### PR TITLE
[WFCORE-3114] Wildfly 10.1.0 add-user command

### PR DESCRIPTION
**Pull request by Dvikasred**
Upstream fix for Bug https://issues.jboss.org/browse/WFCORE-3114

### CODE REVIEW

**Comment by bstansberry** [comment]
The first of these commits is unrelated; please remove it.

**Comment by Dvikasred** [comment]
Thanks for the update,
Do I need to remove  "[WFCORE-3136] Added Generic type CLI commands into docs (CLI guide)" in this pull request ?
OR 
Both the changes I have made is not related ?

**Comment by bstansberry** [comment]
@Dvikasred Please remove the WFCORE-3136 commit.

**Comment by Dvikasred** [comment]
Hi Sure I will do so 
Thanks  a lot for the help

**Comment by Dvikasred** [comment]
Hi,

Thanks for the help. 
As per the request I have revert the "[WFCORE-3136] Added Generic type CLI commands into docs (CLI guide)" Commit. 
Please let me know if you need any support from my side. 

Thanks and Regards,
Vikas Dadhich

**Comment by darranl** [comment]
If I am reading the diff correctly is the proposal to just completely ignore any configured JBOSS_HOME?

**Comment by Dvikasred** [comment]
Yes it is because, While we are running the script.
It is taking the default JBOSS_HOME what set at OS level. 

Once we unset it in script. I will not call the same.

**Comment by Dvikasred** [comment]
It's just like initializing variable with no value. 
I feel which will not create any problem with the existing script(Which is working fine).  
Regarding the warning part. 
In this scenarios we will not face this condition.
Please feel free to share the idea with me. We may find the best one :)
Thanks again for such valuable comments and feedback.

**Comment by darranl** [comment]
I think the opposite question is: -

"What purpose is the code within the script serving now that checks the JBOSS_HOME locations match and emits a warning if the JBOSS_HOME variable is always cleared?"

**Comment by Dvikasred** [comment]
Thanks for the update,
We can either uncomment  and keep it as note or leave it like this. 
This will help others to understand the changes.
Also, If we get some new approach we can use/refer this.

**Comment by darranl** [comment]
My point is, if you take add-user.bat as an example.

Line 21 we discover our local JBOSS_HOME.
Lines 24,25,26 we then check if we have JBOSS_HOME set or use our locally discovered one instead.
Lines 32 to 38 we are comparing the discovered location with the one from the variable and outputting a message if they differ.

If we are going to take the decision to not support using the JBOSS_HOME environment variable then all of this code will need to be cleaned up in the script, otherwise all of this code is redundant and serves no ongoing purpose.

**Comment by Dvikasred** [comment]
I understand this and it was not removed the reason I have mentioned in above comments.
Since this is redundant I will do so. 
Please allow me to go through the test cases in Linux as well as Windows environment. 
thanks again for the feedback.

**Comment by darranl** [comment]
If you are going to have a look at some more testing would it be possible to check why the comparison was not working in the first place?  Maybe that could be double checked to get the error correctly reported.

**Comment by Dvikasred** [comment]
Sure I will check and update the pull request.

**Comment by Dvikasred** [comment]
I have finished testing with Linux.
For windows still it is going on. 
Once everything is done I will commit the changes

**Comment by darranl** [comment]
I suggest we close this one, if the tested changes are available a new PR can be raised.

**Pull request closed without merging**
