### PR TITLE
[WFCORE-3253] Upgrade the wildfly-maven-plugin to version 1.2.0.Final

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.jboss.org/browse/WFCORE-3253

### CODE REVIEW

**Comment by jamezp** [comment]
4.x PR https://github.com/wildfly/wildfly-core/pull/2768

**Comment by jamezp** [comment]
Odd they both failed, but I don't think it's related to the upgrade. retest this please

**Comment by jamezp** [comment]
These failures don't seem related to the version upgrade. I really don't know why they keep failing. Patching does not use the `wildfly-maven-plugin`.

**Comment by jamezp** [comment]
Third time is the charm? retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by jamezp** [comment]
retest this please

**Comment by jamezp** [comment]
retest this please

**Pull request merged**
