### PR TITLE
[WFCORE-2812] make sure column value is shorter than terminal width in SimpleTable.

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/WFCORE-2812
Make sure column value is shorter than terminal width in SimpleTable. Check it with terminalWidth from SimpleTable.addLine method while adding a new line.

AESH upgrade issue https://issues.jboss.org/browse/WFCORE-2840 and https://issues.jboss.org/browse/JBEAP-11013

Jansi has been moved back to 1.11 as prod team preference.

~~Please HOLD. After a discussion with Jean-François by email, more work is required for non interactive mode.~~
Decided to not fix the non interactive mode in current release. it will be tracked in https://issues.jboss.org/browse/JBEAP-11048

### CODE REVIEW

**Comment by soul2zimate** [comment]
I am looking the test failures.

**Comment by soul2zimate** [comment]
retest this please

**Comment by jfdenise** [comment]
As soon as aesh is released (0.66.17), pom.xml will have to be updated.

**Comment by soul2zimate** [comment]
previous CI tests failed because terminal width could be 0 and -1 in some tests, I have updated PR to cover that case.

**Comment by soul2zimate** [comment]
retest this please

**Pull request merged**
