### PR TITLE
[WFCORE-2623] Deprecating domain management methods ....

### PR DESCRIPTION
**Pull request by ropalka**
…onal dependencies configurations

### CODE REVIEW

**Comment by darranl** [comment]
@kabir can you please let me know if this one will be merged?  I will probably get it into ladybird quite quickly if merged as we have other fixes in these classes.

**Comment by ropalka** [comment]
These deprecated methods are used in WildFly so we need to do this change in three steps @bstansberry :
 * first deprecate and provide alternative in Core
 * second switch wildfly to non deprecated methods (once core is updated there)
 * third (and finally) eliminate the deprecated methods
This way we don't break WildFly builds.

**Comment by darranl** [comment]
I would not be surprised of JDG use them as well - deprecation seems safer all round.

**Comment by bstansberry** [comment]
Sounds fine. I see that the static method in SecurityRealm is used. We should replace that use with a capability, but that's a separate thing from what Richard described above.

**Pull request merged**
