### PR TITLE
Fix for WFCORE-1614

### PR DESCRIPTION
**Pull request by jfdenise**
In addition to allow for echoing the command in non interactive mode, the CLI XSD config file has been upgraded to release 3.1. Although the latest XSD was 3.0, the shipped xml config file was still 2.0. I have upgraded the shipped XML file to release 3.1.
The test that was conflicting with WFCORE-1590 has been fixed.

### CODE REVIEW

**Comment by aloubyansky** [comment]
Looks OK to me. Thanks!

**Comment by jfdenise** [comment]
Hold on, one test is now failing locally, investigating.

**Comment by jfdenise** [comment]
The added test was changing the state of the server and was not properly removing some properties, making other tests to fail latter in the run. I am surprised to not have seen it previously. I have fixed this problem.

**Comment by jfdenise** [comment]
retest this please!

**Pull request merged**
