### PR TITLE
WFCORE-6807 Prune deprecations from wildfly-service and wildfly-subsystem

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFCORE-6807

### CODE REVIEW

**Comment by darranl** [comment]
As this module is relatively new it is probably too new that these removals will cause issues but how do we determine when it is safe to remove deprecations like this?

Subsystems and feature packs can be developed outside of the WildFly and WildFly Core repos and may not be keeping up to date at the same cadence as WildFly.

**Comment by pferraro** [comment]
> As this module is relatively new it is probably too new that these removals will cause issues but how do we determine when it is safe to remove deprecations like this?
> 
> Subsystems and feature packs can be developed outside of the WildFly and WildFly Core repos and may not be keeping up to date at the same cadence as WildFly.

FWIW, the methods being removed here were introduced in 23.0.0.Final and deprecated for removal in 24.0.0.Final.
There is only one external repo of which I am aware that uses wildfly-service/subsystem (https://github.com/wildfly-extras/mvc-krazo-feature-pack), and it is unaffected.
I think it would be unwise to delay these removals too long lest they end up in a downstream release.

**Review by yersan — APPROVED** [review]
I agreed with Paul on this, so I approved from my side

@darranl Do you still have concerns with these removals?

**Review by darranl — APPROVED** [review]

**Comment by yersan** [comment]
Thanks @pferraro @darranl

**Pull request merged**
