### PR TITLE
[WFCORE-4341] Upgrade Undertow version

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.jboss.org/browse/WFCORE-4341

### CODE REVIEW

**Comment by bstansberry** [comment]
@kabir  Any ideas? This failure indicates some sort of classloading problem:

```
java.lang.AssertionError: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-19" => "WFLYCTL0158: Operation handler failed: java.util.ServiceConfigurationError: io.undertow.attribute.ExchangeAttributeBuilder: Provider io.undertow.attribute.RemoteObfuscatedIPAttribute$Builder not a subtype"}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.jboss.as.model.test.ModelTestUtils.checkOutcome(ModelTestUtils.java:134)
	at org.jboss.as.model.test.ModelTestUtils.checkFailedTransformedBootOperations(ModelTestUtils.java:627)
	at org.wildfly.extension.undertow.UndertowTransformersTestCase.doRejectTest(UndertowTransformersTestCase.java:211)
	at org.wildfly.extension.undertow.UndertowTransformersTestCase.testRejectTransformersEAP_7_1_0(UndertowTransformersTestCase.java:152)
```

RemoteObfuscatedIPAttribute is new in 2.0.18 and is listed there in a META-INF/services/io.undertow.attribute.ExchangeAttributeBuilder file. This Error indicates a ServiceLoader is doing its thing, is finding this entry, trying to load the service impl but failing because the service impl is not implementing the expected interface. That tells me the expected interface is from the legacy undertow version but somehow 2.0.18 is visible too.

This shows that for EAP 7.1 transformer tests the legacy controller should be using the legacy undertow jars:

https://github.com/wildfly/wildfly/blob/master/undertow/src/test/java/org/wildfly/extension/undertow/UndertowTransformersTestCase.java#L280

So I see pieces of the puzzle but don't really know what to do with them yet.

**Comment by bstansberry** [comment]
Never mind @kabir -- we figured out a solution. Temporary workaround and a longer term fix.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I put the hold label on this as there's another release planned.

**Comment by fl4via** [comment]
Retest this please

**Pull request merged**
