### PR TITLE
[WFCORE-149]:  Failures in 'resolve-expression" op appear in server log.

### PR DESCRIPTION
**Pull request by ehsavoie**
The handler doesn't fail but returns a failure instead.

Jira: https://issues.jboss.org/browse/WFCORE-149

### CODE REVIEW

**Comment by bstansberry** [comment]
@ehsavoie Why does setting the failure description need to be done in a ResultHandler?

**Comment by ehsavoie** [comment]
because otherwise the step is marked as failed and a trace is automatically added if we are in model/runtime phase.

**Comment by bstansberry** [comment]
I was concerned about the impact of delaying reporting the failure so I played around:

```
[standalone@embedded /] :resolve-expression(expression=${foo})
{
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0211: Cannot resolve expression '${foo}'"
}
[standalone@embedded /] batch
[standalone@embedded / #] /system-property=foo:add(value=bar)
[standalone@embedded / #] :resolve-expression(expression=${foo})
[standalone@embedded / #] :resolve-expression(expression=${bar})
[standalone@embedded / #] run-batch
The batch executed successfully
[standalone@embedded /] :composite(steps=[{operation=resolve-expression,expression=${foo}},{operation=resolve-expression,expression=${bar}}])
{
    "outcome" => "success",
    "result" => {
        "step-1" => {
            "outcome" => "success",
            "result" => "bar"
        },
        "step-2" => {
            "outcome" => "failed",
            "failure-description" => "WFLYCTL0211: Cannot resolve expression '${bar}'"
        }
    }
}
```

This shows deferring the failure reporting does result in the step reporting "outcome" => "failed", which is good, but it doesn't result in the overall op failing, which is bad. Granted, this is an edge case but I don't want to introduce a new failure handling semantic just for this case. I have an idea about what to do though.

**Comment by bstansberry** [comment]
The last commit at https://github.com/bstansberry/wildfly-core/commits/WFCORE-149 seems to take care of the problem:

```
[standalone@embedded /] :resolve-expression(expression=${foo})
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0211: Cannot resolve expression '${foo}'",
}
[standalone@embedded /] batch
[standalone@embedded / #] /system-property=foo:add(value=bar)
[standalone@embedded / #] :resolve-expression(expression=${foo})
[standalone@embedded / #] :resolve-expression(expression=${bar})
[standalone@embedded / #] run-batch 
The batch failed with the following error (you are remaining in the batch editing mode to have a chance to correct the error): {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-3" => "WFLYCTL0211: Cannot resolve expression '${bar}'"}}
[standalone@embedded / #] discard-batch 
[standalone@embedded /] :composite(steps=[{operation=resolve-expression,expression=${foo}},{operation=resolve-expression,expression=${bar}}])
{
    "outcome" => "failed",
    "result" => {
        "step-1" => {
            "outcome" => "failed",
            "failure-description" => "WFLYCTL0211: Cannot resolve expression '${foo}'",
            "rolled-back" => true
        },
        "step-2" => {
            "outcome" => "failed",
            "rolled-back" => true
        }
    },
    "failure-description" => {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => "WFLYCTL0211: Cannot resolve expression '${foo}'"}},
    "rolled-back" => true
}

```

**Comment by bstansberry** [comment]
Checkstyle problem:

```
[21:22:21][org.wildfly.core:wildfly-controller] C:\BuildAgent\work\db872761b443af46\core\controller\src\main\java\org\jboss\as\controller\operations\common\ResolveExpressionHandler.java:98: Line has trailing spaces.
[21:22:21][org.wildfly.core:wildfly-controller] Audit done.
[21:22:21][org.wildfly.core:wildfly-controller] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (check-style) on project wildfly-controller: An error has occurred in Checkstyle report generation.
```

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
