### PR TITLE
[WFCORE-3527] Removing OSGi from WildFly-Core

### PR DESCRIPTION
**Pull request by ropalka**

### CODE REVIEW

**Comment by bstansberry** [comment]
@aloubyansky @jamezp please approve

Alexey the main thing I wonder here is whether in the updated patching tests some of the use of 'osgi' is important to the tests, not because the test is concerned with anything about osgi but because the test is evaluating certain structures, and 'osgi' just happened to be a name given to something that could just as well have been called 'foo'.

**Comment by jamezp** [comment]
It looks like in logging we just removed the check to see if there was a module attachment. Do we really need to remove that? I do recall it only being there for OSGi, but it seems like a harmless check to leave in there.

**Comment by ropalka** [comment]
Attachments.MODULE is always attached to DeploymentUnit @jamezp - there's no need for check.
In the past it wasn't always true because of OSGi integration.

**Comment by kabir** [comment]
@ropalka Needs a rebase

**Comment by ropalka** [comment]
Rebased @kabir

**Comment by jmesnil** [comment]
@aloubyansky could you review it please?

**Comment by ropalka** [comment]
Updated @wildfly/mergers-core

**Comment by ropalka** [comment]
How about this PR @jmesnil . What else needs to be accomplished here?

**Comment by jmesnil** [comment]
@ropalka PR looks good to me. I'm just waiting for @aloubyansky approval wrt to patching before we can merge it.

**Pull request merged**
