### PR TITLE
[WFCORE-3511] Improve test coverage of WFCORE-3236

### PR DESCRIPTION
**Pull request by dudaerich**
This should be merged after #3016 and #3019, because it changes the same files and it may cause conflicts.

### CODE REVIEW

**Comment by bstansberry** [comment]
It caused conflicts. :)

**Comment by dudaerich** [comment]
I've resolved them :)

**Comment by jfdenise** [comment]
Approved, thanks!

**Comment by bstansberry** [comment]
this is ok to test

**Pull request merged**
