### PR TITLE
Upgrade aesh to 0.66.3 to fix WFCORE-1277

### PR DESCRIPTION
**Pull request by soul2zimate**
Upgrade aesh to 0.66.3
https://issues.jboss.org/browse/WFCORE-1277

### CODE REVIEW

**Comment by bstansberry** [comment]
Can you backport this to wildfly-core-eap? Until we release WildFly 10.0.0.Final we are not putting stuff into master without a wildfly-core-eap PR.

Thanks for your help on this!

**Comment by soul2zimate** [comment]
sure, thought it needs productized version. I have opened https://github.com/jbossas/wildfly-core-eap/pull/136

**Comment by bstansberry** [comment]
Thanks. I don't know about the process for CPs, but for work on majors and minors we normally upgrade to the community version first and then the productization team updates to the productized version later. That avoids delays in getting things into CI testing, blocking other fixes, etc.

**Comment by soul2zimate** [comment]
Yes, this makes sense to me. 
In CP release,  almost every component upgrade has an upstream issue, which has been tested there first to reveal any possible regression. Thus, we upgrade directly with prod version.

**Pull request merged**
