### PR TITLE
[WFCORE-1408] - add DOM registry path export to JDK modules

### PR DESCRIPTION
**Pull request by baranowb**
https://issues.jboss.org/browse/WFCORE-1408

### CODE REVIEW

**Comment by dmlloyd** [comment]
What problem is solved here? The JIRA is very vague.

**Comment by baranowb** [comment]
For some reason description did not save. Fixed.

Deplotment are not able to access JDK default registry:
java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.dom.DOMXSImplementationSourceImpl from [Module "deployment.dom-registry-test:main" from Service Module Loader]

**Comment by n1hility** [comment]
I'm not sure this is right, we shouldn't need to import JDK parser implementation classes, as the redirect mechanism should take care of this. I'll have to research this later though.

**Comment by baranowb** [comment]
What redirect mechanism?

**Comment by ctomc** [comment]
jboss modules jaxp redirect, https://github.com/jboss-modules/jboss-modules/tree/master/src/main/java/__redirected

**Comment by dmlloyd** [comment]
This change is almost certainly not correct and is out of date.  Can we close?

**Comment by baranowb** [comment]
I'd say, forgot about this PR any way.

**Comment by jmesnil** [comment]
closing this pull request as it is out of date.

**Pull request closed without merging**
