### PR TITLE
[HOLD] Fix for WFCORE-5835, Missing modular export when enabling dns.ping protocol

### PR DESCRIPTION
**Pull request by jfdenise**
Issue: https://issues.redhat.com/browse/WFCORE-5835
This PR is on hold, do not merge. Fix could be applied differently.

### CODE REVIEW

**Comment by jfdenise** [comment]
@ropalka , if you could give an eye. Once merged it would conflict with the PR you opened: https://github.com/wildfly/wildfly-core/pull/4966

**Review by ropalka — APPROVED** [review]
LGTM @jfdenise , just FYI my PR you mentioned above is not going to be applied soon. It turned into discussion PR for now.

**Comment by jfdenise** [comment]
@ropalka , thank-you. I put this PR on hold for now, there are some discussions for this one too.

**Comment by jfdenise** [comment]
@bstansberry @pferraro should we still hold this PR? Thank-you.

**Comment by bstansberry** [comment]
@jfdenise -- @pferraro can confirm but IIRC this what not a change we wanted to make outside of the cloud context.

**Comment by jfdenise** [comment]
@bstansberry , Ok, that is something that we can handle in the cloud if @pferraro confirms.

**Comment by bstansberry** [comment]
BTW, my concern about this was the reference to the jdk.* module and the impact that might have on users who want to run with a slimmed JVM. Unfortunately you can't add JPMS settings that refer to non-existent modules, so it's not safe to just add stuff.

**Comment by jfdenise** [comment]
Closing, will be handled at the cloud level.

**Pull request closed without merging**
