### PR TITLE
[WFCORE-1514] Add '!' operator for operation arguments

### PR DESCRIPTION
**Pull request by jfdenise**
Added support for the "!" operator for operation. 
Removed remote call to retrieve operation description, boolean values are set according to command syntax (implicit value == true, ! == false)

### CODE REVIEW

**Comment by jfdenise** [comment]
retest this please!

**Comment by jfdenise** [comment]
retest this please!

**Comment by jfdenise** [comment]
The failure is unrelated to the changes, re-running the test

**Comment by bstansberry** [comment]
@aloubyansky please approve

**Comment by aloubyansky** [comment]
Approved. Thanks!

**Pull request merged**
