### PR TITLE
[WFCORE-1565] Upgrade JBoss Remoting to 4.0.21.Final

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Supercedes #1578.

**Comment by dmlloyd** [comment]
Caused by: java.io.IOException: No space left on device - guess we'll have to try again Monday.

**Comment by ctomc** [comment]
@dmlloyd build ate up 3.7gb of disk space? Could this be related to the change?

**Comment by dmlloyd** [comment]
Failure unrelated (see https://issues.jboss.org/browse/WFLY-6624 )

**Comment by jamezp** [comment]
retest this please

**Pull request merged**
