### PR TITLE
[WFCORE-3825] Unify "-server" option usage for HostController and DomainController in domain.ps1

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFCORE-3825
https://issues.redhat.com/browse/JBEAP-15433

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
FYI @lvydra , the windows error looks legit

**Comment by lvydra** [comment]
Thanks @yersan , it should be fixed now.

**Review by yersan — APPROVED** [review]
The changes look good to me, they are accordingly to the domain.bat counterpart

**Comment by jmesnil** [comment]
@lvydra thanks

**Pull request merged**
