### PR TITLE
[WFCORE-6891] Remove support for parsing domain management schemas prior to urn:jboss:domain:1.7

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-6891

### CODE REVIEW

**Comment by darranl** [comment]
Hi @yersan FYI this one has a risk of going stale and being complex to update.

**Comment by yersan** [comment]
@darranl Would you mind adding a short description to the Jira to understand the motivation better and why is 1.7 the cut for legacy schema versions? thanks

**Comment by darranl** [comment]
@yersan done

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
Thanks @darranl

**Pull request merged**
