### PR TITLE
[WFCORE-5940] Add java.desktop dependency for Elytron Tool

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/WFCORE-5940

### CODE REVIEW

**Comment by petrberan** [comment]
Changes in this PR should be merged to WFCORE together with Elytron upgrade [WFCORE-5939](https://issues.redhat.com/browse/WFCORE-5939) only if the Elytron upgrade contains the web option for Elytron Tool [ELY-2343](https://issues.redhat.com/browse/ELY-2343)

**Comment by petrberan** [comment]
This PR is still active

**Comment by petrberan** [comment]
This PR is still active

**Comment by petrberan** [comment]
This PR is still active

**Comment by bstansberry** [comment]
@petrberan Thanks for this, but I'd prefer that you coordinate with @fjuma so this commit comes in as part of the Elytron upgrade that brings in the [ELY-2343](https://issues.redhat.com/browse/ELY-2343) fix.

**Pull request closed without merging**
