### PR TITLE
[WFCORE-2917] allow-all-mechanisms, allow/forbid-sasl-mechanisms removing

### PR DESCRIPTION
**Pull request by honza889**
Removed allow-all-mechanisms, allow/forbid-sasl-mechanisms attributes, which are redundant to sasl-mechanism-selector.

https://issues.jboss.org/browse/WFCORE-2917
https://issues.jboss.org/browse/JBEAP-11209

Need to be merged in coordination with https://github.com/wildfly-security/wildfly-elytron/pull/855

### CODE REVIEW

**Comment by darranl** [comment]
@claudio4j / @hpehl FYI - Assuming approved can you please confirm a suitable time to be merged?

**Comment by claudio4j** [comment]
@darranl there is no need to change in HAL as the attributes are automatically handled by read-resource-description operation, as long as r-r-d is correct.

**Comment by darranl** [comment]
Thanks @claudio4j we can get this one through.

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
