### PR TITLE
[WFCORE-4472] Upgrade Undertow to 2.0.21.Final

### PR DESCRIPTION
**Pull request by fl4via**
https://issues.jboss.org/browse/WFCORE-4472

### CODE REVIEW

**Comment by fl4via** [comment]
Unfortunately we have a timeout for FullIntegration Windows. I've triggered a new run of that one

**Comment by jmesnil** [comment]
I've put a hold flag on the PRS #3788 #3787 and #3786 as a reminder to merge them all at once when they pass. They are all approved (the component upgrades are fine) but they are closely related and I'd prefer to run a full CI jobs with the 3 altogether.

For now, #3786 is showing genuine failures that must be fixed.

**Comment by fl4via** [comment]
the cause of the failures is REM3-336 (https://issues.jboss.org/browse/REM3-336) and I'm cutting a new release of remoting with that fix. This PR is not affected by that bug, because the problem was not in xnio, and is good to go. I'll rebase though so that  tests with latest changes can be run

**Comment by fl4via** [comment]
Tests passed, this PR is ready to go

**Pull request merged**
