### PR TITLE
[WFCORE-6034] Upgrade log4j2 2.19.0

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFCORE-6034

### CODE REVIEW

**Comment by boris-unckel** [comment]
This is currently blocked by https://issues.apache.org/jira/browse/LOG4J2-3579

**Comment by boris-unckel** [comment]
The service loader issue has been resolved. Please find all links in the Jira.

**Review by yersan — COMMENTED** [review]
@jamezp Would you mind approving this component upgrade? I'm not 100% sure if we should proceed with it at this stage, in any case, the testsuite looks good, so in general, I'm fine with it.

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
@yersan It looks good to me. If we want to wait until the next release that seems reasonable to me. I'm fine with putting it in now though too. Which ever you're more comfortable with.

**Comment by yersan** [comment]
@boris-unckel , thank you !

**Pull request merged**
