### PR TITLE
[WFCORE-673] Elytron Core Integration

### PR DESCRIPTION
**Pull request by darranl**
:exclamation: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :exclamation:

This pull request is a foundation for making it possible to enable Elytron backed security for the EJB and Undertow subsystems for in-VM invocations and invocations over HTTP.  

Although the Elytron web module is not used directly by core as a result of this pull request it will be in a subsequent pull request where it will be used for management HTTP authentication so the module is added here rather than to WildFly.

This pull request will break the WildFly build, I will follow up with two pull requests to the WildFly repository: -
 1 - A minimal PR that makes WildFly compatible with this PR.

https://github.com/wildfly/wildfly/pull/9160

 2 - A more complete PR that makes it possible to enable Elytron for EJB and Undertow and also incorporates the commits from 1.

https://github.com/wildfly/wildfly/pull/9161

### CODE REVIEW

**Comment by n1hility** [comment]
retest this please

**Comment by bstansberry** [comment]
Please add links to custom runs of https://ci.wildfly.org/viewType.html?buildTypeId=WF_WildFlyCoreIntegrationExperiments that show results of the combination of this branch and the branch for https://github.com/wildfly/wildfly/pull/9160, plus another one for this branch plus https://github.com/wildfly/wildfly/pull/9161

If you add change any of the branches please do new custom runs and link them

**Comment by darranl** [comment]
We have just added a new release of PicketBox 5 - the WildFly Core changes should be able to go in before the WildFly changes.

**Comment by darranl** [comment]
Retest this please.

**Comment by bstansberry** [comment]
@ehsavoie Please @Ignore PreparedResponseTestCase.

**Pull request merged**
