### PR TITLE
Wfcore 505 test

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/WFCORE-505
I found that previous fix I made in WFCORE-505 is incomplete.
Add a test to cover the scenario.

### CODE REVIEW

**Comment by soul2zimate** [comment]
org.jboss.as.test.integration.ejb.stateful.passivation.PassivationTestCase.testPassivationMaxSize: <no details avaliable>
I have seem this intermittent failure in other pull request. 
retest this please.

**Comment by bstansberry** [comment]
@ehsavioie Can you approve this or suggest changes?

Chao Wang -- can you squash this to one commit please? 

Thanks.

**Comment by soul2zimate** [comment]
rebase as per Emmanuel's comment and squash, it deletes @ehsavioie 's comment : (

**Comment by soul2zimate** [comment]
irrelevant failure, retest this please

**Pull request merged**
