### PR TITLE
Fix for WFCORE-4402, Upgrade CLI to use aesh 2.3

### PR DESCRIPTION
**Pull request by jfdenise**
Fix for: https://issues.jboss.org/browse/WFCORE-4402 and https://issues.jboss.org/browse/WFCORE-4408

- Aesh release contains jansi upgrade needed to fix dll copy on Windows.
- jansi upgrade to the one expected by aesh.

### CODE REVIEW

**Comment by jfdenise** [comment]
@jmesnil , I realize that Wildfly has its own version of jansi, I also need to upgrade this dependency.

**Comment by jfdenise** [comment]
@darranl , please wait before to merge this one, it is incomplete.

**Comment by jfdenise** [comment]
@darranl , @jmesnil I just pushed the jansi upgrade.

**Comment by darranl** [comment]
@jfdenise The Linux JDK8 job appears a couple of times now to have a number of identity operation failures and a hang, as this PR is in relation to UI component upgrades that are likely involved in these test scenarios are you able to take a look?

**Comment by jfdenise** [comment]
@darranl , I don't see evidence of usage of aesh/jansi in these tests, where do you see these UI components in use in these tests?

**Comment by darranl** [comment]
Another PR has the same errors so looks like not related to this component upgrade https://github.com/wildfly/wildfly-core/pull/3736

**Pull request merged**
