### PR TITLE
WFLY-5227 - Move security-manager from wildfly to wildfly-core

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
@sguilhen @dmlloyd @darranl Could you guys take a quick look over this and let me know if it looks ok? Particlularly the last commit & jboss-metadata, there were some additional message merged in manually, as msg numbers overlapped etc, I assumed those were still relevant.

**Comment by sguilhen** [comment]
@luck3y It looks good to me.

**Comment by luck3y** [comment]
CI run with full: https://ci.wildfly.org/viewLog.html?buildId=36006&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

**Comment by luck3y** [comment]
Hopefully successful run in CI, due to some confustion of -SNAPSHOT vs not  :(

https://ci.wildfly.org/viewLog.html?buildId=36033&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

**Pull request merged**
