### PR TITLE
WFCORE-5581 Upgrade Jandex to 2.4.0.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFCORE-5581

### CODE REVIEW

**Comment by jmesnil** [comment]
diff to previous integrated release: https://github.com/wildfly/jandex/compare/2.2.3.Final...2.4.0.Final

**Review by jmesnil — APPROVED** [review]
@pferraro LGTM.
@bstansberry do you see any issue with bumping Jandex for WildFly 25?

**Comment by pferraro** [comment]
FYI, this upgrade is required by the most recent release of smallrye-open-api.

**Review by bstansberry — APPROVED** [review]
This is fine for WF 25.

**Comment by jmesnil** [comment]
@pferraro thanks

**Pull request merged**
