### PR TITLE
[WFCORE-3832][WFCORE-3542] Elytron jdbc-realm - hash encoding and ModularCrypt

### PR DESCRIPTION
**Pull request by hkalina**
based on https://github.com/wildfly/wildfly-core/pull/3475

jdbc-realm:
* added hash-encoding/salt-encoding: https://issues.jboss.org/browse/WFCORE-3832
* added modular-crypt-mapper: https://issues.jboss.org/browse/WFCORE-3542 (bundled as requested by @darranl )
* refactoring: removed non-public dead code

### CODE REVIEW

**Comment by darranl** [comment]
This one I agree should be an RFE, we are adding support to Elytron for something it has never done before.

**Comment by hkalina** [comment]
Rebased to be based on https://github.com/wildfly-security-incubator/wildfly-core/tree/WFCORE-3858
Closing PR until requirements (the base and elytron upgrade) will be merged.

**Comment by jmesnil** [comment]
https://issues.jboss.org/browse/WFCORE-3832 is a RFE and should follow our process for new features.

**Comment by hkalina** [comment]
It already have https://issues.jboss.org/browse/PRODMGT-1878 - is not it sufficient?

**Comment by darranl** [comment]
I would suggest close this PR for now, I have created an RFE issue for this - if we get an assignee they can pick this one up.

**Pull request closed without merging**
