### PR TITLE
[WFCORE-4612] ExternalModuleDependencySpecService should make depende...

### PR DESCRIPTION
**Pull request by bstansberry**
…ncies on 'javaee.api' optional

https://issues.jboss.org/browse/WFCORE-4612

This allows app dependencies added via Class-Path entries in MANIFEST.MF or from files in $JBOSS_HOME/lib/ext or the java.ext.dirs dirs to work even with no javaee.api module provisioned. Of course the dependency can't need any of the javaee.api artifacts.

@yersan @jfdenise FYI.

Replaces #3906 which had an incorrect branch name.

I added a second commit here that goes beyond making the javaee.api dep optional and instead adds individual optional deps on the various EE API modules. This allows things to depend on whatever is provisioned without requiring irrelevant things to be provisioned.

### CODE REVIEW

**Comment by jamezp** [comment]
I'm sure this has been considered, but I just didn't see any comments about it. This feels a bit odd being in core as any new dependency in full will require a change in core and I assume a core upgrade before the new dependency in full can be merged.

**Comment by bstansberry** [comment]
@jamezp Yes, the dual maintenance is my main concern with this.

An alternative I'd considered was to add a new 'wildflyee.api' module to core with these in it as optional deps. And then javaee.api in full would just become an alias to wildflyee.api, with a comment explaining where to go to add more specs. So only 1 place to maintain.  But because Galleon uses passive+ provisioning for WF (https://docs.wildfly.org/galleon/#_feature_pack_original_effective_package_set) the effect is Galleon would provision all the 'optional' packages, defeating the slimming goal (somewhat.)

Hmm, perhaps I could make 'wildflyee.api' a dynamic module. So Galleon is unaware.

**Comment by yersan** [comment]
@bstansberry Are you planning to squash this before merging? It is going to introduce conflict with one of my PR, so I was planning to update my PR onto these changes resolving the conflicts, but there are two commits, just asking

**Comment by bstansberry** [comment]
@yersan I rebased; thanks for the reminder!

**Pull request merged**
