### PR TITLE
[WFCORE-5945][WFCORE-5941] upgraded WildFly OpenSSL to 2.2.3.Final an…

### PR DESCRIPTION
**Pull request by istudens**
…d OpenSSL Natives to 2.2.2.Final

Issue: 
https://issues.redhat.com/browse/WFCORE-5941
https://issues.redhat.com/browse/WFCORE-5945

### CODE REVIEW

**Comment by istudens** [comment]
@fjuma could you review this please? thanks

**Comment by fjuma** [comment]
@istudens I haven't been able to release the community artifacts yet due to the issue I mentioned earlier so this PR won't pass CI until that happens.

**Comment by istudens** [comment]
@fjuma ah, ok

**Comment by fjuma** [comment]
Just a very small style comment, it's better to have a separate commit for each component upgrade. So having two commits in this PR would be better.

**Comment by istudens** [comment]
@fjuma good point, I've fixed that.

**Comment by fjuma** [comment]
Looks good, thanks @istudens!

**Comment by yersan** [comment]
@fjuma would you mind pinging here when the OpenSSL is available on maven central? Thanks!

**Comment by fjuma** [comment]
@yersan Will do.

**Comment by fjuma** [comment]
I've released WildFly OpenSSL 2.2.3.Final and WildFly OpenSSL Natives 2.2.2.Final so will re-trigger CI here and will remove the hold label.

**Comment by fjuma** [comment]
@yersan Just FYI, I needed to do the WildFly OpenSSL Natives Linux release on Ubuntu and something went wrong, resulting in the CI failures here. Will need to fix this Friday morning.

**Comment by fjuma** [comment]
I needed to rebuild and release the WildFly OpenSSL Linux Natives. I'm going to close this PR since I've now created a new one that supersedes this one:

https://github.com/wildfly/wildfly-core/pull/5162

**Pull request closed without merging**
