### PR TITLE
Update to Remoting 4.0.19.Final

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
Those tests failed with "failed to establish view [node-0, node-1] within 15000 ms." hinting at network problem.

**Comment by bstansberry** [comment]
This is the root of the recent failure:

[18:55:48][org.wildfly:wildfly-ts-integ-basic] Running org.jboss.as.test.integration.jca.moduledeployment.MultiObjectActivationFlatTestCase
[19:20:32][org.wildfly:wildfly-ts-integ-basic] 
[19:20:32][org.wildfly:wildfly-ts-integ-basic] Results :
[19:20:32][org.wildfly:wildfly-ts-integ-basic] 
[19:20:32][org.wildfly:wildfly-ts-integ-basic] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0
[19:20:32][org.wildfly:wildfly-ts-integ-basic] 
[19:20:32][org.wildfly:wildfly-ts-integ-basic] [ERROR] There was a timeout or other error in the fork

**Comment by bstansberry** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
