### PR TITLE
[WFCORE-819] Add test for checking order of subsystem after cloning

### PR DESCRIPTION
**Pull request by marekkopecky**
[WFCORE-819] Add test for checking order of subsystem after profile cloning

https://issues.jboss.org/browse/WFCORE-819

This test covers functionality from https://issues.jboss.org/browse/WFCORE-812

### CODE REVIEW

**Comment by marekkopecky** [comment]
retest this please

**Comment by marekkopecky** [comment]
retest this please

**Comment by bstansberry** [comment]
This looks fine but it now has a minor merge conflict that needs to be resolved.

**Comment by bstansberry** [comment]
Superceded by #912, which is just a rebase w/ merge conflicts fixed. That's merged. Thanks!

**Pull request closed without merging**
