### PR TITLE
[WFCORE-872] Add version 5 of the management schema and model.

### PR DESCRIPTION
**Pull request by darranl**
:exclamation: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :exclamation:

### CODE REVIEW

**Comment by darranl** [comment]
The WildFly side of this pull request can be found here https://github.com/wildfly/wildfly/pull/8583

**Comment by darranl** [comment]
I am going to hold off merging the latest changes from core until we know we are ready to merge this.

**Comment by bstansberry** [comment]
My expectation is this will be held up until Jason moves full wildfly's master branch to 11.x.

**Comment by bstansberry** [comment]
@darranl if you can review https://github.com/wildfly/wildfly/pull/8813 I can merge it once ok. Then I can set up the system property in the CI jobs and this PR will be ready for rebase.

**Comment by bstansberry** [comment]
@darranl That PR is merged and the CI jobs updated, so this one is ready for rebasing.

**Comment by TomasHofman** [comment]
I will rebase today

**Comment by TomasHofman** [comment]
Sorry, wrong PR.

**Comment by darranl** [comment]
Retest this please.

**Comment by bstansberry** [comment]
retest this please

**Comment by darranl** [comment]
Clustering failure - that's a pass ;-)

retest this please

**Pull request merged**
