### PR TITLE
new jboss-parent & checkstyle

### PR DESCRIPTION
**Pull request by ctomc**
+ fixes in codestyle new checkstyle found

### CODE REVIEW

**Comment by kabir** [comment]
Retest this please

**Comment by jamezp** [comment]
The new parent brings in version 3.2 of the `maven-compiler-plugin` which can cause compile issues with annotation processors. https://jira.codehaus.org/browse/MCOMPILER-236 I want to look at this further before allowing that version of the compiler in.

**Comment by jamezp** [comment]
Setting the `useIncrementalCompilation` to `false` in the compiler configuration seems to workaround this error. Is there a reason we need 3.2? I'd be more comfortable leaving it at 3.1 unless we have a compelling reason to upgrade.

**Comment by ctomc** [comment]
3.2 fixes problem with not properly displayed logging/output from annotation processors. Fix that David contributed.
I don't mind disabling incremental compilation if that causes problems. Did you saw this problem manifest also in any of our projects?

**Comment by jamezp** [comment]
Yeah. I can replicate it quite easily by doing a `mvn clean install && mvn install`. The second one fails.

**Pull request closed without merging**
