### PR TITLE
[WFCORE-5255] / [WFCORE-5169] Migrate all tests to use Apache DS AM26 and org.apache.directory.api 2.0.0

### PR DESCRIPTION
**Pull request by SoniaZaldana**
https://issues.redhat.com/browse/WFCORE-5255
https://issues.redhat.com/browse/WFCORE-5169

### CODE REVIEW

**Comment by bstansberry** [comment]
@darranl This one I'll leave to you. It LGTM and passes CI but you call out various points in the JIRA description that I don't know enough about to see if they are covered.  Thanks for this @SoniaZaldana

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
@SoniaZaldana we have a merge conflict in the pom, if you can please correct that I think we can get this through.

**Comment by SoniaZaldana** [comment]
Sorry for the delay @darranl. I resolved the conflict.

**Pull request merged**
