### PR TITLE
Fix transformer tests

### PR DESCRIPTION
**Pull request by kabir**
Reintroduces ModelTestModelControllerService.DelegatingResourceDefinition removed in commit https://github.com/ctomc/wildfly-core/commit/d313f87c4ff1ea6019aad5f9aebc5734227d3304#diff-8d29306104c6abe7fc7a909ab2803f9d  
of 
https://github.com/wildfly/wildfly-core/pull/535. 

Before merging both the core and the wildfly integration tests should be run with -Djboss.test.transformers.eap

### CODE REVIEW

**Comment by ctomc** [comment]
hold this one a bit, I will send less invasive PR

**Comment by kabir** [comment]
WildFly core integration experiments job http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=49519&buildTypeId=WF_WildFlyCoreIntegrationExperiments&tab=buildLog has the -Djboss.test.transformers.eap property set

**Comment by ctomc** [comment]
last CI run was with eap tranformers included.
looks good to me.

**Comment by kabir** [comment]
http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=49585&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments has the -Djboss.test.transformers.eap property set

**Pull request merged**
