### PR TITLE
[WFCORE-5205] Use new Module.findServices() utility method to load security providers

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-5205

### CODE REVIEW

**Comment by ropalka** [comment]
@darranl please review

**Comment by fjuma** [comment]
@ropalka Just noticed that the 4 tests in `TlsTestCase` that make use of the `openssl` provider seem to be getting ignored in the Linux - JDK 11 run:

https://ci.wildfly.org/buildConfiguration/WildFlyCore_PullRequest_LinuxJdk9/232561?buildTab=tests&pager.currentPage=1&filterText=OpenSSL

These shouldn't be getting ignored since the Linux CI agents do have the OpenSSL library installed. So it seems like the `openssl` provider isn't getting loaded for some reason.

**Comment by ropalka** [comment]
These excluded tests are not related to this PR @fjuma - I can see them ignored also on WildFly master

**Comment by ropalka** [comment]
I created https://issues.redhat.com/browse/WFCORE-5219 to don't block this PR @fjuma @darranl

**Comment by darranl** [comment]
@ropalka I think we are ready to go on this one but it looks like we have a merge conflict as the ProviderDefinitions was refactored for a feature.  Let me know if you will handle the conflict or if you would like me to follow up.

**Comment by ropalka** [comment]
Fixed @darranl

**Comment by ropalka** [comment]
The failure is unrelated to this PR. It happened because of insufficient disk space left device - see exception.

**Review by darranl — APPROVED** [review]
Thank you @ropalka giving CI one more try and then this is ready to go in.

**Pull request merged**
