### PR TITLE
[WFCORE-808]  Remove op handling must properly remove child resources

### PR DESCRIPTION
**Pull request by bstansberry**
Changes the standard base remove handler to add steps to remove children.

This allows removal of entire profiles in a single op.

Also includes the commits from #877 and #879, which are needed for the recursive removal to work properly.

For the WildFly full testsuite to pass, https://github.com/wildfly/wildfly/pull/7734 will first need to be merged downstream.

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

Core - Full Integration failure was due to the job being misconfigured.

**Comment by kabir** [comment]
:+1:

**Comment by bstansberry** [comment]
https://github.com/wildfly/wildfly/pull/7763 will hopefully fix the MixedDomain failure.

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
