### PR TITLE
WFCORE-3794 Undertow 2.0.5.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**
https://issues.jboss.org/browse/WFCORE-3794

### CODE REVIEW

**Comment by jmesnil** [comment]
@stuartwdouglas both Linux and Windows Full integration jobs have the same regressions that are likely caused by the PR. Is there a pending PR in wildfly related to this undertow upgrade?

**Comment by stuartwdouglas** [comment]
@jmesnil it must be some kind of regression in Undertow, I am looking into it.

**Comment by stuartwdouglas** [comment]
I have pushed a snapshot and updated the PR to use that for testing overnight, if it is sucessful I will cut a new release in the morning.

**Comment by stuartwdouglas** [comment]
Retest this please

**Pull request merged**
