### PR TITLE
[WFCORE-5438] For modular VMs include --add-exports=java.naming/com.s…

### PR DESCRIPTION
**Pull request by bstansberry**
…un.jndi.ldap=ALL-UNNAMED

https://issues.redhat.com/browse/WFCORE-5438

### CODE REVIEW

**Comment by bstansberry** [comment]
@darranl @jmesnil It looks like the 16.0.0.Beta5 release hasn't been tagged yet. If so if CI on this is ok it would be good to get in.

**Review by ropalka — APPROVED** [review]
LGTM

**Comment by ropalka** [comment]
What about 16.0.0.Beta5 release I'm observing JDK17 failures there after Elytron upgrade @bstansberry . I asked @darranl 's team to have a look at those. Just FYI.

**Comment by bstansberry** [comment]
This didn't make 16.0.0.Beta5.

**Pull request merged**
