### PR TITLE
[WFCORE-3133] - [Migration operation] [Web to Undertow] truststore - ke…

### PR DESCRIPTION
**Pull request by JiriOndrusek**
…ystore-password does it really needs to be mandatory?

WFCORE: https://issues.jboss.org/browse/WFCORE-3133

(part of solution for: https://github.com/wildfly/wildfly/pull/10381)

### CODE REVIEW

**Comment by bstansberry** [comment]
Please correct the commit message and the PR title to reflect the WFCORE issue. Thanks.

**Comment by bstansberry** [comment]
I'm not clear on what this has to do with Web to Undertow migration.

**Comment by bstansberry** [comment]
@JiriOndrusek Any update on this one?

**Comment by JiriOndrusek** [comment]
@bstansberry @darranl I'm sorry for the delay (I've missed notifications), I'll look into it.

**Comment by JiriOndrusek** [comment]
@darranl May I ask for clarification of you change request? 
I have tried migration without trusstore password and it works (with the wildfly from master with changes from this PR and linked one) -> password for trusstore is optional.
For the keystore it behaves in the same way, although I haven't found a way of creation keystore with key without password. I was able simulate it with keystore with entry only (in that case there was a problem that there are no keys in store) - but as a prove that it can be defined without password it is enough.

**Comment by bstansberry** [comment]
AIUI the issues are as follows:

1) The xsd for the version that is current when this change is made needs to be updated to reflect the fact the password is not required.

2) The xsd version this applies to is not wildfly_config_5_0.xsd, as 5 had shipped and we don't change it. It would have been 6, which is the version for WF Core 4 / WF 12. But this likely isn't going to make WF Core 4. So it will be wildfly_config_7_0.xsd.

It's ok that even though the  5 and 6 xsds say the attribute isn't optional that the parser for those versions (ManagementXml_5) is lenient and doesn't require it. IOW we shouldn't need a ManagementXml_7 that doesn't require the attribute while ManagementXml_5 would continue to.

**Comment by JiriOndrusek** [comment]
@bstansberry 

I've checked definition of password, and it is optional - https://github.com/wildfly/wildfly-core/blob/master/server/src/main/resources/schema/wildfly-config_6_0.xsd#L652
(I've validate it also as xml against xsd)

So I don't think there is need to ass anything.

**Comment by bstansberry** [comment]
retest this please

@jmesnil Assuming no relevant CI issues this is good to go.

**Pull request merged**
