### PR TITLE
[WFCORE-6084] Upgrade bouncycastle from 1.71 to 1.72

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFCORE-6084

### CODE REVIEW

**Comment by yersan** [comment]
Thanks, just FYI @boris-unckel , this BC release is primarily a feature release, so we have to leave it up for the next willdfly-core release, I've just added the 20.x label

**Comment by yersan** [comment]
@jamezp / @jimma Would you mind taking a look and approving it regarding your components? thanks!

**Review by jamezp — APPROVED** [review]
This works for RESTEasy. It's already been upgraded there.

**Comment by jimma** [comment]
@yersan  This upgrade should work for CXF/JBossWS-CXF.

**Comment by yersan** [comment]
Hi @jamezp / @jimma thanks for the quick update, in any case, we need to bump the version again since BC has announced a regression on BC OpenPGP module. They have published only a micro version only for BC OpenPGP.

I've filed this Jira to track it: [WFCORE-6105](https://issues.redhat.com/browse/WFCORE-6105)

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
@boris-unckel, thank you!

**Pull request merged**
