### PR TITLE
[WFCORE-5167] Use individual ApacheDS dependencies to avoid beinging in additional shaded content.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-5167

### CODE REVIEW

**Review by jamezp — COMMENTED** [review]
@darranl What is the reasoning for directly using the versions in the test? While I'm personally not opposed as they are just test dependencies, we generally always use the parent property.

**Comment by darranl** [comment]
@jamezp The reasoning here is the version was already defined here to avoid a conflict with any parent version.  A Jira issue has been raised to clean up ApacheDS dependencies further but this change is not the time to refactoring the use of ApacheDS across the whole testsuite.

**Comment by jamezp** [comment]
@darranl Okay. What we've done before is add a separate property. @jmesnil do you have a preference?

**Comment by darranl** [comment]
This pom already had the versions inlined and not in a separate property, changes like refactoring into properties can come under the next Jira.

**Comment by jmesnil** [comment]
@darranl thanks

**Pull request merged**
