### PR TITLE
[WFCORE-774] Memory leak in JBoss CLI

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.jboss.org/browse/WFCORE-774

### CODE REVIEW

**Comment by aloubyansky** [comment]
There is a method in CommandContext called terminateSession() which is where the clean up should take place when the session is over. Is there anything that could also be added to that method?

**Comment by TomasHofman** [comment]
Well, the only problem there was that every instance of CommandContextImpl added new JaasConfigurationWrapper to global Configuration (so it was creating longer and longer chain). JaasConfigurationWrappers are also holding references back to CommandContextImpl instances, which prevents those from being garbage collected.

So I see two options:
1) only add JaasConfigurationWrapper to global Configuration in the first CommandContext instance being created (shouldn't affect the functionality as I believe),
2) or remove JaasConfigurationWrapper from the Configuration in terminateSession() and restore original configuration.

Neither option is bullet proof, and I thought 1) is simpler.

**Comment by aloubyansky** [comment]
@darranl what's your opinion on this?

**Comment by aloubyansky** [comment]
BTW, Thomas, thanks for your effort here!

**Comment by darranl** [comment]
Looks fine.

**Comment by aloubyansky** [comment]
Ok, given that no matter which option we choose it's still a static config at the end, I'm fine with this too.

**Pull request merged**
