### PR TITLE
[WFCORE-6870][WFCORE-6871][WFCORE-6876] ModuleSpecification cleanups

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFCORE-6870
https://issues.redhat.com/browse/WFCORE-6871
https://issues.redhat.com/browse/WFCORE-6876

Some non-urgent housekeeping.

### CODE REVIEW

**Comment by bstansberry** [comment]
Note that the GH status box only shows 5 CI jobs passing, but https://ci.wildfly.org/project.html?projectId=WildFlyCore_PullRequest&branch_WildFlyCore_PullRequest=pull%2F6053 show the usual larger set.

IIRC I forgot to add a file in the branch before submitting this and quickly fixed that, which may have confused things.

**Comment by bstansberry** [comment]
The status box doesn't show the full set of CI results. They can be seen here:

https://ci.wildfly.org/project.html?projectId=WildFlyCore_PullRequest&branch_WildFlyCore_PullRequest=pull%2F6053

All jobs pass except the one recorded in the status box (which is unrelated).

**Review by yersan — APPROVED** [review]
This looks safe enough to me for going to Final, it also improves the tests, let me know if you disagree

**Comment by bstansberry** [comment]
Thanks @yersan

**Pull request merged**
