### PR TITLE
[WFCORE-1095] Remove bouncycastle dependency

### PR DESCRIPTION
**Pull request by bstansberry**
JIRA: https://issues.jboss.org/browse/WFCORE-1095
EAP JIRA: https://issues.jboss.org/browse/JBEAP-1760

### CODE REVIEW

**Comment by bstansberry** [comment]
3.x for now. If it passes I'll ask productization if they'd like the dependency gone and if so I'll file a JBEAP.

**Comment by ctomc** [comment]
a big +1

**Comment by jamezp** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
