### PR TITLE
[WFCORE-4031] Test coverage for read-config-as-features(nested=false)

### PR DESCRIPTION
**Pull request by LittleJohnII**
https://issues.jboss.org/browse/WFCORE-4031

### CODE REVIEW

**Comment by jmesnil** [comment]
@LittleJohnII WFCORE-3991 has been resolved as we already merge the feature. Could you open additional WFCORE issues for additional testing please?

**Comment by LittleJohnII** [comment]
Sure, I updated the description.

**Comment by LittleJohnII** [comment]
Hold on a second, I'll rename the commit as well...

**Comment by LittleJohnII** [comment]
I force pushed another fix - this is also relevant to the previous test coverage. The domain tests sometime didn't wait for all the servers to start and the tests could fail with `server boot in process`. Thanks to Alexey for letting me know.

Cc. @aloubyansky

**Pull request merged**
