### PR TITLE
[WFCORE-6124] Remove deprecated SocketBinding and OutboundSocketBinding members

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/WFCORE-6124

[WFCORE-6124] Remove deprecated SocketBinding and OutboundSocketBinding members

### CODE REVIEW

**Comment by soul2zimate** [comment]
Error in integration jobs are expected until WFLY-17297 is resolved.

**Comment by soul2zimate** [comment]
This is still active, but blocked by https://github.com/wildfly/wildfly/pull/16307

**Review by yersan — APPROVED** [review]

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @soul2zimate and @yersan

**Pull request merged**
