### PR TITLE
[WFCORE-2805] Use Xalan from JRE rather than our own fork

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.jboss.org/browse/WFCORE-2805

### CODE REVIEW

**Comment by bstansberry** [comment]
@n1hility please approve

**Comment by n1hility** [comment]
this requires further discussion

**Comment by ppalaga** [comment]
@n1hility where is the discussion going to happen? cc @wolfc

**Comment by jmesnil** [comment]
I am closing this PR as there has been no progress on this PR since June 2017. 

Do not hesitate to reopen it if there is progress or an updated conversation about it, thanks

**Pull request closed without merging**
