### PR TITLE
[WFCORE-2957] read-resource without include-runtime shows runtime-only resources

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/WFCORE-2957

### CODE REVIEW

**Comment by petrberan** [comment]
Follow up on https://github.com/wildfly/wildfly-core/pull/4473 which was closed due to inactivity

**Review by yersan — COMMENTED** [review]
Hello @petrberan test failures are related to this change.

**Comment by petrberan** [comment]
Thank you @yersan , had a false positive tests on my device. Should be fixed in this commit

**Comment by petrberan** [comment]
Hi @yersan just noticed this PR is still open with test failures. However, I'm not getting any failures on my device, could you retest this one please?

**Comment by yersan** [comment]
Hi, @petrberan I've kicked it off again, you can do it by opening the "Details" link and clicking on the "Run" button at the upper corner.

In any case, this PR is still under discussion see https://github.com/wildfly/wildfly-core/pull/4473#issuecomment-804503317

**Comment by petrberan** [comment]
Sorry about that @yersan , got few problems in my branches. Anyway, I pushed the proposed changes with the latest commit. Is there anything I can do to make this PR merged?

**Review by yersan — CHANGES_REQUESTED** [review]
@petrberan I reviewed again this and found a minor detail to address on one of the test cases. Besides that minor detail, it looks good to me and we can merge it after the approvals.


@bstansberry Would you mind taking another look and approve on your side? there were some discussions in the past about it, but the summary is the PR is going to remove runtime resources from reading operations. I've been checking HAL in case of finding any obvious error, but it looks fine.

Since we are making major changes, I think we can proceed with these, after all, not to show runtime values when include-runtime is false is the correct behavior.

**Comment by petrberan** [comment]
Hi @yersan @bstansberry can I ask for review please?

**Comment by petrberan** [comment]
Can I ask for review please @yersan @bstansberry ? The failed test is not related to the PR, got all greens on my part

**Review by yersan — APPROVED** [review]
@bstansberry I gave my approval since my last review since my last change request was addressed, but since these changes affect the standard read operations returning something different, my main concern here is HA or any other client.

We can argue that runtime resources should not be shown if you are not enabling them, but since merging this can open the door to bugs on those clients (or corrections needed on those clients) I'm still running into doubts, so I would like to hear your opinion here to also ensure I'm not missing something.

**Comment by yersan** [comment]
In any case, I would defer this to WF29 so we can get some bake

**Review by bstansberry — APPROVED** [review]
@yersan @petrberan LGTM.

**Comment by yersan** [comment]
Thanks, @petrberan

**Pull request merged**
