### PR TITLE
[WFCORE-6736] Remove the usage of deprecated OperationDescriptor interface

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFCORE-6736

### CODE REVIEW

**Comment by yersan** [comment]
@lvydra This has compilation failures, could you rebase and fix them? thanks!

**Comment by lvydra** [comment]
Thanks @yersan, updated.

**Comment by bstansberry** [comment]
/retest

^^^ is partly to keep this from being closed as stale, since AFAICT it's fine.

**Comment by lvydra** [comment]
This has been meanwhile done by https://github.com/wildfly/wildfly-core/pull/6090

**Pull request closed without merging**
