### PR TITLE
[WFCORE-4925] Correct GAV versions in ModelTestControllerVersion

### PR DESCRIPTION
**Pull request by rachmatowicz**
This PR corrects the GAV versions for Wildfly Core in the helper class ModelTestControllerVersion.
For details, see: https://issues.redhat.com/browse/WFCORE-4925

### CODE REVIEW

**Comment by jmesnil** [comment]
@rachmatowicz Is it normal that your PR includes Emmanuel's commit?

**Comment by jmesnil** [comment]
Corresponding PR for wildfly-core 11.0.x branch is #4136

**Comment by rachmatowicz** [comment]
Fixed, sorry!

**Comment by rachmatowicz** [comment]
Not fixed, give me minute.

**Pull request closed without merging**
