### PR TITLE
WFCORE-2556 removing case-sensitive attr from credential store

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.jboss.org/browse/JBEAP-8871
https://issues.jboss.org/browse/WFCORE-2556

This PR is dependent on:
* https://github.com/wildfly/wildfly-core/pull/2499 / https://issues.jboss.org/browse/JBEAP-10255 --  removes case-sensitivity from realms
* https://github.com/wildfly/wildfly/pull/10187 - fixes integration tests in Wildfly
* https://github.com/jbossas/jboss-eap7/pull/1993 - fixes integration tests in EAP 7.1

After the three above are merged, tests should start passing on this PR.

### CODE REVIEW

**Comment by darranl** [comment]
@TomasHofman This PR has conflicts, can you please rebase and then ping me and I will merge into the incubator.

**Comment by TomasHofman** [comment]
retest this please

**Comment by TomasHofman** [comment]
retest this please

**Comment by darranl** [comment]
Merged into ladybird to be pulled back in coordinated PR.

**Comment by TomasHofman** [comment]
Can I close this one, or leave open?

**Comment by darranl** [comment]
I think Brian prefers it is closed now.  If not GitHub will automatically close it when merged so we are sure it is fully merged.

**Comment by TomasHofman** [comment]
Thanks, then I close it.

**Pull request closed without merging**
