### PR TITLE
[WFCORE-6245] Eliminating deprecated ibm.jdk module usages

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-6245

### CODE REVIEW

**Comment by ropalka** [comment]
This PR depends on https://github.com/wildfly/wildfly/pull/16572 to be merged first

**Comment by bstansberry** [comment]
@ropalka This needs some discussion on the wildfly-dev list. I believe the ServerRootResourceDefinition change means this module will no longer be provisioned in a slimmed server. And we have no simple way of ensuring it is provisioned, e.g. a layer. And I don't want a layer. :)

Then there's the aspect of SE packages no longer being available.

I'd like this on the discussed on the list so it gets greater visibility.

**Comment by ropalka** [comment]
I'm working in both areas @bstansberry . I'm preparing the information email for discussion on wildfly-dev ML and collecting information to add to relevant JIRAs.

**Comment by yersan** [comment]
@ropalka FYI

 I'm moving this to "Ready For Review", there will be future work removing completely this module from WildFly, although it can be removed now, I'm assuming we want it fully removed on the next release.

Since the WildFly counterpart PR was already merged, we could get this one merged as it is for WildFly Core 20.0.0. Final

**Comment by ropalka** [comment]
Yes, we will remove ibm.jdk module in next release @yersan .

**Review by yersan — APPROVED** [review]

**Pull request merged**
