### PR TITLE
[WFCORE-6627] Make use of the SetRequestInformationMechanismFactory to set the request information during HTTP authentication

### PR DESCRIPTION
**Pull request by Skyllarr**
https://issues.redhat.com/browse/WFCORE-6627

**Requires**: ELY-2583 :  https://github.com/wildfly-security/wildfly-elytron/pull/1952 
so **requires** Elytron 2.2.3.Final component upgrade: https://github.com/wildfly/wildfly-core/pull/5835

### CODE REVIEW

**Review by darranl — APPROVED** [review]

**Comment by bstansberry** [comment]
@Skyllarr There's a compile problem:

```
[20:22:18][Step 3/6] [ERROR] /opt/buildAgent/work/e8e0dd9c7c4ba60/core/elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java:[60,38] cannot find symbol
[20:22:18][Step 3/6] [ERROR]   symbol:   class SetRequestInformationCallbackMechanismFactory
[20:22:18][Step 3/6] [ERROR]   location: package org.wildfly.security.http.util
```

**Comment by Skyllarr** [comment]
> @Skyllarr There's a compile problem:
> 
> ```
> [20:22:18][Step 3/6] [ERROR] /opt/buildAgent/work/e8e0dd9c7c4ba60/core/elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java:[60,38] cannot find symbol
> [20:22:18][Step 3/6] [ERROR]   symbol:   class SetRequestInformationCallbackMechanismFactory
> [20:22:18][Step 3/6] [ERROR]   location: package org.wildfly.security.http.util
> ```

@bstansberry this requires wildfly-elytron change,  sorry I did not add this to the PR description before, fixed now

**Comment by bstansberry** [comment]
No problem, @Skyllarr. Note there is a 'core-upgrade-required' label you should be able to apply to PRs like this. That's helpful as its visible when looking at the PR queue.

**Comment by yersan** [comment]
Thanks @Skyllarr and all the ones involved!

**Pull request merged**
