### PR TITLE
WFCORE-1732 permissions of the parent should be applied to the subdep…

### PR DESCRIPTION
**Pull request by istudens**
…loyment too

Supersedes https://github.com/wildfly/wildfly/pull/8842.

### CODE REVIEW

**Comment by istudens** [comment]
@stuartwdouglas @dmlloyd could you review this please? thanks

**Comment by istudens** [comment]
This fix seems to be too general. I was afraid it would cause regressions. But at least VirtualFilePermissions might be cloned from the parent to subdeployments this way, wdyt?

**Comment by istudens** [comment]
I mean something like 
https://github.com/istudens/wildfly-core/commit/d925cf45ce785eb1382bd0df833ce3b29a78c101#diff-3f1bdca0ad46a27814c89dfb03e146b1R257

**Comment by dmlloyd** [comment]
See comments on downstream PR - do not merge yet.

**Comment by dmlloyd** [comment]
I talked this over with Petr.  It's a +1 from me.

**Comment by dmlloyd** [comment]
Assuming the tests pass. :)

**Comment by istudens** [comment]
David, do you have any idea how to fix this in a different way? My proposed fix fixes this issue but introduces regressions because it is most likely not a good idea to clone perms from ear to war automatically. I am not sure if at least VirtualFilePermission might be cloned this way as I asked above, see the commit linked above. What do you think about it?
Otherwise any web deployment of an ear would need an explicit permissions to get to the lib packaged within the ear.

**Comment by dmlloyd** [comment]
Rather than cloning permissions, we should be just setting the required permissions on each module separately.  It should be known what additional VFSPermission instances are required by just browsing the structure of the deployment.

**Comment by istudens** [comment]
This has been refactored by @dmlloyd comments and it is finally passing the tests on TeamCity.

**Pull request merged**
