### PR TITLE
WFCORE-1231 Remove OSGI bundle related stuff from patching tests

### PR DESCRIPTION
**Pull request by jmartisk**
OSGi subsystem is removed, so this PR removes OSGi-related stuff from the patching test suite. Interesting is that the tests still pass, apparently the Patching subsystem still can handle this stuff.

https://issues.jboss.org/browse/WFCORE-1231

### CODE REVIEW

**Comment by jmartisk** [comment]
retest this please

**Comment by bstansberry** [comment]
@aloubyansky please approve

**Comment by aloubyansky** [comment]
Looks good, thanks!

**Comment by bstansberry** [comment]
@jmartisk can you rebase this please? Thanks.

**Comment by jmartisk** [comment]
Done.

**Comment by jmartisk** [comment]
retest this please

**Pull request merged**
