### PR TITLE
WFCORE-4611 Complete AttributeDefinition.getImmutableFlags() -> getFlags() transition

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFCORE-4611

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks for cleaning up after me, @pferraro !

**Comment by yersan** [comment]
Hi @pferraro / @bstansberry 

The changes on this PR affect [TransactionSubsystemRootResourceDefinition.java ](https://github.com/wildfly/wildfly/blob/9e2545ff734c9ded53d1e5d16847ac524a1674ee/transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemRootResourceDefinition.java#L391)

My suggestion is to revert these changes now and create them again after the revert. We can handle both when we are releasing 19.0.0.Beta17 by incorporating the required changes in wildfly full with the wildfly-core upgrade. Please, feel free to suggest if you think we have to use a different workaround.

**Comment by yersan** [comment]
@pferraro / @bstansberry Ups, sorry for all the noise, replacing .getImmutableFlags() by getFlags() in full should be enough

**Comment by yersan** [comment]
https://github.com/wildfly/wildfly/pull/15928

**Pull request merged**
