### PR TITLE
[WFCORE-3398] Elytron, wrong capabilities registered

### PR DESCRIPTION
**Pull request by ivassile**
wildfly-elytron-integration: https://issues.jboss.org/browse/WFCORE-3398
JBEAP: https://issues.jboss.org/browse/JBEAP-13688

### CODE REVIEW

**Comment by ivassile** [comment]
@darranl I'm sorry but could you please explain your request, because I do not fully understand it? I've added "Affects Version/s: 4.0.0.Alpha3" to WFCORE-3398, but I don't know what else to change.

**Comment by darranl** [comment]
The commit message and the title of this PR both reference a JBEAP issue - those references should be changed to the WFCORE issue.

**Comment by ivassile** [comment]
@darranl Thanks for the clarification. Up until now, I've always referenced the JBEAP issue in the PRs, but probably something changed so I'll start referring to the upstream issue in the PRs.

**Comment by ivassile** [comment]
@darranl Thanks for the clarification. I'll correct it.

**Pull request merged**
