### PR TITLE
WFCORE-5374 Remove the wildfly-elytron dependency from the main pom.xml file

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFCORE-5374

### CODE REVIEW

**Comment by jmesnil** [comment]
@parsharma Without that dependency, the build of WildFly Full fails with:

```
Dependency convergence error for org.wildfly.security:wildfly-elytron:1.1.5.Final paths to dependency are:
  +-org.wildfly:wildfly-clustering-ejb-spi:25.0.0.Beta1-SNAPSHOT
    +-org.jboss:jboss-ejb-client:4.0.42.Final
      +-org.wildfly.security:wildfly-elytron:1.1.5.Final
  and
  +-org.wildfly:wildfly-clustering-ejb-spi:25.0.0.Beta1-SNAPSHOT
    +-org.jboss:jboss-ejb-client:4.0.42.Final
      +-org.wildfly:wildfly-naming-client:1.0.14.Final
        +-org.wildfly.security:wildfly-elytron:1.1.0.Final
```

It seems the `org.wildfly:wildfly-clustering-ejb-spi` module will have to provide a dependency for it to reconcile `jboss-ejb-client` and `wildfly-naming-client`dependencies 

(@fjuma fiy)

**Comment by parsharma** [comment]
@jmesnil I am working on this part. Thanks

**Comment by jmesnil** [comment]
@parsharma are you planning to resolve this before we release WildFly 25 Final?

**Comment by parsharma** [comment]
@jmesnil I am not sure because there are some issues that need to be merge in order to resolve this issue. I am working on that issues. Will update you soon. 

Thanks

**Pull request closed without merging**
