### PR TITLE
[WFCORE-4617] jboss-cli.sh does not error on invalid options

### PR DESCRIPTION
**Pull request by spyrkob**
JIRA: https://issues.jboss.org/browse/WFCORE-4617

@jfdenise could you review please?

### CODE REVIEW

**Comment by darranl** [comment]
Do keep in mind with a change like this - all scripts that already exist that pass in an unrecognised option will now fail even if that option could be ignored.

**Comment by spyrkob** [comment]
@darranl as far as I can tell, currently if an option is not recognised, it will be interpreted as a command and the script will fail when trying to execute this command. The difference with the change should be earlier failure (before connection attempt) and new error message.

**Comment by darranl** [comment]
@spyrkob I understand the purpose of this change, but that doesn't eliminate the possibility that previously "working" calls to this script may now start failing - these calls could be coming from existing scripts such as cron jobs etc...

**Comment by jfdenise** [comment]
@darranl , we are replacing an error message with another one. We don't have "working" script that would suddenly start to fail.

**Comment by darranl** [comment]
@jfdenise Ok if we are happy this is replacing one error state with another error state - sounds good and we shouldn't have issues with user scripts.

**Comment by bstansberry** [comment]
@jfdenise If you are ok with this please approve via github approval.

**Pull request merged**
