### PR TITLE
WFCORE-6866 Create ServiceDescriptor for management executor

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFCORE-6866

If someone has a better idea of where to locate this service descriptor, let me know.

### CODE REVIEW

**Comment by yersan** [comment]
> If someone has a better idea of where to locate this service descriptor, let me know.

I have no better suggestions than the Capabilities class. I understand the natural choice would be to be declared on the service value class, but for this one, `Executor`, is impossible.

**Review by yersan — APPROVED** [review]
In any case, I'll wait some days more in case there is any other suggestion

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
I don't have any better locations either.

**Comment by bstansberry** [comment]
Thanks @pferraro and @yersan

**Pull request merged**
