### PR TITLE
WFCORE-384 - Server does wrongly reference a list of socket binding groups

### PR DESCRIPTION
**Pull request by luck3y**
This currently correctly limits the s-b-g to 1 per server / host. Rather than make extensive changes to the sbg constructors at the moment to use maxOccurs, this just changes the resource descriptions to match what is currently allowed.

### CODE REVIEW

**Comment by luck3y** [comment]
There were a couple of other issues that came up during testing this, which I'll open seperate tickets for:

(A) - You can perform /host=master/server=server-one/socket-binding-group=standard-sockets:remove and the operation completes. However, if you try to add, you get:

/host=master/server=server-one/socket-binding-group=standard-sockets:add

{
"outcome" => "failed",
"result" => undefined,
"failure-description" => "WFLYCTL0249: Operation 'add' targeted at resource '[(\"socket-binding-group\" => \"standard-sockets\")]' was directly invoked by a user. User operations are not permitted to directly update the persistent configuration of a server in a managed domain.",
"response-headers" => {"process-state" => "reload-required"},
"rolled-back" => true
}

Should the add be allowed, or the remove be prevented? On reload after the remove, the previous value is restored, so it isn't being persisted.

B) /host=master/socket-binding-group=test1:add(default-interface=public)
This completes as expected, however, removing it and re-adding generates the following exception:

[Host Controller] 19:27:34,481 ERROR org.jboss.as.controller.management-operation WFLYCTL0013: Operation ("add") failed - address: ([
Host Controller,
Host Controller
[Host Controller] ]): org.jboss.msc.service.DuplicateServiceException: Service jboss.socket-binding-manager is already registered
[Host Controller] at org.jboss.msc.service.ServiceRegistrationImpl.setInstance(ServiceRegistrationImpl.java:158)
[Host Controller] at org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:235)
[Host Controller] at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:768)
[Host Controller] at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
[Host Controller] at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
[Host Controller] at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
[Host Controller] at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
[Host Controller] at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317)
[Host Controller] at org.jboss.as.controller.OperationContextImpl$ContextServiceBuilder.install(OperationContextImpl.java:2114)
[Host Controller] at org.jboss.as.server.services.net.BindingGroupAddHandler.performRuntime(BindingGroupAddHandler.java:112)
[Host Controller] at org.jboss.as.controller.AbstractAddStepHandler.performRuntime(AbstractAddStepHandler.java:337)
[Host Controller] at org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:151)
[Host Controller] at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
[Host Controller] at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
[Host Controller] at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
[Host Controller] at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
[Host Controller] at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:400)
[Host Controller] at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:222)
[Host Controller] at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.doExecute(ModelControllerClientOperationHandler.java:208)
[Host Controller] at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.access$300(ModelControllerClientOperationHandler.java:130)
[Host Controller] at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:152)
[Host Controller] at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:148)
[Host Controller] at java.security.AccessController.doPrivileged(Native Method)
[Host Controller] at javax.security.auth.Subject.doAs(Subject.java:422)
[Host Controller] at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:149)
[Host Controller] at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1.execute(ModelControllerClientOperationHandler.java:148)
[Host Controller] at org.jboss.as.protocol.mgmt.AbstractMessageHandler$ManagementRequestContextImpl$1.doExecute(AbstractMessageHandler.java:363)
[Host Controller] at org.jboss.as.protocol.mgmt.AbstractMessageHandler$AsyncTaskRunner.run(AbstractMessageHandler.java:472)
[Host Controller] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Host Controller] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Host Controller] at java.lang.Thread.run(Thread.java:745)
[Host Controller] at org.jboss.threads.JBossThread.run(JBossThread.java:320)
[Host Controller]

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by bstansberry** [comment]
@luck3y re: your question (A): 

Any config write op from a user that directly addresses a domain server resource should fail. User's can't directly touch a domain server's config; only their HC can, as part of the HC's processing a user request targeting a domain-wide or host-specific resource. 

What you've described here is another variant of the https://issues.jboss.org/browse/WFCORE-771 bug. It's an absolutely critical bug if the ops are actually changing the server state in some way.

**Comment by bstansberry** [comment]
Re your (B):

Does the remove include the normal "reload-required" stuff in the response? If not that's a bug. If so, it's the usual WFCORE-1106 scenario.

**Comment by luck3y** [comment]
@bstansberry Yes, it does show reload-required, this whole sequence is:

[domain@localhost:9990 /] /host=master/socket-binding-group=test1:add(default-interface=public)
{
    "outcome" => "failed",
    "result" => {},
    "failure-description" => {"host-failure-descriptions" => {"master" => "WFLYCTL0212: Duplicate resource [
    (\"host\" => \"master\"),
    (\"socket-binding-group\" => \"test1\")
]"}},
    "rolled-back" => true
}
[domain@localhost:9990 /] /host=master/socket-binding-group=test1:remove
{
    "outcome" => "success",
    "result" => undefined,
    "server-groups" => undefined,
    "response-headers" => {"process-state" => "reload-required"}
}
[domain@localhost:9990 /] /host=master/socket-binding-group=test1:add(default-interface=public)
{
    "outcome" => "failed",
    "result" => {},
    "failure-description" => {"host-failure-descriptions" => {"master" => "WFLYCTL0158: Operation handler failed: org.jboss.msc.service.DuplicateServiceException: Service jboss.socket-binding-manager is already registered"}},
    "rolled-back" => true,
    "response-headers" => {"process-state" => "reload-required"}
}

**Comment by luck3y** [comment]
Ah, I just read 1106, got it ;)

**Comment by bstansberry** [comment]
@luck3y this doesn't look quite right:

```
[domain@localhost:9990 /] /host=master/socket-binding-group=test1:remove
{
"outcome" => "success",
"result" => undefined,
"server-groups" => undefined,
"response-headers" => {"process-state" => "reload-required"}
}
```

Under the "response-headers" node I also expect to see "operation-requires-reload" => true. 

So something is missing in the reporting on the op. But still, the preceding add op didn't report the host being in reload-required, while the remove op did, so my deduction is the remove op is what put the host in r-r! ;) And so this is the 1106 situation.

**Comment by bstansberry** [comment]
The issue I mentioned with "operation-requires-reload" => true not being present seems to be a problem with DomainFinalResultHandler. Any response-header data reported by the individual hosts is not getting aggregated into the overall response. I'm not sure exactly how it should be aggregated.

**Pull request merged**
