### PR TITLE
[WFCORE-6823] Don't register the Jakarta AuthConfigFactory in the host controller.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-6823

### CODE REVIEW

**Comment by yersan** [comment]
@darranl just asking, shouldn't this change be driven by the RFE that would move Jakarta Authentication to its own subsystem?

**Comment by bstansberry** [comment]
@darranl The JIRA description could use an update then, as the 'bug' aspect is unclear.

**Comment by darranl** [comment]
@yersan / @bstansberry I have updated the description in the issue to say it is to fix the bug,

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
Thanks @darranl @bstansberry

**Pull request merged**
