### PR TITLE
[WFCORE-6609] remove obsolete JMockit

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/WFCORE-6609 remove obsolete JMockit

### CODE REVIEW

**Review by fjuma — COMMENTED** [review]
@soul2zimate Thanks for working on this! It's great that this is no longer needed by the tests. This looks good, the WFCORE issue in the title and commit message just needs to be updated (it's currently "WFCORE-").

**Comment by soul2zimate** [comment]
yes,  I created a new issue and linked in the title and commit message.

**Review by yersan — APPROVED** [review]
Great @soul2zimate , looks good, the test failure can be ignored since it is not related. Waiting for approval from Elytron team.

**Review by fjuma — APPROVED** [review]
Thanks @soul2zimate!

**Comment by yersan** [comment]
Thanks @fjuma @soul2zimate

**Pull request merged**
