### PR TITLE
[18.x] WFCORE Backports

### PR DESCRIPTION
**Pull request by boris-unckel**
This aggregate PR contains the following backports

|Component|Jira|Commit|Upstream PR|
|---|---|---|---|
|Snakeyaml 1.33|[WFCORE-6071](https://issues.redhat.com/browse/WFCORE-6071)|https://github.com/wildfly/wildfly-core/commit/baa8a5cd204e4e0aafda310f37f8b075a24b3922|https://github.com/wildfly/wildfly-core/pull/5227|
|WildFly OpenSSL 2.2.5.Final|[WFCORE-5981](https://issues.redhat.com/browse/WFCORE-5981)|https://github.com/wildfly/wildfly-core/commit/5334cd051f1ec7496306a0ca6b39ae02a94a7080|https://github.com/wildfly/wildfly-core/pull/5164|
|OpenSSL Natives 2.2.2.Final|[WFCORE-5941](https://issues.redhat.com/browse/WFCORE-5941)[WFCORE-5976](https://issues.redhat.com/browse/WFCORE-5976)|https://github.com/wildfly/wildfly-core/commit/3bc7ecb191c8414339cd6d1849085a5436fa5f55|https://github.com/wildfly/wildfly-core/pull/5131 https://github.com/wildfly/wildfly-core/pull/5162|
|JBoss Remoting 5.0.26.Final|[WFCORE-6076](https://issues.redhat.com/browse/WFCORE-6076)|https://github.com/wildfly/wildfly-core/commit/014cb0c2b4bea84e65479e9c693f808d02443190|https://github.com/wildfly/wildfly-core/pull/5234|
|JBoss Marshalling to 2.0.13.Final|[WFCORE-6162](https://issues.redhat.com/browse/WFCORE-6162)|https://github.com/wildfly/wildfly-core/commit/4c18e7e0295add657f11a498ed5cf1cc566af254|https://github.com/wildfly/wildfly-core/pull/5228|
|JBoss Invocation 1.7.1.Final|[WFCORE-6163](https://issues.redhat.com/browse/WFCORE-6163)|https://github.com/wildfly/wildfly-core/commit/e79ca0a4ff5382f2d031679838634a60e0150785|https://github.com/wildfly/wildfly-core/pull/5264|
|log4j2 2.19.0|[WFCORE-6034](https://issues.redhat.com/browse/WFCORE-6034)|https://github.com/wildfly/wildfly-core/commit/1f98fc632b48cf48b551935bb463fab0a2ac2df1|https://github.com/wildfly/wildfly-core/pull/5187|
|commons-lang3 3.12.0|[WFCORE-5971](https://issues.redhat.com/browse/WFCORE-5971)|https://github.com/wildfly/wildfly-core/commit/80cf9ba3a9aa67e51b488e45c6a294323ea76ad5|https://github.com/wildfly/wildfly-core/pull/5157|
|Google Guava 31.1-jre|[WFCORE-6083](https://issues.redhat.com/browse/WFCORE-6083)|https://github.com/wildfly/wildfly-core/commit/300eaad8ca1d3a00e238f8d50e234dddf82c2a87|https://github.com/wildfly/wildfly-core/pull/5237|
|JGit 5.13.1.202206130422-r Apache SSHD 2.9.2|[WFCORE-6165](https://issues.redhat.com/browse/WFCORE-6165)|https://github.com/wildfly/wildfly-core/commit/52f6ee5e3737a899cab9be79280d71bfd68ee66e|https://github.com/wildfly/wildfly-core/pull/5132 https://github.com/wildfly/wildfly-core/pull/5291|
|Undertow 2.2.22.Final|[WFCORE-6164](https://issues.redhat.com/browse/WFCORE-6164)|https://github.com/wildfly/wildfly-core/commit/26f319c3a1173880079f21407c328c0bf6634682|https://github.com/wildfly/wildfly-core/pull/5313 https://github.com/wildfly/wildfly/pull/16363|
|Byteman 4.0.20|[WFCORE-6099](https://issues.redhat.com/browse/WFCORE-6099)|https://github.com/wildfly/wildfly-core/commit/f7ff2f82f8543ff97986df5e2501d7ce56b14fa7|https://github.com/wildfly/wildfly-core/pull/5253|

### CODE REVIEW

**Comment by boris-unckel** [comment]
@yersan thanks for your feedback. I understand you don't want to publish the version. I still think it would help people who fork to have a documented and reviewed branch to start with. For me it's to give back something in terms of open source, we are going to use these changes in our fork anyway.

**Comment by yersan** [comment]
Hi @boris-unckel , got it, and makes sense what you described, however, since PR Jobs were failing, and the PR was not ready for merging without a proper review, I closed it directly and avoid polishing the queue with things that are not expected to be reviewed and approved for merging; notice if this PR is up, we cannot guarantee we are going to spend time reviewing, approving and merging since 18.x is not currently under development.

**Comment by boris-unckel** [comment]
@yersan Would it be possible to get this into [WF26.1.3](https://groups.google.com/g/wildfly/c/ejZjQXm1xeg/m/OG7eI0GhBgAJ) ?

**Comment by yersan** [comment]
Hello, the WildFly team is doing this extraordinary release due to a severity vulnerability found in Apache CXF (9.8 of 10 at CVSS v3 Base Score), there are no plans to release WildFly Core 18.x in WF26.1.3.

Refer to this WildFly Discussion [email thread](https://groups.google.com/g/wildfly/c/ejZjQXm1xeg/m/OG7eI0GhBgAJ) about his release and feel free to share any feedback there.

**Pull request closed without merging**
