### PR TITLE
[WFCORE-6612][WFCORE-6613][WFCORE-6614][WFCORE-6615] Allow use of WildFly Channels when running the testsuite

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFCORE-6612
https://issues.redhat.com/browse/WFCORE-6613
https://issues.redhat.com/browse/WFCORE-6614
https://issues.redhat.com/browse/WFCORE-6615

Draft because I need to update the WFCORE-6612 commit to set 'overwriteProvisionedServer' in all the wildfly-maven-plugin 'provision' executions.

### CODE REVIEW

**Comment by bstansberry** [comment]
Custom test runs to exercise the two new profiles, using -Dts.layers:

1) With -Dinternal.wildfly.channels 

https://ci.wildfly.org/viewLog.html?buildId=404095

2) With -Dexternal.wildfly.channels=org.wildfly.core:wildfly-core-manifest:23.0.0.Beta2-SNAPSHOT

https://ci.wildfly.org/viewLog.html?buildId=404097

Both pass.

**Comment by bstansberry** [comment]
This is now ready for review.

I tweaked this, so I've launched two more custom test runs to exercise the two new profiles, using -Dts.layers:

1) With -Dinternal.wildfly.channels 

https://ci.wildfly.org/viewLog.html?buildId=404325

2) With -Dexternal.wildfly.channels=org.wildfly.core:wildfly-core-manifest:23.0.0.Beta2-SNAPSHOT

https://ci.wildfly.org/viewLog.html?buildId=404326

**Review by yersan — COMMENTED** [review]
Hi @bstansberry why did you leave out from the change the testsuite/layers? I understand we still want to continue using the dist/build as a method to compare the two types of provisioning, but I don't get why you do not proceed with testsuite/layers in a similar way as the other modules under testsuite

**Comment by bstansberry** [comment]
Thanks @yersan

**Pull request merged**
