### PR TITLE
[WFCORE-3641] Upgrading JBoss MSC to 1.3.1.Final.

### PR DESCRIPTION
**Pull request by ropalka**
This upgrade brings in [MSC-204] fixes for container shutdown
freeze regressions. See [WFCORE-3590] for more information.

### CODE REVIEW

**Comment by ropalka** [comment]
This brings in MSC regression fix @bstansberry

**Comment by bstansberry** [comment]
@dmlloyd Please approve for inclusion in WF Core 4, WF 12.

**Comment by bstansberry** [comment]
retest this please

**Comment by ropalka** [comment]
Hmm, the problem persists @bstansberry @dmlloyd

**Comment by ropalka** [comment]
I identified the real cause of WFCORE-3590 @bstansberry & @dmlloyd - I updated this PR accordingly.

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
