### PR TITLE
WFCORE-1375 upgrade jboss-parent to 20 making build work on JDK9

### PR DESCRIPTION
**Pull request by ctomc**
- to make build work on recent JDK9 builds
- upgrade byteman to 3.0.3

### CODE REVIEW

**Comment by ctomc** [comment]
interesting it looks like maven 3.2.5 process this different than maven 3.3.x

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
retest this please

**Comment by bstansberry** [comment]
@aloubyansky are these patching testsuite changes ok?

**Comment by aloubyansky** [comment]
I was just not sure what was the reason for reuseForks=false. After talking to Tomaz he confirmed they tested it extensively, so I am ok with this. Thanks!

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
