### PR TITLE
[WFCORE-5334]: Deleting Configuration Data when Git connection is fai…

### PR DESCRIPTION
**Pull request by ehsavoie**
…led.

* Moving files into an "attic" folder.
* Restoring files in case of git failure.
* Deleting attic files afterwards.

Jira: https://issues.redhat.com/browse/WFCORE-5334

### CODE REVIEW

**Comment by jmesnil** [comment]
I'm not sure to understand the issue.

If the git pull fails, what has been modified in the local repository?

**Comment by ehsavoie** [comment]
To be able to pull you need to target an empty directory. So at the first pull WildFly deletes some directories. If the pull in question fails then those directories/ files are 'lost' and this blocks the server from starting.

**Comment by jmesnil** [comment]
@ehsavoie so do you need to copy the existing directory or move it?

**Comment by ehsavoie** [comment]
I move the files to a temp place (the 'attic') to be able to restore if the git operation fails

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
@ehsavoie Windows failures are related to the patch

**Comment by jmesnil** [comment]
@ehsavoie I've added a `fixme` label to hold this PR until the Windows failures are fixed

**Pull request closed without merging**
