### PR TITLE
[WFCORE-3402] Upgrade MSC to 1.2.8.Final

### PR DESCRIPTION
**Pull request by ropalka**

### CODE REVIEW

**Comment by ropalka** [comment]
Please, do not merge yet.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by ropalka** [comment]
I reviewed failing test - there was some problem with remoting there.

**Comment by ropalka** [comment]
retest this please

**Comment by ropalka** [comment]
Seems windows job started swapping so it didn't complete in specified amount of time (thus was forcibly terminated)

**Pull request merged**
