### PR TITLE
[WFCORE-6799] Upgrade SLF4J from 2.0.12 to 2.0.13

### PR DESCRIPTION
**Pull request by yersan**
Jira issue: https://issues.redhat.com/browse/WFCORE-6799

### CODE REVIEW

**Review by jamezp — APPROVED** [review]
This is only used for testing. I can't open up the failed CI job for some reason, but I don't think it would be related.

**Comment by yersan** [comment]
It is unrelated has failed with a similar stack trace for other PRs. In addition, since it is a test only dependency, it is not being driven to WildFly via WildFly Core, so any failure on integration tests should be unrelated.

CC @rhusar in relation to https://issues.redhat.com/browse/WFLY-14064, it looks like the test case is still failing

**Comment by rhusar** [comment]
> It is unrelated has failed with a similar stack trace for other PRs. In addition, since it is a test only dependency, it is not being driven to WildFly via WildFly Core, so any failure on integration tests should be unrelated.
> 
> CC @rhusar in relation to https://issues.redhat.com/browse/WFLY-14064, it looks like the test case is still failing

Thanks, I ll have a look (and yes, definitely unrelated)

**Comment by yersan** [comment]
Thanks @jamezp @rhusar

**Pull request merged**
