### PR TITLE
[WFCORE-7054] Upgrade BouncyCastle from 1.78.1 to 1.79

### PR DESCRIPTION
**Pull request by yersan**
Jira Issue: https://issues.redhat.com/browse/WFCORE-7054

### CODE REVIEW

**Comment by yersan** [comment]
Test failure in full integration Job is unrelated

**Comment by yersan** [comment]
@jamezp @jimma Could you approve from your side? thanks!

**Comment by jimma** [comment]
@yersan  I'd like to wait for wss4j merge this version first:  https://github.com/apache/ws-wss4j/pull/407. Thanks.

**Review by jamezp — APPROVED** [review]
This is fine from a RESTEasy perspective.

**Comment by yersan** [comment]
Hi @jimma https://github.com/apache/ws-wss4j/pull/407 was merged, let us know when you are fine proceeding with this, thanks!

**Comment by yersan** [comment]
Thanks @jimma  @jamezp

**Pull request merged**
