### PR TITLE
[WFCORE-4704] WS integration with WildFly Elytron - AuthenticationClient for Authentication / SSL

### PR DESCRIPTION
**Pull request by Skyllarr**
Will not compile. Requires [ELY-1853](https://issues.jboss.org/browse/ELY-1853)

### CODE REVIEW

**Comment by bstansberry** [comment]
This is ok to test.

**Comment by jmesnil** [comment]
@Skyllarr PR fails with a compilation failure: 

```
Compilation failure
/store/work/tc-work/aa7b981af3f49e3c/elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java:[377,99] cannot find symbol
  symbol:   method useWebServices(java.util.Map<java.lang.String,java.lang.Object>)
  location: variable c of type org.wildfly.security.auth.client.AuthenticationConfiguration
```

Is the code up to date with the latest Elytron 1.11.0.CR1 release?

**Comment by Skyllarr** [comment]
Hello @jmesnil . No the code is not up to date with latest Elytron release. This PR requires ELY-1853 to be merged first.

**Comment by jmesnil** [comment]
@Skyllarr thanks

**Pull request merged**
