### PR TITLE
[WFCORE-4413] Fixing javax.api and javax.sql.api modules BC issues

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFCORE-4413

### CODE REVIEW

**Comment by ropalka** [comment]
I analyzed modules before and after the changes and I identified just two backward compatibility issues.
Who's volunteering to review this PR @bstansberry @jmesnil @darranl @kabir @jamezp ?

**Comment by darranl** [comment]
Looks like the failures and hang are the same as in https://github.com/wildfly/wildfly-core/pull/3725 so maybe not related to that component upgrade after all.

**Comment by darranl** [comment]
Aren't some of these modules supposed to be automatically generated in jboss-modules now or are these two not a part of that?

**Comment by ropalka** [comment]
There was implemented an ability to define dependencies on **Jigsaw** aka **JPMS (Java Platform Module System) modules**  in module.xml (JBoss module descriptors). If there's a module referenced in module.xml that has no module.xml definition it is considered to be JPMS module and JBoss Modules implementation delegates to PlatformModuleLoader for not-found modules.
Also note that JPMS system is emulated on top of JDK8. 

To answer your question neither **javax.api** nor **javax.sql.api** represent a JPMS module.
That is also the reason why these modules have been deprecated.
It is necessary to include missing module dependencies there explicitly.

**Pull request merged**
