### PR TITLE
Fix for WFCORE-4112, upgrade CLI to aesh 1.8

### PR DESCRIPTION
**Pull request by jfdenise**
Upgrade to aesh 1.8.

### CODE REVIEW

**Comment by jamezp** [comment]
These versions don't seem to be released. I don't see them on Maven Central or JBoss Nexus.

**Comment by jfdenise** [comment]
I am using  -Pstaged-releases to resolve aesh from staging repo.

**Comment by jmesnil** [comment]
sorry, I misunderstood the comment. This PR is passing checks as the jobs using staging repos.
Do not merge unti @jfdenise confirm it is ok to merge :)

**Comment by jfdenise** [comment]
retest this please!

**Comment by jfdenise** [comment]
@jmesnil , aesh is publicly released. This one can be merged. Thanks.

**Pull request merged**
