### PR TITLE
[WFCORE-4853] Add support for External HTTP authentication mechanism …

### PR DESCRIPTION
**Pull request by ashley-abdelsayed98**
…with Elytron

https://issues.redhat.com/browse/WFCORE-4853
https://issues.redhat.com/browse/EAP7-1323

To pass CI, this will require an Elytron, Elytron Web, and Undertow upgrade but this is ready for the changes to be reviewed.
Depends on wildfly-security/wildfly-elytron#1386, wildfly-security/elytron-web#174, and undertow-io/undertow#881

### CODE REVIEW

**Comment by jmesnil** [comment]
@ashley-abdelsayed98 could you please rebase this PR? The changes in #4234 have introduced a merge conflict

**Comment by ashley-abdelsayed98** [comment]
Thank you @jmesnil I've rebased my branch!

**Comment by darranl** [comment]
Just waiting on a tag of Undertow so we can tag Elytron and Elytron Web and this one is then ready to go.

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
This was tested with the combined PR which also contained the required Elytron and Undertow component upgrades.

**Pull request merged**
