### PR TITLE
[WFCORE-5325] Additional tests for credential stores

### PR DESCRIPTION
**Pull request by OndrejKotek**
https://issues.redhat.com/browse/WFCORE-5325

Depends on #4495

### CODE REVIEW

**Comment by OndrejKotek** [comment]
The failure of `testExportNonExistingAlias` is expected due to dependency on #4495.

**Review by darranl — APPROVED** [review]
Thank you @OndrejKotek looks good to me.

**Comment by darranl** [comment]
Well apart from the actual test failures :smile: looks like they may need double checking.

**Comment by OndrejKotek** [comment]
> Well apart from the actual test failures smile looks like they may need double checking.

The failure of `CredentialStoreTestCase#testExportNonExistingAlias` is expected due to the dependency on #4495. I see no other failures now.

**Pull request merged**
