### PR TITLE
WFCORE-563: Upgrade to xerces 2.11.0.SP1

### PR DESCRIPTION
**Pull request by wolfc**
https://issues.jboss.org/browse/WFCORE-563

### CODE REVIEW

**Comment by wolfc** [comment]
We could revert https://issues.apache.org/jira/browse/XERCESJ-1353
https://github.com/jboss/xerces/commit/fb0b31519f9f8902c5d4061fcbc7ac4dc945bf5b

**Comment by langfr** [comment]
... or merge https://github.com/jboss/xerces/pull/4 ?

**Comment by wolfc** [comment]
This is a version with https://github.com/jboss/xerces/pull/6 in place.

**Comment by wolfc** [comment]
It seems the build is borked when using timed snapshots. That would be a different issue.

**Comment by kabir** [comment]
@wolfc we only accept proper releases

**Pull request merged**
