### PR TITLE
WFCORE-1356 Make an optional dependency on javax.transaction.api

### PR DESCRIPTION
**Pull request by tomjenkinson**
https://issues.jboss.org/browse/WFCORE-1356

### CODE REVIEW

**Comment by kabir** [comment]
Retest this please

**Comment by jamezp** [comment]
retest this please, failure doesn't seem related

**Comment by jamezp** [comment]
All tests have passed on this. The Core - windows just didn't report back.

**Comment by dmlloyd** [comment]
This PR is out of date now.

**Pull request closed without merging**
