### PR TITLE
WFCORE-4450 java.rmi package not visible to application

### PR DESCRIPTION
**Pull request by TomasHofman**
Issue: https://issues.jboss.org/browse/WFCORE-4450
WFLY issue: https://issues.jboss.org/browse/WFLY-12026
Downstream issue: https://issues.jboss.org/browse/JBEAP-16725

### CODE REVIEW

**Comment by bstansberry** [comment]
My impression is this is a workaround, the way https://issues.jboss.org/browse/WFLY-10394 was a workaround.  If so there needs to be an issue filed to get a final fix.

**Comment by TomasHofman** [comment]
Still working on this, I created this issue as a follow-up: https://issues.jboss.org/browse/MODULES-390

David disagrees however...

**Comment by TomasHofman** [comment]
I moved the follow-up issue to WFLY: https://issues.jboss.org/browse/WFLY-12032

**Comment by TomasHofman** [comment]
I will have no time to investigate proper solution until after EAP 7.2.2 is released, which is why I wanted to go with the workaround.

**Comment by TomasHofman** [comment]
Closing, the problem doesn't seem to be limited to rmi package.

**Pull request closed without merging**
