### PR TITLE
WFCORE-1056 try to prevent --empty-config from causing issues 

### PR DESCRIPTION
**Pull request by luck3y**
with embed-server if the configuration already exists and --remove-existing was not provided.

### CODE REVIEW

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by bstansberry** [comment]
@luck3y This handles the --empty-config problem nicely; better than waiting for the server start to barf. But there are other cases where the InstanceAlreadyExistsException logging will still happen. For example, try corrupting standalone.xml and starting, then fixing and starting again.

We need to ensure the MSC ServiceContainer gets shut down. I think something like https://github.com/wildfly/wildfly-core/compare/master...bstansberry:stop-msc will do the trick.

I expect embed-host-controller has a similar problem.

**Comment by luck3y** [comment]
@bstansberry +1 I'll check against embedded HC and send PR

**Comment by bstansberry** [comment]
retest this please

**Pull request closed without merging**
