### PR TITLE
[WFCORE-6070] Upgrade JBoss Modules to 2.1.0.Final

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-6070

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
Hi @ropalka , notice at this stage we are in bugfix only mode. The current JBoss Modules bump is a minor release and includes a feature request. I guess we are flexible if there is a higher requirement for this, otherwise, we should wait for WF20 and let it bake a bit.

WDYT?

**Comment by ropalka** [comment]
You are right @yersan , this 2.1.0.Final is only about switching its code base to JDK11 by default.
It don't need to be merged in WildFly 19 and can wait for WildFly 20.

**Comment by yersan** [comment]
Hi @ropalka , sadly, this one got a conflict, could you take a look? thanks

**Comment by ropalka** [comment]
Fixed @yersan

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
I've resolved a conflict introduced by https://github.com/wildfly/wildfly-core/pull/5196

**Pull request merged**
