### PR TITLE
WFCORE-1558 allow wildcards for read-children-names and read-children-resources

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
Had some hijinx figuring out what filteredData did, still not sure that adding it in the handlers is the right thing to do, as handleResult in GlobalOperationHandlers.AbstractMultiTargetHandler seems to want to add it itself, but theres a mixture of invocations some with null filterdata / some not.

**Comment by luck3y** [comment]
Example output:

[domain@localhost:9990 /] /server-group=*/:read-children-names(child-type=deployment)
{
    "outcome" => "success",
    "result" => [
        {
            "address" => [("server-group" => "main-server-group")],
            "outcome" => "success",
            "result" => ["hello.war"]
        },
        {
            "address" => [("server-group" => "other-server-group")],
            "outcome" => "success",
            "result" => ["hello.war"]
        }
    ]
}

[domain@localhost:9990 /] /server-group=*/:read-children-resources(child-type=deployment)
{
    "outcome" => "success",
    "result" => [
        {
            "address" => [("server-group" => "main-server-group")],
            "outcome" => "success",
            "result" => {"hello.war" => {
                "enabled" => true,
                "name" => "hello.war",
                "runtime-name" => "hello.war"
            }}
        },
        {
            "address" => [("server-group" => "other-server-group")],
            "outcome" => "success",
            "result" => {"hello.war" => {
                "enabled" => true,
                "name" => "hello.war",
                "runtime-name" => "hello.war"
            }}
        }
    ]
}

[domain@localhost:9990 /] /socket-binding-group=*/:read-children-names(child-type=socket-binding)
{
    "outcome" => "success",
    "result" => [{
        "address" => [("socket-binding-group" => "standard-sockets")],
        "outcome" => "success",
        "result" => []
    }]
}

**Comment by bstansberry** [comment]
This looks good, but there needs to be quite a lot of testing added. I'll poke a bit and give some recommended places.

**Comment by bstansberry** [comment]
org.jboss.as.test.integration.mgmt.access.StandardRolesBasicTestCase is a possible candidate. Having good RBAC coverage is essential.

**Comment by bstansberry** [comment]
In full, org.jboss.as.test.integration.domain.mixed.WildcardReadsTestCase is another. Hmm, that brings to mind a possible issue -- that this may not work properly on hosts before core version 3. In core 2 there was quite a bit of jumping through hoops to hide the fact that previous releases (i.e. EAP 6) did not understand cross-process wildcard reads (https://issues.jboss.org/browse/WFCORE-621). I'm guessing but I wouldn't be surprised if with this PR read-children-names and read-children-resources work for master and a current DC managing EAP 6.x slaves, but fails for WF 10 / EAP 7.0 slaves.

**Comment by luck3y** [comment]
No, problem, I'll add some tests, and maybe something in the mixed domain tests? I wanted to make sure I was on the right track first. Thanks for the pointers :)

**Comment by bstansberry** [comment]
Sounds good. The WildcardReadsTestCase one is in mixed-domain. I expect there are some other ones that may be good to update too.

Ah, there's another WildcardReadsTestCase in testsuite/rbac. So that's one to have a look. There's also a WildcardOperationsTestCase in testsuite/domain.

If you look at the commits for WFCORE-282, 287 and 621 those are relatively recent ones that dealt with wildcard ops in one way or another, so tests those touch may be candidates for more methods.

**Comment by bstansberry** [comment]
I put a fixme on this pending the tests so we don't need to check it. If github doesn't automatically remove it when you push changes to the branch, please ping me and I can manually do it.

**Comment by luck3y** [comment]
OK, cool. I'm almost there I think!

**Comment by bstansberry** [comment]
@luck3y what's the status on this one?

**Comment by luck3y** [comment]
@bstansberry I'm hoping to get back to it soon. It needs a resolution for the issues with using read-children-names (which always has a childType parameter, and the CLI validate() method unable to call a wildcarded version of read-operation-names to check the parameters.

I'll have another look towards the end of this week and hopefully get it fixed up.

**Comment by bstansberry** [comment]
Please ping me when this is ready and I'll remove the Hold label I'm about to add.

**Comment by luck3y** [comment]
Closing this for now, will revisit in the future.

**Pull request closed without merging**
