### PR TITLE
Upgrade apache httpclient from 4.4.1 to 4.5.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Will this allow us to use the same version in WildFly full?

**Comment by langfr** [comment]
I hope so.
There is an older PR: https://github.com/wildfly/wildfly/pull/7256 recently updated also. But still failing.

**Comment by bstansberry** [comment]
Note to self: http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62080&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments tests the https://github.com/wildfly/wildfly/pull/7256 branch and this one in combination.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Another note to self: that last experiment bombed, but here's another attempt using a rebased version of both this PR and the full one:

http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62124&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

**Comment by bstansberry** [comment]
Superceded by #1005. Thanks!

**Pull request closed without merging**
