### PR TITLE
WFCORE-5249: NoClassDefFoundError: Failed to link org/bouncycastle/op…

### PR DESCRIPTION
**Pull request by sudeshnas93**
Issue: https://issues.redhat.com/browse/WFCORE-5249

### CODE REVIEW

**Comment by bstansberry** [comment]
@ehsavoie please have a look so we can be sure the JIRA is resolved for WF 23.

**Comment by darranl** [comment]
The failures don't look related so I have re-triggered the failed CI jobs.

**Review by ehsavoie — CHANGES_REQUESTED** [review]
The export and services attributes are not required from my point of view

**Comment by darranl** [comment]
I am going to need this to be fixed in about the next 10 minutes as I am trying to aggregate some PRs onto CI as tagging of WildFly Core is imminent - I think I will submit a follow up PR based on this one to remove those two attributes.

**Comment by bstansberry** [comment]
Please do, @darranl 

Thanks

**Comment by ehsavoie** [comment]
@darranl :+1 as my reproducers don't need those so I think we are all clear on that

**Comment by darranl** [comment]
Superseded by https://github.com/wildfly/wildfly-core/pull/4513

**Pull request closed without merging**
