### PR TITLE
WFCORE-129 - overlay does not work for zipped files in exploded archive

### PR DESCRIPTION
**Pull request by baranowb**
WFLY: https://issues.jboss.org/browse/WFCORE-129
6.4.0: https://bugzilla.redhat.com/show_bug.cgi?id=1147352

### CODE REVIEW

**Comment by baranowb** [comment]
Done + rebase against master.

**Comment by baranowb** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Is this still an issue? I think it should have been resolved by my fix for https://issues.jboss.org/browse/WFCORE-547

**Comment by baranowb** [comment]
yep, it did. Closing this one.

**Pull request closed without merging**
