### PR TITLE
WFCORE-2977 Wildfly OpenSSL 1.0.0.CR4

### PR DESCRIPTION
**Pull request by stuartwdouglas**
https://issues.jboss.org/browse/WFCORE-2977

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Needs a rebase, and I guess it's meant to be CR5 now?

**Comment by stuartwdouglas** [comment]
Closing for now

**Pull request closed without merging**
