### PR TITLE
[WFCORE-6037] Upgrade to Jandex 3.0.0

### PR DESCRIPTION
**Pull request by Ladicek**
https://issues.redhat.com/browse/WFCORE-6037

### CODE REVIEW

**Comment by yersan** [comment]
@Ladicek, fyi. We need to integrate this PR together with the wildfly-core upgrade PR for wildfly.

To merge this PR we need:
1. We need to have the wildfly PR counterpart in place and ready. 
2. Then I can create a list of custom Jobs that use both of your topic branches to verify the integration works.
3. We will merge this PR 
4. We will bump the wildfly-core version in wildfly together with the WFLY-16917 PR

**Comment by Ladicek** [comment]
Sure. Note that the WildFly full PR isn't ready until:

- SmallRye OpenAPI has a Jandex 3 based release (which will likely have to be upgraded in the same PR);
- Hibernate 6.1.3 is released (that can be upgraded in WildFly independently of Jandex, because it's still compiled with Jandex 2, it's just compatible with Jandex 3 at runtime).

**Comment by Ladicek** [comment]
Status update:

- SmallRye OpenAPI has a Jandex 3 based release (3.0.0) now, and I already updated https://github.com/wildfly/wildfly/pull/15987 to use it; I think it would be best if https://github.com/wildfly/wildfly/pull/16026 was merged first
- Hibernate 6.1.3 is released and there's a PR for WildFly already: https://github.com/wildfly/wildfly/pull/16039; that should also be merged first

After both PRs to `wildfly/wildfly` mentioned above are merged, I'll rebase the Jandex 3.0 upgrade PR to WildFly full and then it will be ready.

**Comment by bstansberry** [comment]
@Ladicek I merged the ORM 6.1.3 and Open API 3.0.0-RC4 PRs.

**Comment by Ladicek** [comment]
Okay, let me rebase these PRs.

**Comment by Ladicek** [comment]
Both PRs rebased.

**Comment by yersan** [comment]
Integration Jobs:

https://ci.wildfly.org/viewLog.html?buildId=325260 (Linux integration)
https://ci.wildfly.org/viewLog.html?buildId=325262 (Bootable JAR)
https://ci.wildfly.org/viewLog.html?buildId=325264 (Galleon)
https://ci.wildfly.org/viewLog.html?buildId=325266 (Microprofile)
https://ci.wildfly.org/viewLog.html?buildId=325270 (WildFly Preview)
https://ci.wildfly.org/viewLog.html?buildId=325272 (Windows)

**Review by yersan — CHANGES_REQUESTED** [review]
Hi @Ladicek ,

Integration tests have revealed issues with your changes when we are wildfly-arquillian and the WildFly trimming capabilities.

See for example the following error trace from the Galleon integration Job:

```
[09:48:48] :	 [Step 4/5] [INFO] -------------------------------------------------------
[09:48:48] :	 [Step 4/5] [INFO]  T E S T S
[09:48:48] :	 [Step 4/5] [INFO] -------------------------------------------------------
[09:48:48] :	 [Step 4/5] [INFO] Running org.jboss.as.test.integration.deployment.deploymentoverlay.DeploymentOverlayTestCase
[09:48:56]W:	 [Step 4/5] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.864 s <<< FAILURE! - in org.jboss.as.test.integration.deployment.deploymentoverlay.DeploymentOverlayTestCase
[09:48:56]W:	 [Step 4/5] [ERROR] org.jboss.as.test.integration.deployment.deploymentoverlay.DeploymentOverlayTestCase  Time elapsed: 7.852 s  <<< ERROR!
[09:48:56] :	 [Step 4/5] org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy test.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0412: Required services that are not installed:" => ["module.resolved.service.\"deployment.test.war\".main","jboss.module.spec.service.\"deployment.arquillian-service\".main"],"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.module.resolve.phase.\"deployment.test.war\".main.1 is missing [jboss.module.spec.service.\"deployment.arquillian-service\".main]","jboss.module.service.\"deployment.test.war\".main is missing [module.resolved.service.\"deployment.test.war\".main]"]}}}
[09:48:56] :	 [Step 4/5] 	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:184)
[09:48:56] :	 [Step 4/5] 	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:162)
[09:48:56] :	 [Step 4/5] 	at org.jboss.as.arquillian.container.ArchiveDeployer.deploy(ArchiveDeployer.java:91)
[09:48:56] :	 [Step 4/5] 	at org.jboss.as.arquillian.container.CommonDeployableContainer.deploy(CommonDeployableContainer.java:256)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:151)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:118)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:239)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:118)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy(DeploymentExceptionHandler.java:47)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createDeploymentContext(ContainerDeploymentContextHandler.java:71)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:54)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:92)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:77)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachDeployment(ContainerDeployController.java:232)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachManagedDeployment(ContainerDeployController.java:212)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deployManaged(ContainerDeployController.java:77)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:96)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:48:56] :	 [Step 4/5] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:48:56] :	 [Step 4/5] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:89)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:163)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:177)
[09:48:56] :	 [Step 4/5] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[09:48:56] :	 [Step 4/5] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[09:48:56] :	 [Step 4/5] 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[09:48:56] :	 [Step 4/5] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[09:48:56] :	 [Step 4/5] 
[09:48:56] :	 [Step 4/5] [INFO] Running org.jboss.as.test.integration.deployment.resourcelisting.WarResourceListingTestCase
[09:48:56]F:	 [Step 4/5] org.jboss.as.test.integration.deployment.deploymentoverlay.DeploymentOverlayTestCase
[09:48:56]F:		 [org.jboss.as.test.integration.deployment.deploymentoverlay.DeploymentOverlayTestCase] DeploymentOverlayTestCase
[09:48:56]i:			 [DeploymentOverlayTestCase] [Test Output]
&amp#27;[0m08:48:50,248 INFO  [org.jboss.modules] (main) JBoss Modules version 2.0.3.Final
&amp#27;[0m&amp#27;[0m08:48:50,795 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.13.Final
&amp#27;[0m&amp#27;[0m08:48:50,808 INFO  [org.jboss.threads] (main) JBoss Threads version 2.4.0.Final
&amp#27;[0m&amp#27;[0m08:48:50,984 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: WildFly Full 27.0.0.Beta1-SNAPSHOT (WildFly Core 19.0.0.Beta18-SNAPSHOT) starting
&amp#27;[0mWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/store/repository/org/wildfly/core/wildfly-elytron-integration-jakarta/19.0.0.Beta18-SNAPSHOT/wildfly-elytron-integration-jakarta-19.0.0.Beta18-SNAPSHOT.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
&amp#27;[0m08:48:51,984 INFO  [org.wildfly.security] (ServerService Thread Pool -- 16) ELY00001: WildFly Elytron version 2.0.0.Beta3
&amp#27;[0m&amp#27;[33m08:48:52,294 WARN  [org.jboss.as.controller] (ServerService Thread Pool -- 24) WFLYCTL0481: The runtime dependency package 'io.smallrye.opentracing-contrib' is already registered at location '/subsystem=microprofile-opentracing-smallrye'
&amp#27;[0m&amp#27;[33m08:48:52,313 WARN  [org.jboss.as.controller] (ServerService Thread Pool -- 24) WFLYCTL0481: The runtime dependency package 'io.smallrye.opentracing-contrib' is already registered at location '/subsystem=microprofile-opentracing-smallrye'
&amp#27;[0m&amp#27;[0m08:48:52,793 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
&amp#27;[0m&amp#27;[0m08:48:52,816 INFO  [org.xnio] (MSC service thread 1-7) XNIO version 3.8.7.Final
&amp#27;[0m&amp#27;[0m08:48:52,825 INFO  [org.xnio.nio] (MSC service thread 1-7) XNIO NIO Implementation Version 3.8.7.Final
&amp#27;[0m&amp#27;[0m08:48:52,890 INFO  [org.jboss.remoting] (MSC service thread 1-8) JBoss Remoting version 5.0.25.Final
&amp#27;[0m&amp#27;[0m08:48:52,911 INFO  [org.wildfly.extension.microprofile.config.smallrye] (ServerService Thread Pool -- 47) WFLYCONF0001: Activating MicroProfile Config Subsystem
&amp#27;[0m&amp#27;[0m08:48:52,911 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 39) WFLYCLINF0001: Activating Infinispan subsystem.
&amp#27;[0m&amp#27;[0m08:48:52,917 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 51) WFLYNAM0001: Activating Naming Subsystem
&amp#27;[0m&amp#27;[0m08:48:52,917 INFO  [org.wildfly.extension.microprofile.opentracing] (ServerService Thread Pool -- 50) WFLYTRACEXT0001: Activating MicroProfile OpenTracing Subsystem
&amp#27;[0m&amp#27;[0m08:48:52,976 INFO  [org.wildfly.extension.metrics] (ServerService Thread Pool -- 46) WFLYMETRICS0001: Activating Base Metrics Subsystem
&amp#27;[0m&amp#27;[0m08:48:52,981 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 41) WFLYRS0016: RESTEasy version 6.2.0.Beta1
&amp#27;[0m&amp#27;[33m08:48:52,932 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 55) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
&amp#27;[0m&amp#27;[0m08:48:52,988 INFO  [org.wildfly.extension.health] (ServerService Thread Pool -- 38) WFLYHEALTH0001: Activating Base Health Subsystem
&amp#27;[0m&amp#27;[0m08:48:53,002 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 40) WFLYIO001: Worker 'default' has auto-configured to 8 IO threads with 64 max task threads based on your 4 available processors
&amp#27;[0m&amp#27;[0m08:48:53,008 INFO  [org.jboss.as.connector] (MSC service thread 1-8) WFLYJCA0009: Starting Jakarta Connectors Subsystem (WildFly/IronJacamar 1.5.8.Final)
&amp#27;[0m&amp#27;[0m08:48:53,018 INFO  [org.jboss.as.naming] (MSC service thread 1-8) WFLYNAM0003: Starting Naming Service
&amp#27;[0m&amp#27;[0m08:48:53,073 INFO  [org.wildfly.extension.microprofile.metrics.smallrye] (ServerService Thread Pool -- 49) WFLYMPMETRICS0001: Activating MicroProfile Metrics Subsystem
&amp#27;[0m&amp#27;[0m08:48:53,080 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0003: Undertow 2.3.0.Alpha2 starting
&amp#27;[0m&amp#27;[0m08:48:53,101 INFO  [org.wildfly.extension.microprofile.health.smallrye] (ServerService Thread Pool -- 48) WFLYMPHEALTH0001: Activating MicroProfile Health Subsystem
&amp#27;[0m&amp#27;[33m08:48:53,297 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-5) WFLYELY00023: KeyStore file '/opt/buildAgent/work/c5cf9919c8cd1e1c/full/testsuite/integration/web/target/wildfly-cloud/standalone/configuration/application.keystore' does not exist. Used blank.
&amp#27;[0m&amp#27;[33m08:48:53,310 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-5) WFLYELY01084: KeyStore /opt/buildAgent/work/c5cf9919c8cd1e1c/full/testsuite/integration/web/target/wildfly-cloud/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
&amp#27;[0m&amp#27;[0m08:48:53,310 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0012: Started server default-server.
&amp#27;[0m&amp#27;[0m08:48:53,320 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) Queuing requests.
&amp#27;[0m&amp#27;[0m08:48:53,321 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0018: Host default-host starting
&amp#27;[0m&amp#27;[33m08:48:53,553 WARN  [org.jboss.as.domain.http.api.undertow] (MSC service thread 1-7) WFLYDMHTTP0003: Unable to load console module for slot main, disabling console
&amp#27;[0m&amp#27;[0m08:48:53,594 INFO  [org.jboss.as.patching] (MSC service thread 1-4) WFLYPAT0050: WildFly Full cumulative patch ID is: base, one-off patches include: none
&amp#27;[0m&amp#27;[0m08:48:53,610 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0006: Undertow HTTP listener default listening on [::1]:8080
&amp#27;[0m&amp#27;[0m08:48:53,665 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-4) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/buildAgent/work/c5cf9919c8cd1e1c/full/testsuite/integration/web/target/wildfly-cloud/standalone/deployments
&amp#27;[0m&amp#27;[0m08:48:54,042 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
&amp#27;[0m&amp#27;[0m08:48:54,045 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 27.0.0.Beta1-SNAPSHOT (WildFly Core 19.0.0.Beta18-SNAPSHOT) started in 4133ms - Started 193 of 285 services (132 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
&amp#27;[0m&amp#27;[0m08:48:54,048 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://[::1]:9990/management
&amp#27;[0m&amp#27;[0m08:48:54,049 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
&amp#27;[0m&amp#27;[0m08:48:55,310 INFO  [org.jboss.as.repository] (management-handler-thread - 1) WFLYDR0001: Content added at location /opt/buildAgent/work/c5cf9919c8cd1e1c/full/testsuite/integration/web/target/wildfly-cloud/standalone/data/content/c0/741322333d5edb3e1bc32a71fc12eb096961e6/content
&amp#27;[0m&amp#27;[0m08:48:55,335 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0027: Starting deployment of "arquillian-service" (runtime-name: "arquillian-service")
&amp#27;[0m&amp#27;[31m08:48:55,908 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.module.service."deployment.arquillian-service".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.arquillian-service".main: WFLYSRV0179: Failed to load module: deployment.arquillian-service
	at org.jboss.as.server@19.0.0.Beta18-SNAPSHOT//org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:116)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jboss.modules.ModuleNotFoundException: org.jboss.jandex
	at org.jboss.modules.Module.addPaths(Module.java:1271)
	at org.jboss.modules.Module.link(Module.java:1627)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1655)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:303)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:287)
	at org.jboss.as.server@19.0.0.Beta18-SNAPSHOT//org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:93)
	... 8 more
```
The arquillian service is asking for the `org.jboss.jandex` module dependency. I found wildfly-arquillian is still using this dependency: https://github.com/wildfly/wildfly-arquillian/blob/main/protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/JMXProtocolPackager.java#L142

Since you have replaced the "org.jboss.jandex" modules with "io.smallrye.jandex" converting it into an alias, from Galleon point of view the alias is never provisioned when WildFly is trimmed, because there are no modules that depend on it.

I think a possible workaround without requiring a change/release of wildfly-arquillian will be to not replace the existing "org.jboss.jandex" dependencies on any WildFly JBoss Modules module. Doing it, I think Galleon will take into account the alias for the trimmed server and will provision both the alias and the target JBoss Modules module.

Maybe @jfdenise can confirm this detail, for sure the opposite is not working.

**Comment by Ladicek** [comment]
Sorry, I don't know anything about provisioning or trimming. I know I had a successful run of `mvn clean install -DallTests` a few weeks ago, so I thought the present state is OK. I'll be happy to do any modifications you recommend.

**Comment by yersan** [comment]
Sure, no problem @Ladicek. For now, without a new release of wildfly-arquillian, I believe we will be good if we don't rename the existing JBoss Modules dependencies, here and in the WIldFly PR counterpart. They will be pointing out to an alias, and once Galleon detects an alias, both the alias and the target module will be provisioned.

**Comment by Ladicek** [comment]
Updated both PRs to avoid the changes to module dependencies. All `module.xml` files still declare a dependency on `org.jboss.jandex`.

**Review by yersan — APPROVED** [review]
Thank you, @Ladicek; all integration Jobs are green, we are fine to proceed with this.

@bstansberry I plan to merge this for the next wildfly-core release, would you mind approving it to confirm you want it for WF27? Thanks

**Comment by Ladicek** [comment]
FYI, I've just released Jandex 3.0.1 with a few fixes. I'm not upgrading these PRs unless you tell me so, because I assume that at this point, it is probably easier for you to get the Jandex 3.0.0 upgrade merged and then move to 3.0.1 separately.

**Comment by yersan** [comment]
Hi @Ladicek, the plan is to merge this PR on Monday next week when I am releasing WildFly Core Beta18. Since it is all in place now, I think it is better to do the 3.0.0 integration and after that, we can bump the minor.

Would you agree?

**Comment by yersan** [comment]
> Would you agree?

well, yes, you are per your above comment, sorry for the noise, we can bump 3.0.1 micro next week. Notice, we will enter on bug fix only next week, no new features are allowed.

**Comment by Ladicek** [comment]
I sneaked in a few tiny features (as in, new methods in public API) into Jandex 3.0.1, but indeed it is mainly a bugfix release: https://smallrye.io/blog/jandex-3-0-1/

**Review by bstansberry — APPROVED** [review]
@Ladicek @yersan LGTM. +1 for getting this in 27 Beta1.

**Comment by yersan** [comment]
@Ladicek fully merged, in full as well, thanks!

**Pull request merged**
