### PR TITLE
WFCORE-1347 StringListAttributeDefinition.unwarp doesn't take default…

### PR DESCRIPTION
**Pull request by ctomc**
… value into account

downstream https://github.com/jbossas/wildfly-core-eap/pull/161

### CODE REVIEW

**Comment by ctomc** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by ctomc** [comment]
@n1hility this one needs https://github.com/wildfly/wildfly/pull/8647 to be merged first.

**Comment by n1hility** [comment]
retest this please

**Comment by bstansberry** [comment]
The latest windows failure has this in the build.log:


[17:16:31][org.wildfly:wildfly-ts-integ-basic] Running org.jboss.as.test.integration.ee.appclient.basic.SimpleApplicationClientTestCase
[17:17:52][org.wildfly:wildfly-ts-integ-basic] org.jboss.as.test.integration.ee.appclient.basic.SimpleApplicationClientTestCase
[17:17:52][org.jboss.as.test.integration.ee.appclient.basic.SimpleApplicationClientTestCase] testAppClientJBossDescriptor
[17:17:52]
[testAppClientJBossDescriptor] java.lang.AssertionError: App client call failed. App client output: 17:16:47,321 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 25) WFLYWS0002: Activating WebServices Extension
17:16:47,296 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 24) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
17:16:47,277 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 23) WFLYSEC0002: Activating Security Subsystem
17:16:47,300 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 22) WFLYNAM0001: Activating Naming Subsystem
17:16:47,292 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 26) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "appclient")]) - failure description: "WFLYCTL0155: parameters may not be null"
17:16:47,491 INFO  [org.wildfly.iiop.openjdk] (ServerService Thread Pool -- 19) WFLYIIOP0001: Activating IIOP Subsystem
17:16:47,696 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
17:16:48,087 INFO  [org.jboss.as.security] (MSC service thread 1-4) WFLYSEC0001: Current PicketBox version=4.9.5.Final
17:16:48,122 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 16) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
17:16:48,392 INFO  [org.jboss.as.connector] (MSC service thread 1-1) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.3.2.Final)
17:16:48,987 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0018: Started Driver service with driver-name = h2
17:16:49,479 INFO  [org.jboss.ws.common.management] (MSC service thread 1-2) JBWS022052: Starting JBossWS 5.1.3.SP1 (Apache CXF 3.1.4) 
17:16:51,224 INFO  [org.wildfly.iiop.openjdk] (MSC service thread 1-1) WFLYIIOP0009: CORBA ORB Service started
17:16:51,425 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
17:16:52,405 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 10.1.0.Final-SNAPSHOT (WildFly Core 2.1.0.CR3-SNAPSHOT) started in 11288ms - Started 126 of 129 services (12 services are lazy, passive or on-demand)
[17:17:52]
[testAppClientJBossDescriptor] java.lang.AssertionError: App client call failed. App client output: 17:16:47,321 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 25) WFLYWS0002: Activating WebServices Extension
17:16:47,296 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 24) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
17:16:47,277 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 23) WFLYSEC0002: Activating Security Subsystem
17:16:47,300 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 22) WFLYNAM0001: Activating Naming Subsystem
17:16:47,292 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 26) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "appclient")]) - failure description: "WFLYCTL0155: parameters may not be null"
17:16:47,491 INFO  [org.wildfly.iiop.openjdk] (ServerService Thread Pool -- 19) WFLYIIOP0001: Activating IIOP Subsystem
17:16:47,696 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
17:16:48,087 INFO  [org.jboss.as.security] (MSC service thread 1-4) WFLYSEC0001: Current PicketBox version=4.9.5.Final
17:16:48,122 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 16) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
17:16:48,392 INFO  [org.jboss.as.connector] (MSC service thread 1-1) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.3.2.Final)
17:16:48,987 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0018: Started Driver service with driver-name = h2
17:16:49,479 INFO  [org.jboss.ws.common.management] (MSC service thread 1-2) JBWS022052: Starting JBossWS 5.1.3.SP1 (Apache CXF 3.1.4) 
17:16:51,224 INFO  [org.wildfly.iiop.openjdk] (MSC service thread 1-1) WFLYIIOP0009: CORBA ORB Service started
17:16:51,425 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
17:16:52,405 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 10.1.0.Final-SNAPSHOT (WildFly Core 2.1.0.CR3-SNAPSHOT) started in 11288ms - Started 126 of 129 services (12 services are lazy, passive or on-demand)

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.jboss.as.test.integration.ee.appclient.basic.SimpleApplicationClientTestCase.testAppClientJBossDescriptor(SimpleApplicationClientTestCase.java:152)

So, problem with 'parameters' attribute on subsystem=appclient

Seems related to this PR given the declaration of that param in AppClientSubsystemResourceDefinition

    public static final StringListAttributeDefinition PARAMETERS = new StringListAttributeDefinition.Builder(Constants.PARAMETERS)
            .setAllowExpression(true)
            .build();

**Comment by ctomc** [comment]
opened https://github.com/wildfly/wildfly/pull/8720 for the appclient fix

**Comment by ctomc** [comment]
integration job for both PRs https://ci.wildfly.org/viewLog.html?buildId=9239&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

**Comment by ctomc** [comment]
the integration job passed. Only usual clustering tests are failing :|

**Comment by ctomc** [comment]
Integration job passes completely after downstream PR was updated to fix clustering issue.
see: https://ci.wildfly.org/viewLog.html?buildId=9266&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

**Comment by ctomc** [comment]
test

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
yey! it passes!

**Pull request merged**
