### PR TITLE
[WFCORE-4302] Validation of 'host-context-map' attribute of 'server-ssl-sni-context' should not reject ^ character

### PR DESCRIPTION
**Pull request by Skyllarr**
https://issues.redhat.com/browse/WFCORE-4302

### CODE REVIEW

**Comment by Skyllarr** [comment]
@darranl I fixed this and added a simple test as well.

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
@bstansberry are you likely to want a model bump and transformer for this one?

**Comment by bstansberry** [comment]
@darranl @Skyllarr I guess the argument for a transformer would be to detect values that were previously rejected and have the transformer reject them?

Both doing nothing (so the resource/op fails on the legacy host) or a reject transformer mean a failure, but the reject transformer is perhaps an easier to understand one.  That's a pretty minor benefit; not worth a version bump + transformer IMO.

A middle ground (that I'm not asking for) is to file a reminder JIRA and if you end up with a model bump for WF 24 anyway, add the transformer. If you don't, then 'Won't Do' resolve it. My impression is a lot of the pain is the model bump.

**Comment by darranl** [comment]
@Skyllarr I think to be complete we should just add the transformer, the model bump PR is here https://github.com/wildfly/wildfly-core/pull/4530

**Comment by Skyllarr** [comment]
> @Skyllarr I think to be complete we should just add the transformer, the model bump PR is here #4530

@darranl  Thanks. I added the transformer.

**Comment by darranl** [comment]
This PR is still active, we just need at least one feature for the model bump.

**Pull request merged**
