### PR TITLE
WFCORE-396 READ_ONLY domain server ops

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by bstansberry** [comment]
Cool; the test failure is evidence of test coverage!

**Comment by luck3y** [comment]
I was hoping something like this would happen ;)

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Pull request merged**
