### PR TITLE
[WFCORE-7089] When setting a policy in the PolicyDefinitions do not a…

### PR DESCRIPTION
**Pull request by jamezp**
…ttempt to refresh the policy if it's null.

https://issues.redhat.com/browse/WFCORE-7089

### CODE REVIEW

**Comment by bstansberry** [comment]
@darranl or @fjuma Is this ok?

The NPE fix is clearly fine; I just want to make sure you don't see anything wrong with 'policy' being null in the first place.

**Comment by bstansberry** [comment]
Well, I asked so I'll be patient a bit for an answer, but thinking more this seems fine. The 'policy' param is null because it's what was read from getPolicy() in service start, and on SE 24 there is no particular reason for that call to return anything but null.

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
@bstansberry yes this is fine, before Java 24 we would have always had a policy but 24 onwards we will never have a Policy - this service is sufficiently self contained there are not other reasons this would become null.

**Comment by darranl** [comment]
The test failures look unrelated, I was going to kick off CI but I see we have a big queue at the moment.

**Comment by yersan** [comment]
@darranl test failures are old friends and unrelated, they are also failing with similar traces for other PR, the xerces one is recently, but unrelated. I adding a "ready-to-merge"

**Pull request merged**
