### PR TITLE
[WFCORE-497] Do cross-model validation in a separate step

### PR DESCRIPTION
**Pull request by bstansberry**
While at it I made a couple minor changes to how data is obtained during validation.

### CODE REVIEW

**Comment by ctomc** [comment]
Just thinking out loud, couldn't we do validation like this also in ValidateModelStepHandler? which is already ran as separate step.

**Comment by kabir** [comment]
The concern here seems to be very different wrt to the ValidateModelStepHandler question.

**Comment by bstansberry** [comment]
@ctomc Eventually much of this stuff should be done in something like ValidateModelStepHandler, or perhaps internally in the OC the way that capabilities and requirements are resolved. I'm talking here about the "validating model ref" part. These particular OSHs also do some pretty-custom validation that I don't envision us handling centrally -- the HandlerUtil.checkNoOtherHandlerWithTheSameName bit.

I did this as a one-off because it is blocking Alexey's work.

**Comment by ctomc** [comment]
makes sense, tnx @bstansberry

**Pull request merged**
