### PR TITLE
[WFCORE-5888] Upgrade httpcore to 4.4.15

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFCORE-5888

### CODE REVIEW

**Comment by boris-unckel** [comment]
Please find git-tag, git-diff, release notes links in the Jira.

**Review by yersan — APPROVED** [review]
@jamezp This is a maintenance release only, but would you mind also approving from RestEasy point of view?

**Comment by yersan** [comment]
@boris-unckel the Jhonzon removal made a conflict on this one. Would you mind rebasing this? thanks!

**Comment by jmesnil** [comment]
@boris-unckel thanks

**Pull request merged**
