### PR TITLE
[WFCORE-1479]: Jar sub deployment has as first dependency parent ear

### PR DESCRIPTION
**Pull request by vpakan**
JIRA: https://issues.jboss.org/browse/WFCORE-1479
EAP 7.1 Jira: https://issues.jboss.org/browse/JBEAP-5267

### CODE REVIEW

**Comment by bstansberry** [comment]
@dmlloyd or @stuartwdouglas or someone more familiar with this: is this ok?

**Comment by kabir** [comment]
@stuartwdouglas ^^

**Comment by rsvoboda** [comment]
@vpakan, could you please add test to guard this fix?

**Comment by stuartwdouglas** [comment]
I think this looks reasonable.

**Pull request merged**
