### PR TITLE
WFCORE-757 Update build tools and generate host.xml from subsystem te…

### PR DESCRIPTION
**Pull request by stuartwdouglas**
…mplates

### CODE REVIEW

**Comment by bstansberry** [comment]
The "Core - Full Integration" failure looks related.

**Comment by ctomc** [comment]
```
Failed to execute goal org.wildfly.build:wildfly-feature-pack-build-maven-plugin:1.0.0.Final:build (feature-pack-build) on project wildfly-servlet-feature-pack: Execution feature-pack-build of goal org.wildfly.build:wildfly-feature-pack-build-maven-plugin:1.0.0.Final:build failed: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create feature pack from org.wildfly.core:wildfly-core-feature-pack:2.0.0.Alpha5-SNAPSHOT: ParseError at [row,col]:[3,52]
[ERROR] Message: Unexpected element '{urn:wildfly:feature-pack:1.1}feature-pack'
```

**Comment by stuartwdouglas** [comment]
The -full version of this PR needs to be merged first: https://github.com/wildfly/wildfly/pull/7600

Otherwise the removal of the host.xml files break domain mode in -full. Once the -full version has been merged this should work.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
oops; thought i'd merged the full one but hadn't.

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
