### PR TITLE
ModelController-client needs to be using JDK8 source level, to prepar…

### PR DESCRIPTION
**Pull request by ctomc**
…e it for elytron.

### CODE REVIEW

**Comment by bstansberry** [comment]
This isn't necessary for core 2.0.0, correct?

**Comment by ctomc** [comment]
this should to be in for EAP7.0, whatever core release will that use.
Otherwise we will have problems with 7.1 moving it to 8 because of elytron needs which would cause another set of problems.

**Comment by bstansberry** [comment]
David tells me the Elytron work will not be negatively impacted by deferring this to 7.1 so I don't want to make this change at this late date based on Elytron needs.

**Comment by ctomc** [comment]
Only thing I am arguing is that for 7.0 we will have requirement for modelcontroller client usage to be JDK6, and in 7.1 it will be bumped to 8. which might break some clients that will be using it when they upgrade.
Argument boils down to, isn't it better to have such change in initial major release so we only break users client code once instead of twice.
I am sure that number of users that might be affected by this will be minimal but it will still exist.

**Comment by dmlloyd** [comment]
It's a client library; if the change is a problem for them, they will continue to use the 7.0 version.

**Pull request closed without merging**
