### PR TITLE
[18.x] Fix for WFCORE-5756, Upgrade bootable jar to 7.0.0.Final

### PR DESCRIPTION
**Pull request by jfdenise**
Issue: https://issues.redhat.com/browse/WFCORE-5756
Diff: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/6.1.1.Final...7.0.0.Final

### CODE REVIEW

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
@jfdenise I'm no longer sure we want to update bootable jar for this `18.x`branch. This branch is meant to be used for WildFly 26. I thought that the major bump for bootable jar version was aligned with WildFly version.
Should we stick to this match:
* Bootable Jar 6.x -> WildFly 26.x
* Bootable Jar 7.x -> WildFly 27.x

This question is also relevant for https://github.com/wildfly/wildfly/pull/15045

**Comment by bstansberry** [comment]
@jmesnil I didn't see your comments here and merged https://github.com/wildfly/wildfly/pull/15045. That can be reverted if need be. The 7 release looked like it was basically just moving to WF 26 for its examples, which seemed valid for a 26.x test fixture. But there may be something more to it.

**Comment by jfdenise** [comment]
@jmesnil , 7.0.0.Final depends on WildFly 26, 6.0.0.Final depends on WildFly 25.0.0.Final. This is good to merge.

**Comment by jmesnil** [comment]
@jfdenise thanks!

**Pull request merged**
