### PR TITLE
[WFCORE-5254] Fix domain-management module OSHs that are populating t…

### PR DESCRIPTION
**Pull request by bstansberry**
…he runtime with data from the operation instead of the Resource tree

https://issues.redhat.com/browse/WFCORE-5254

### CODE REVIEW

**Review by yersan — APPROVED** [review]
At host-controller module level, StaticDiscoveryAddHandler and DiscoveryOptionAddHandler seems to have the similar potential bug, I'll file a Jira separate Jira to address them.

**Comment by yersan** [comment]
`StaticDiscoveryAddHandler` and `DiscoveryOptionAddHandler` seem don't fit in this category. They work upon placeholder resources, which doesn't have a model associated.

**Comment by bstansberry** [comment]
@yersan I think your instinct to file a JIRA about those handlers is a good one; at least a minor priority task to look into them. That code is pretty unusual and it's good to make it clean to avoid future bugs introduced by maintainers. At worst the task might result in adding some comments to explain why the code does what it does.

This kind of thing is generally a minor thing; it only matters in edge cases involving composite ops where more than one step alters the relevant part of the model. Then the 'operation' object would not be showing the true configuration.

**Comment by yersan** [comment]
StaticDiscoveryAddHandler and DiscoveryOptionAddHandler details will be tracked on https://issues.redhat.com/browse/WFCORE-5281

**Comment by jmesnil** [comment]
@bstansberry thanks

**Pull request merged**
