### PR TITLE
[WFCORE-5563]: Remove commons-lang(2) usage, use commons-lang3

### PR DESCRIPTION
**Pull request by langfr**
Jira https://issues.redhat.com/browse/WFCORE-5563

Requires
https://github.com/wildfly/wildfly/pull/14581
https://github.com/wildfly/wildfly/pull/14700

### CODE REVIEW

**Comment by boris-unckel** [comment]
@darranl This has been labeled "on hold" due to possible merge conflicts with the legacy security removal. Is this still valid? Does a backport to 18.x add value?

**Comment by bstansberry** [comment]
@langfr @boris-unckel I removed the 'hold' label and started a fresh CI run. If it passes picking it to the 18.x branch sounds good but not critical. It's a test dep. Cleaning out test deps in 18.x is good too though.

**Comment by yersan** [comment]
Thanks for the contribution, @langfr !

**Pull request merged**
