### PR TITLE
Revert "Revert "[WFCORE-263] Detect and react to domain rollout issue…

### PR DESCRIPTION
**Pull request by bstansberry**
…s in invocations of cancel|find-non-progressing-operation on a slave HC""

This reverts my original revert of the WFCORE-263 fix. I reverted it due to unexplained testsuite instability it introduced. I'm hoping that changes I introduced in domain op handling late in the core 2.0.0 cycle will make this stable.

I originally put a "Hold" label on this as my main goal opening it was to be able to trigger lots of CI runs. It's now been getting runs for 4+ months and I haven't seen the hang problems so I think it's good to go.

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by n1hility** [comment]
Retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
