### PR TITLE
[WFCORE-4571] Value of 'soft-fail' attribute in 'elytron/trust-manager'…

### PR DESCRIPTION
**Pull request by jstourac**
… is not propagated

- fixes propagation of soft-fail attribute configuration in trust-manager resource

https://issues.jboss.org/browse/WFCORE-4571

### CODE REVIEW

**Comment by darranl** [comment]
@jstourac Thank you for the contribution, once we are merging to WildFly or WildFly Core we should be referencing Jira issues from the respective projects rather than the WFWIP which is more of a process specific issue.

Can you please either clone or move the WFWIP issue over to WFCORE and update the commit message and PR title?  This then looks like it should be quite quick to approve and merge.

**Comment by jstourac** [comment]
@darranl, sorry, my bad, I should have realized it myself. I've moved wfwip issue to wfcore one and updated all relevant references. Should be ready for further steps now. Thank you! :)

**Comment by jstourac** [comment]
@jmesnil, @darranl, anything I can do to help with this one? I believe that test failures in job with security manager are not related to these changes.

**Comment by jstourac** [comment]
@darranl, thank you. I've just made the issue public.

**Pull request merged**
