### PR TITLE
[WFCORE-5171] Upgrade XNIO to 3.8.4.Final

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WFCORE-5171

### CODE REVIEW

**Comment by bstansberry** [comment]
@fl4via @dmlloyd It seems this release is not present in nexus.

**Comment by dmlloyd** [comment]
It looks like the xnio-all artifact is, but the others aren't.  It seems like something went wrong with the Maven deploy and I'm not sure how to fix it.  I think I might have to torpedo that one and try again with 3.8.4.Final.

**Comment by dmlloyd** [comment]
3.8.4.Final is released; it should (🤞🏻) be on Nexus in the next 24 hours.

**Comment by bstansberry** [comment]
@gaol Can you change the JIRA / commit msg / PR title to 3.8.4 please? Thanks.

**Comment by gaol** [comment]
@bstansberry Done !

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
