### PR TITLE
[WFCORE-5024] RESTEasy integration with WildFly Elytron - Authenticat…

### PR DESCRIPTION
**Pull request by Skyllarr**
…ionClient for Authentication / SSL

https://issues.redhat.com/browse/WFCORE-5024

### CODE REVIEW

**Comment by darranl** [comment]
The requirements are in place for this feature, we just have some prior component upgrades needed before this one is merged into core.

**Comment by darranl** [comment]
@Skyllarr We should be close to merging this one but it currently has a conflict, can you please rebase?

**Comment by Skyllarr** [comment]
@darranl Rebased.

**Comment by jmesnil** [comment]
@Skyllarr thanks

**Pull request merged**
