### PR TITLE
[WFCORE-4014] Using DelegatingTrustManager correctly to ensure new TrustManager will be used on re-initialization by existing SSLContexts

### PR DESCRIPTION
**Pull request by justinmcook**
Jira: https://issues.jboss.org/browse/WFCORE-4014

### CODE REVIEW

**Comment by darranl** [comment]
@justinmcook just one small comment regarding the commit message - it is useful to try and have a message that mentions either what you are fixing or what you are changing.

In five or ten years time someone may be trying to work out the history, although you can cross reference the Jira is is easier if you get a brief pointer from the commit message.

**Comment by hkalina** [comment]
Actually it is my commit message :innocent: I has not find brief description of:
Using DelegatingTrustManager correctly to ensure new TrustManager will be used on re-initialization by existing SSLContexts

**Comment by darranl** [comment]
The long description also works for me :-)

**Comment by justinmcook** [comment]
Update title and commit message to be longer/more descriptive

**Pull request merged**
