### PR TITLE
[WFCORE-6291] Obtain the complete set of PolicyContextHandler implementations from the Elytron EE module.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-6291
https://issues.redhat.com/browse/WFCORE-6298
https://issues.redhat.com/browse/WFCORE-6299

### CODE REVIEW

**Review by Skyllarr — APPROVED** [review]

**Review by bstansberry — APPROVED** [review]

**Comment by luck3y** [comment]
Note the jobs are running here: https://ci.wildfly.org/buildConfiguration/WFCorePRAggregator/363696?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

I'm looking into why the status doesn't appear to be updating.

**Comment by luck3y** [comment]
... annnd right as I type that comment they updated.

**Comment by yersan** [comment]
Thanks to all involved in the review

**Pull request merged**
