### PR TITLE
[WFCORE-4495] Upgrade wildfly-openssl to 1.0.7.Final

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.jboss.org/browse/WFCORE-4495

### CODE REVIEW

**Comment by fl4via** [comment]
@darranl @jmesnil It should be fixed now :-)

**Comment by jmesnil** [comment]
@fl4via could you please open a PR for this upgrade against wildfly-core 9.0.x branch?

**Comment by jmesnil** [comment]
@fl4via never mind, I created the PR against 9.x myself in #3848  :)

thanks!

**Comment by fl4via** [comment]
@jmesnil thanks! :)

**Pull request merged**
