### PR TITLE
[WFCORE-4904] Remove setting Metaspace

### PR DESCRIPTION
**Pull request by moulalis**
Issue JIRA : https://issues.redhat.com/browse/WFCORE-4904

### CODE REVIEW

**Comment by bstansberry** [comment]
We need a clear case for removing the -XX:MetaspaceSize=96M setting. The discussion I've seen around this is focused on the -XX:MaxMetaspaceSize setting.

The -XX:MetaspaceSize=96M setting was added because we observed that relying on the default value resulted in a full gc in the middle of server boot as the jvm adjusted to the necessary amount of memory.  That had a small impact on boot speed.

**Comment by darranl** [comment]
Based on Brian's comments I have added the hold label as this sounds like it needs to be a part of a larger investigation.

**Comment by moulalis** [comment]
> Based on Brian's comments I have added the hold label as this sounds like it needs to be a part of a larger investigation.

@darranl Thanks for adding Hold label on it, even I was looking for the same. Investigating more on it.

**Comment by moulalis** [comment]
Working on it.

**Pull request closed without merging**
