### PR TITLE
[WFCORE-3665] Bump the domain management version to 7.0.0

### PR DESCRIPTION
**Pull request by jmesnil**
* add wildfly-config_7_0.xsd and bump the domain namespace to urn:jboss:domain:7.0

There is no schema changes between wildfly-config_7_0.xsd and the
previous wildfly-config_6_0.xsd

JIRA: https://issues.jboss.org/browse/WFCORE-3665

### CODE REVIEW

**Comment by jmesnil** [comment]
@bstansberry fiy I made a global find and replace for the XSD namespace change in the test files. I checked from the diff that I did not change files that should have stayed on the previous 6.0 schema but I may have missed some subtleties especially with regards to legacy test cases.

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
This PR requires https://github.com/wildfly/wildfly/pull/11017 to be merged in WildFly to ensure that all XML validation tests passes for WildFly integration tests with core snapshots.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
