### PR TITLE
[WFCORE-2635] Upgrade WildFly Elytron to 1.1.0.Beta35 and Backport Latest Changes

### PR DESCRIPTION
**Pull request by darranl**
:warning: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :warning:

This PR resolves the following issues: -
   https://issues.jboss.org/browse/WFCORE-2553
   https://issues.jboss.org/browse/WFCORE-2574
   https://issues.jboss.org/browse/WFCORE-2517
   https://issues.jboss.org/browse/WFCORE-2371
   https://issues.jboss.org/browse/WFCORE-2556
   https://issues.jboss.org/browse/WFCORE-2482
   https://issues.jboss.org/browse/WFCORE-2614
   https://issues.jboss.org/browse/WFCORE-2625
   https://issues.jboss.org/browse/WFCORE-2474
   https://issues.jboss.org/browse/WFCORE-2581
   https://issues.jboss.org/browse/WFCORE-2635
   https://issues.jboss.org/browse/WFCORE-2636

### CODE REVIEW

**Comment by darranl** [comment]
Experimental Build Parameters: -

* WildFly Core *

Repository - https://github.com/wildfly-security-incubator/wildfly-core.git
Branch - WFCORE-2635

* WildFly *

Repository - https://github.com/wildfly-security-incubator/wildfly.git
Branch - WFLY-8527

**Comment by darranl** [comment]
Experimental Builds: -

https://ci.wildfly.org/viewLog.html?buildId=54056&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

https://ci.wildfly.org/viewLog.html?buildId=54060&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperimentsWindows

**Comment by darranl** [comment]
Replacement Windows Build 

https://ci.wildfly.org/viewLog.html?buildId=54063&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperimentsWindows

**Comment by bstansberry** [comment]
retest this please

**Comment by kabir** [comment]
I increased the timeout on the windows experiments job rerun at https://ci.wildfly.org/viewLog.html?buildId=54135&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperimentsWindows

**Pull request merged**
