### PR TITLE
WFCORE-6080 Remove AttributeDefinition.isAllowNull

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFCORE-6080

### CODE REVIEW

**Comment by parsharma** [comment]
Wildfly Issue: https://issues.redhat.com/browse/WFLY-17164
PR: https://github.com/wildfly/wildfly/pull/16181

Both PR needs to be merged together.

**Review by yersan — CHANGES_REQUESTED** [review]
Hello @parsharma , working with PRs that need to be changed on both sides is time-consuming and more complex. If there is a simple alternative to avoid that, that's preferable.

For this specific case, you can just deprecate the old method in WildFly Core and make it invoke the new one. We can release wildfly-core with both methods. Then you can drop the deprecations in wildfly and invoke directly the new method name available on wildfly-core. Once, the wildfly PR is merged, you can finally remove the deprecated method in wildfly-core. That workflow allows us to keep an eye on the CI on each step, and since every change is atomic, we do not need to be triggering Jobs manually. We can release wildfly-core at any moment to expedite the changes.

Sometimes, coordination is required between WildFly Core and WildFly, but if there is a simple alternative, that's preferable.

**Comment by parsharma** [comment]
@yersan sure. I will change the code accordingly. Thanks for the suggestion.

**Comment by parsharma** [comment]
@yersan I have updated the code. Please let me know your review comments. Thanks

**Review by yersan — APPROVED** [review]
Changes look good to me; they go beyond Jira requirements but changing `AbstractAttributeDefinitionBuilder` accordingly sounds logical to me too, after all, it is the builder for `AttributeDefinition`

**Pull request merged**
