### PR TITLE
[WFCORE-5106] Add configuration option in Elytron subsystem to change file encoding in FileAuditEndpoint.

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.redhat.com/browse/WFCORE-5106
Note: This change depends on Elytron issue ELY-1211. Merge after PR https://github.com/wildfly-security/wildfly-elytron/pull/1438 

https://issues.redhat.com/browse/EAP7-1557
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/335

### CODE REVIEW

**Comment by jmesnil** [comment]
this PR is out of sync with the main branch.
I'm closing it. Please reopen it when it is up to date and can be built.

**Comment by darranl** [comment]
Converted to draft as awaiting Elytron component upgrade.

**Comment by ivassile** [comment]
Reworked the PR to be in sync with the latest subsystem changes.

**Review by darranl — CHANGES_REQUESTED** [review]
FYI as a subsystem change this will need to be on top of version 14 of the model at the very least.

Without changing the SHAs can you please rebase or merge with the topic branch of this PR:
  https://github.com/wildfly/wildfly-core/pull/4530

Ping me if you want me to confirm what I am saying but we have about 5 PRs building on top of the work in #4530

**Comment by ivassile** [comment]
Rebased and reworked the PR to use the latest version 14 of the model.

**Comment by darranl** [comment]
This PR is still in progress, we are awaiting the process to progress.

**Comment by ivassile** [comment]
Modified the PR to be on top of version 15.1.

**Pull request closed without merging**
