### PR TITLE
[WFCORE-5169] upgraded to Apache Directory Server AM27 and Kerby

### PR DESCRIPTION
**Pull request by istudens**
Issue: https://issues.redhat.com/browse/WFCORE-5169
Related Issues: 
https://issues.redhat.com/browse/WFCORE-6485
https://issues.redhat.com/browse/WFCORE-5255

### CODE REVIEW

**Comment by istudens** [comment]
@darranl @fjuma can you review this please? thanks

**Comment by fjuma** [comment]
Thank you very much for working on this @istudens!

Just wanted to ask if you've done a quick sanity check with IBM JDK just to make sure there are no new test failures with these changes (i.e., just to make sure the failures from [WFCORE-5432](https://issues.redhat.com/browse/WFCORE-5432) won't occur anymore with these new changes).

**Comment by istudens** [comment]
@fjuma Nope, I missed IBM JDK. I will test it.

**Comment by istudens** [comment]
@fjuma It looks good to me even with IBM JDK 11 (both /elytron and /testsuite/elytron tests).

**Comment by fjuma** [comment]
Thanks for confirming that @istudens!

**Comment by yersan** [comment]
CC @Skyllarr in case you missed the request for review

**Comment by Skyllarr** [comment]
Oops I missed this, reviewing now

**Comment by Skyllarr** [comment]
@istudens Thanks!

**Comment by yersan** [comment]
Thanks @fjuma @Skyllarr and @istudens

**Pull request merged**
