### PR TITLE
[WFCORE-39] : Make KeepAliveTimeAttributeDefinition deal with both a sim...

### PR DESCRIPTION
**Pull request by ehsavoie**
...ple long and a complex attribute.

Transforming KeepAliveTimeAttributeDefinition in Model from a complex Object to a Long.
All keep-alive now are expressed as long in milliseconds.
This will affects all subsystems using the "threads" subsystem in wildfly which will be treated in another PR once this one is integrated and released.
Jira: https://issues.jboss.org/browse/WFCORE-39
Replace : https://github.com/wildfly/wildfly-core/pull/64
Requires : https://github.com/wildfly/wildfly/pull/7850 in full for integration tests

### CODE REVIEW

**Comment by ctomc** [comment]
please hold this until all other threads related stuff is merged in first. Also transformers in such state as are in this PR are no longer ok considering all other changes we did.

**Comment by jamezp** [comment]
These failures seem related.

**Comment by ehsavoie** [comment]
The failures are due to the conversion of all keep alive times to a single time unit aka milliseconds.
Since we are matching the XML this fails. It needs a PR on full for it to work.

**Comment by ehsavoie** [comment]
It requires https://github.com/wildfly/wildfly/pull/7850 in WildFly full for integration tests to pass.

**Comment by kabir** [comment]
Why is this needed? There must be more places where we have time+unit, so why this change to milliseconds in just one place? I'll close this since it has been rotting for a while, but if there is anything important I have missed which Brian wants, please feel free to reopen.

**Comment by kabir** [comment]
Speaking with Emmanuel, the driver for https://issues.jboss.org/browse/WFCORE-39 was https://issues.jboss.org/browse/WFLY-1877 and https://issues.jboss.org/browse/WFLY-1878 (both opened by Brian)

**Comment by bstansberry** [comment]
I need to decide what I want to do about this.

**Comment by ehsavoie** [comment]
:D Maybe just WFLY-1878 is sufficient.

**Comment by bstansberry** [comment]
Closing. Sorry for wasting your time on this. Part of the original reason for wanting to use long was the thinking we had a couple years back that complex attributes are evil. Since we've moved away from that mentality. OTOH we (particularly Jason) have moved even more strongly toward never breaking the API, and any shift of attribute types will break API, at least for reads even if we can be forgiving with writes.

**Pull request closed without merging**
