### PR TITLE
Bug fix: WFCORE-3522

### PR DESCRIPTION
**Pull request by yelhouti**
try to fix dependency order, local first

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is OK to test

**Comment by dmlloyd** [comment]
Though it's safe to say, it's unlikely to succeed :)

**Comment by bstansberry** [comment]
this is ok to test

**Comment by jmesnil** [comment]
The test failures are related to the PR:

```
Caused by: java.util.ServiceConfigurationError: org.jboss.msc.service.ServiceActivator: Provider org.jboss.as.test.integration.management.cli.modules.ModulesServiceActivator not a subtype"}}
```

```
java.lang.ClassCastException: org.jboss.as.connector.subsystems.datasources.WildFlyDataSource cannot be cast to org.jboss.as.connector.subsystems.datasources.WildFlyDataSource
```

**Comment by yelhouti** [comment]
the fix is much more complex, the problem is still there though

**Pull request closed without merging**
