### PR TITLE
[WFCORE-5465][WFCORE-5523] Git tests fail if git init.defaultBranch is not master

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/WFCORE-5465
https://issues.redhat.com/browse/WFCORE-5523

### CODE REVIEW

**Review by darranl — COMMENTED** [review]
I would suggest for both the commit message and the title of the Jira issue they are updated to better reflect the problem being fixed.

**Comment by petrberan** [comment]
That's a valid point @darranl , I've changed it into something more appropriate. Thank you

**Comment by petrberan** [comment]
Just noticed that test failure for this PR was caused by missing changes in https://github.com/wildfly/wildfly-core/pull/4707

The changes in https://github.com/wildfly/wildfly-core/pull/4707 depends on this PR, but at the same time changes in this PR depends on https://github.com/wildfly/wildfly-core/pull/4707 , resulting into test failures in both PRs.

In order to prevent build failures of WFCORE this PR contains changes for https://issues.redhat.com/browse/WFCORE-5465 and https://issues.redhat.com/browse/WFCORE-5523

**Review by ehsavoie — CHANGES_REQUESTED** [review]
The code looks good to me but the commit message should be improved:
The links to the 2 Jiras are missing
 JIRA: https://issues.redhat.com/browse/WFCORE-5465
          https://issues.redhat.com/browse/WFCORE-5523
And the commit message should explain a bit what is done a bit like that :
* setting the initial branch when initializing the git repository
* ensuring the branch name in tests is defined

**Comment by bstansberry** [comment]
Thanks @petrberan. +1 to mentioning both WFCORE-5465 and WFCORE-5523 in both the commit message and the PR title. The PR title becomes part of the merge commit message. Having those in the messages is really helpful for finding work by grepping the git log.

**Comment by petrberan** [comment]
Thanks for pointing this out @ehsavoie 

Is the PR format now correct @bstansberry ? I could always close this PR and open up a new one with two commits.

**Comment by darranl** [comment]
@petrberan it is not nescesary to submit a PR to split commits, if you work on your topic branch, split the commits and force push this PR will be updated.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @petrberan !

**Pull request merged**
