### PR TITLE
[WFCORE-4651] Upgrade WildFly Open SSL to 1.0.8.Final

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.jboss.org/browse/WFCORE-4651

### CODE REVIEW

**Comment by fl4via** [comment]
Retest this please

**Comment by darranl** [comment]
Are there any release notes available for this component upgrade?

**Comment by fl4via** [comment]
@darranl there aren't. Are these release notes required?

**Comment by jmesnil** [comment]
@fl4via During feature freeze, we need to be cautious about changes brought by component upgrades. A link to the release notes or the diff to the previous version really helps checking that there is no unintended changes or new features brought by accident

**Comment by jmesnil** [comment]
In this case the diff is enough: https://github.com/wildfly/wildfly-openssl/compare/1.0.7.Final...1.0.8.Final

**Comment by jmesnil** [comment]
@fl4via thanks

**Pull request merged**
