### PR TITLE
[WFCORE-2234] Introduce srcdeps

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.jboss.org/browse/WFCORE-2234

Let me open this on wildfly-dev ML first.

### CODE REVIEW

**Comment by ppalaga** [comment]
736f331 brings an update to srcdeps 3.1.0 which implements the `failWithout` feature that can be used to opt-in source dependencies only in some specific builds (such as pull request builds) and forbid them in all other cases. This is a requirement that resulted from the discussion on wildfly-dev [1]. The present config in `srcdeps.yaml` uses `srcdeps.enabled` property to allow source dependencies - hence maven needs to be invoked with `-Dsrcdeps.enabled`.

As asked for by @darranl , the `srcdeps.yaml` file is now located in the root directory of the project rather than in `.mvn` subdir.

[1] http://lists.jboss.org/pipermail/wildfly-dev/2017-January/005718.html

**Comment by ppalaga** [comment]
@kabir @bstansberry is there something missing in this PR? Otherwise, could it please be merged?

**Comment by ppalaga** [comment]
@kabir @bstansberry could this please be merged? Me and other team members would like to start using srcdeps in their PRs.

**Comment by bstansberry** [comment]
I'm going to leave this on to @n1hility. I didn't see a clear consensus on the list about this so I'll defer to formal authority. :)

**Comment by ppalaga** [comment]
> I'm going to leave this on to @n1hility.

@n1hility, could you please comment in the 'srcdeps' thread on the mailing list?

**Comment by ppalaga** [comment]
ecba2b9 upgrades to the latest srcdeps version

**Comment by jmesnil** [comment]
I'm closing this issue as there has been no consensus to introduce srcdeps in WildFly Core.
If that was subject to change, this PR can be reopened.

**Pull request closed without merging**
