### PR TITLE
[WFCORE-6600] Create logging category for com.networknt.schema

### PR DESCRIPTION
**Pull request by spyrkob**
Issue: https://issues.redhat.com/browse/WFCORE-6600

### CODE REVIEW

**Comment by yersan** [comment]
Hi @spyrkob , yaml expected files need to be adapted by incorporating the new configuration, ideally, we should avoid these sorts of maintenance to be more effective, I opened https://issues.redhat.com/browse/WFCORE-6602 for it

**Comment by spyrkob** [comment]
@yersan should I update those files in this PR or do we need to wait until WFCORE-6602 is resolved?

**Comment by yersan** [comment]
Hi @spyrkob , I think WFCORE-6602 will take some time before someone can work on it, so the better for this work is to adapt the test cases together with this PR

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
@spyrkob Thanks!

**Pull request merged**
