### PR TITLE
[WFCORE-3219] unignore AuditLogPeriodicRotatingFileHandlerTestCase.testRotate

### PR DESCRIPTION
**Pull request by kwart**
* https://issues.jboss.org/browse/WFCORE-3219
* https://issues.jboss.org/browse/JBEAP-12942

### CODE REVIEW

**Comment by bstansberry** [comment]
How can we be smarter here?

**Comment by darranl** [comment]
@bstansberry Are you looking for some rework on the test?

**Comment by jmesnil** [comment]
How can the test be faster to run?

The test takes more than 1 minute to run because it is sleeping for 61 seconds.
Could we change the rotating period to be smaller (e.g. at the second, with `.yyyy-MM-dd-hh-mm-ss`?

**Comment by wolfc** [comment]
Maybe put the test in a separate maven profile, so it only runs on CI machines?

**Comment by kwart** [comment]
As this will require more work, I'm closing this PR.

**Pull request closed without merging**
