### PR TITLE
[WFLY-15023][WFCORE-5573] Upgrade to JBoss Invocation 1.7.0.Final - supports both Javax & Jakarta based artifacts

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-5573
https://issues.redhat.com/browse/WFLY-15023

### CODE REVIEW

**Comment by ropalka** [comment]
@bstansberry please review

**Comment by jmesnil** [comment]
@ropalka This PR breaks WildFly Full compilation with the error:


```
[INFO] --- licenses-plugin:2.2.0.Final:insert-versions (update-licenses-xml) @ wildfly-preview-feature-pack ---
11:32:41
  [WARNING] Unable to obtain POM for artifact : io.undertow:undertow-websockets-jsr-jakartaee9:jar:2.2.10.Final:provided
11:32:41
  org.apache.maven.project.InvalidProjectModelException: Some problems were encountered while processing the POMs:
11:32:41
  [ERROR] 'dependencies.dependency.version' for io.undertow:undertow-servlet-jakartaee9:jar is missing. @ line 50, column 21
11:32:41
  [ERROR] 'dependencies.dependency.version' for io.undertow:undertow-servlet-jakartaee9:test-jar is missing. @ line 74, column 21
11:32:41
   for project
11:32:41
      at org.apache.maven.project.DefaultMavenProjectBuilder.transformError (DefaultMavenProjectBuilder.java:193)
11:32:41
      at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository (DefaultMavenProjectBuilder.java:240)
11:32:41
      at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository (DefaultMavenProjectBuilder.java:251)
11:32:41
      at org.wildfly.maven.plugins.licenses.DependenciesResolver.getDependencyMavenProject (DependenciesResolver.java:152)
11:32:41
      at org.wildfly.maven.plugins.licenses.DependenciesResolver.loadDependenciesAndConvertThem (DependenciesResolver.java:125)
11:32:41
      at org.wildfly.maven.plugins.licenses.UpdateLicensesMojo.getDependenciesLicenseInfos (UpdateLicensesMojo.java:284)
11:32:41
      at org.wildfly.maven.plugins.licenses.UpdateLicensesMojo.execute (UpdateLicensesMojo.java:239)
```

**Comment by ropalka** [comment]
This is because https://github.com/wildfly/wildfly/pull/14634 have to go in first @jmesnil . My fault.

**Comment by bstansberry** [comment]
https://github.com/wildfly/wildfly/pull/14634 is merged now

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @ropalka

**Pull request merged**
