### PR TITLE
[WFCORE-6368] Upgrading JBoss MSC to 1.5.1.Final

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-6368

### CODE REVIEW

**Review by yersan — APPROVED** [review]
LGTM

**Review by darranl — APPROVED** [review]

**Comment by yersan** [comment]
Thanks @ropalka

**Comment by pferraro** [comment]
I think the changes here are problematic.  ServiceTarget.addService(ServiceName) is now deprecated, and its replacement throws an UnsupportedOperationException?

**Comment by ropalka** [comment]
This upgrade has two parts. MSC side and WildFly side. This PR is about including latest MSC changes. Then I created https://issues.redhat.com/browse/WFCORE-6371 that needs to be sorted out in order to support new method @pferraro  .

**Comment by pferraro** [comment]
Discussion ongoing here: https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/New.20MSC.20Service.20API

**Pull request merged**
