### PR TITLE
WFCORE 579 ProxyMetadataSource does not return JDK8 'default' methods fro minterfaces

### PR DESCRIPTION
**Pull request by baranowb**
https://issues.jboss.org/browse/WFCORE-579
https://issues.jboss.org/browse/WFLY-4404
https://bugzilla.redhat.com/show_bug.cgi?id=1196686

PRs
upstream: https://github.com/wildfly/wildfly-core/pull/541
6.4.x: https://github.com/jbossas/jboss-eap/pull/2339

### CODE REVIEW

**Comment by ctomc** [comment]
retest this please

**Comment by baranowb** [comment]
Nice. Locally only org.jboss.as.test.integration.ee.injection.resource.resourceref.ResourceRefTestCase fail.

**Comment by baranowb** [comment]
retest this please

**Comment by baranowb** [comment]
All I can get is: org.jboss.as.test.clustering.xsite.XSiteSimpleTestCase but this happen after above test
:8ball:

**Comment by baranowb** [comment]
retest this please

**Comment by jimma** [comment]
@baranowb Can this issue be simply fixed by adding the default method in the constructor ?
```
+        //add default method
+        for (Method method : indexedClass.getMethods()) {
+            if (method.getDeclaringClass().isInterface() && (method.getModifiers() & (ABSTRACT | PUBLIC | STATIC)) == PUBLIC) {
+                method.setAccessible(true);
+                addMethod(methods, method);
+                addMethodByTypeName(methodsByTypeName, method);
+            }
+        }
 ```

**Comment by baranowb** [comment]
retest this please

**Comment by baranowb** [comment]
jimma: as I said. There are two classes that perform similar tasks - I rose this issue on dev list but did not get input, hence I did it like that.

**Comment by jimma** [comment]
retest this please

**Comment by bstansberry** [comment]
I've pinged the other committers to get a resolution on this. I rarely deal with these kinds of patches. It's too late for CR1.

**Comment by stuartwdouglas** [comment]
This should be resolved by my recent PR's to remove ClassIndex

**Comment by jamezp** [comment]
This should be resolved now. See https://issues.jboss.org/browse/WFLY-4835 for more details.

**Pull request closed without merging**
