### PR TITLE
[WFCORE-6326] Revert the removal of the org.jboss.vfs module on deplo…

### PR DESCRIPTION
**Pull request by jamezp**
…yments.

https://issues.redhat.com/browse/WFCORE-6326

### CODE REVIEW

**Comment by kabir** [comment]
@jamezp I'm totally unfamiliar with this, but since https://issues.redhat.com/browse/WFLY-17921 mentions RestEasy Spring deployments, I am curious if this could be added to the subsystem rather than server wide. 

Apart from that, it looks good

**Comment by jamezp** [comment]
> @jamezp I'm totally unfamiliar with this, but since https://issues.redhat.com/browse/WFLY-17921 mentions RestEasy Spring deployments, I am curious if this could be added to the subsystem rather than server wide.
> 
> Apart from that, it looks good

@kabir It could, but this affects all Spring deployments. My initial thought was to add it there because the test failures came up in the resteasy-spring project during an upgrade. However, when I looked into it seems it would affect any deployment using Spring.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@jamezp Can you send up a PR against 20.x as well? Thanks.

**Review by yersan — APPROVED** [review]
This need to be documented back in [WFLY-17841](https://issues.redhat.com/browse/WFLY-17841)

**Comment by jamezp** [comment]
Upstream PR #5476

**Pull request merged**
