### PR TITLE
[WFCORE-6664] Upgrade SLF4J from 2.0.9 to 2.0.11

### PR DESCRIPTION
**Pull request by yersan**
Jira issue: https://issues.redhat.com/browse/WFCORE-6664

### CODE REVIEW

**Review by jamezp — APPROVED** [review]
I think this is okay. There is one commit that is not backwards compatible, but it's on a utility that should not be used. See https://github.com/qos-ch/slf4j/commit/316b5d1727d647250ff791565650070094f5b85e and https://github.com/qos-ch/slf4j/issues/361

**Comment by yersan** [comment]
@jamezp thanks for looking at this. You are talking about the `Util.report()` method removal, isn't it? 

The class itself states that [it is an internal utility class](https://github.com/qos-ch/slf4j/blob/316b5d1727d647250ff791565650070094f5b85e/slf4j-api/src/main/java/org/slf4j/helpers/Util.java#L28C2-L28C30), so I think we are safe. The `slf4j-api` module is distributed in the modules directory, so potentially there could be application using it, but again, it states that it is an internal utility class, so if someone is using it, its usage should be removed.

**Comment by jamezp** [comment]
> @jamezp thanks for looking at this. You are talking about the `Util.report()` method removal, isn't it?
> 
> The class itself states that [it is an internal utility class](https://github.com/qos-ch/slf4j/blob/316b5d1727d647250ff791565650070094f5b85e/slf4j-api/src/main/java/org/slf4j/helpers/Util.java#L28C2-L28C30), so I think we are safe. The `slf4j-api` module is distributed in the modules directory, so potentially there could be user applications using it, but again, it states that it is an internal utility class, so if someone is using it, its usage should be removed. Looking at what the Report method does, its usage doesn't look useful.

@yersan Yes, that is what I was referring to. I think it's okay too, I just wanted to make sure to point out that we saw it and we think it's okay :)

**Comment by yersan** [comment]
Thanks @jamezp

**Pull request merged**
