### PR TITLE
[WFCORE-3685] switch_to_using_org.jboss.modules.ClassTransformer

### PR DESCRIPTION
**Pull request by xjusko**
fixes https://issues.redhat.com/browse/WFCORE-3685

### CODE REVIEW

**Comment by jmesnil** [comment]
@scottmarlow could you please review?

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
I think the follow up work is removing use of  java.lang.instrument.ClassFileTransformer in WildFly as mentioned in [WFLY-10025](https://issues.redhat.com/browse/WFLY-10025?focusedCommentId=13585254&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13585254)

```
cd wildfly
grep -rli java.lang.instrument.ClassFileTransformer  --include=*.java
jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/Hibernate51CompatibilityTransformer.java
jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPADelegatingClassFileTransformer.java
testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/transformer/DummyClassFileTransformer1.java
testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/transformer/DummyClassFileTransformer2.java
```

**Comment by xjusko** [comment]
This issue needs https://issues.redhat.com/browse/WFLY-15288 to pass full integration.

**Comment by scottmarlow** [comment]
jpa/hibernate-transformer/src/main/java/org/jboss/as/hibernate/Hibernate51CompatibilityTransformer.java is being removed via a separate WF pr.

**Comment by darranl** [comment]
@xjusko Can you please confirm the current status of this one?  We have a merge conflict as well that needs fixing - once fixed are we at a point to be reviewed again?

**Comment by xjusko** [comment]
I am working on it

**Comment by xjusko** [comment]
All tests passed on my machine.

**Review by yersan — COMMENTED** [review]
Hi @xjusko , there are two tasks to do for this PR:

1) It needs to be rebased on top of the latest wildfly-core/main (git rebase upstream/main your-topic-brach)
2) The changes introduced on this Jira requires also changes in the [WildFly project](https://github.com/wildfly/wildfly). All the Full Integration Jobs for this PR are going to fail because you also need to change WildFly and adapt it to the changes you are adding on wildfly-core. wildfly-core is just a component of wildfly (we usually name it as wildfly full), see for example the uses of `DelegatingClassFileTransformer` in WildFly Full: https://github.com/wildfly/wildfly/blob/8af5ca7a3ae7be97abfc8c9d409fb6dce29704be/jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/JPAClassFileTransformerProcessor.java#L59

Once you have rebased this PR, you can clone WildFly Full and built it by using the wildfly-core version that contains your changes. For example:

 `mvn clean install -DskipTests -Dversion.org.wildfly.core=[the wildfly-core-version that has your changes, e.g 19.0.0.Beta7-SNAPSHOT]`

Then you will need to modify WildFly accordingly and create a PR to address those changes. Once both PRs are in place, we can run the failed Jobs by using the topic branches on both repositories. If they pass, we will coordinate the integration of both changes.

**Comment by xjusko** [comment]
hi @yersan 
I rebased this branch on top of main and also rebased already created PR for the wildfly, which should be right here:
https://github.com/wildfly/wildfly/pull/14661
I also ran `mvn clean install -DallTests -Dversion.org.wildfly.core=19.0.0.Beta7-SNAPSHOT` on my wildflly branch and all tests passed.
If anything else is needed or I misunderstood something let me know.

**Comment by yersan** [comment]
Integration Jobs looks fine. 
Integration Jobs shows there are no test failures.

@jmesnil / @darranl This PR will require some coordination to be integrated on wildfly.

@xjusko would you mind rebasing both again on top of the main branches? both wildfly-core and wildfly topic branches. Thanks.

**Comment by yersan** [comment]
In addition @xjusko, we require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to these terms?

**Comment by xjusko** [comment]
> In addition @xjusko, we require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to these terms?

Of course I do, is there anything special I need to do to agree to these terms?

**Comment by yersan** [comment]
> Of course I do, is there anything special I need to do to agree to these terms?

Nothing special. Just what you did, confirm you have read them and you agree with the terms. That's all. Thanks.

**Pull request merged**
