### PR TITLE
[18.x][WFCORE-5530] Add encryption support to FilesystemSecurityRealm 

### PR DESCRIPTION
**Pull request by Ashpan**
https://issues.redhat.com/browse/WFCORE-5530
Upstream: https://github.com/wildfly/wildfly-core/pull/4983

### CODE REVIEW

**Comment by bstansberry** [comment]
@ashpan @fjuma This now has a merge conflict.

**Comment by Ashpan** [comment]
@bstansberry Fixed the merge conflict

**Comment by bstansberry** [comment]
Thanks @Ashpan. I expect we will integrate the needed WildFly Core release on Monday.

**Pull request merged**
