### PR TITLE
WFCORE-2617 Credential store flush failure creates inconsistency...

### PR DESCRIPTION
**Pull request by TomasHofman**
... between the the version on the filesystem and in the memory

https://issues.jboss.org/browse/WFCORE-2617
https://issues.jboss.org/browse/JBEAP-9989

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by TomasHofman** [comment]
retest this please

**Comment by bstansberry** [comment]
I asked for review from the elytron team.

**Comment by bstansberry** [comment]
This is going to need a rebase when I merge #2318 and I need to give that one precedence.

**Comment by TomasHofman** [comment]
PR rebased.

**Comment by bstansberry** [comment]
Custom builds while ci.wildfly.org is down:

http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=114024&
http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=114026&

**Comment by TomasHofman** [comment]
retest this please

**Comment by TomasHofman** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
