### PR TITLE
[WFCORE-5229] Update module descriptor v1.9. Adjust dependencies for jav…

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes [WFCORE-5229](https://issues.redhat.com/browse/WFCORE-5229)
Please find jdeps results attached to Jira issue.

### CODE REVIEW

**Review by ropalka — CHANGES_REQUESTED** [review]
Most recent version is 1.9 not 1.8

**Comment by ropalka** [comment]
Also migrate these modules:

core-feature-pack/common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/scripting/main/module.xml
core-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/interceptor/api/main/module.xml
core-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/security/auth/message/api/main/module.xml
core-feature-pack/ee-8-api/src/main/resources/modules/system/layers/base/javax/security/jacc/api/main/module.xml
core-feature-pack/galleon-common/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/wildfly-core/module.xml

**Comment by boris-unckel** [comment]
@ropalka I have upgrade all to 1.9 except the ones which use the system property:
core-feature-pack/common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/scripting/main/module.xml

**Review by jamezp — APPROVED** [review]

**Review by ropalka — CHANGES_REQUESTED** [review]
I still see a lot of 1.8 modules @boris-unckel : 
[wildfly-core/core-feature-pack]>grep -r "urn:jboss:module" * | grep -v "1.9"
common/src/main/resources/modules/system/layers/base/com/googlecode/javaewah/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="com.googlecode.javaewah">
common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml:<module xmlns="urn:jboss:module:1.6" name="ibm.jdk">
common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml:<module xmlns="urn:jboss:module:1.6" name="io.undertow.core">
common/src/main/resources/modules/system/layers/base/javax/api/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="javax.api">
common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="javax.sql.api">
common/src/main/resources/modules/system/layers/base/javax/xml/stream/api/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="javax.xml.stream.api">
common/src/main/resources/modules/system/layers/base/org/aesh/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.aesh">
common/src/main/resources/modules/system/layers/base/org/apache/httpcomponents/core/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.apache.httpcomponents.core">
common/src/main/resources/modules/system/layers/base/org/apache/sshd/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.apache.sshd">
common/src/main/resources/modules/system/layers/base/org/apache/xerces/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.apache.xerces">
common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.bouncycastle.bcpg">
common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.bouncycastle.bcpkix">
common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcprov/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.bouncycastle.bcprov">
common/src/main/resources/modules/system/layers/base/org/codehaus/woodstox/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.codehaus.woodstox">
common/src/main/resources/modules/system/layers/base/org/eclipse/jgit/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.eclipse.jgit">
common/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.cli">
common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.controller">
common/src/main/resources/modules/system/layers/base/org/jboss/as/core-security/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.core-security">
common/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.deployment-scanner">
common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.domain-http-interface">
common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-management/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.domain-management">
common/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.host-controller">
common/src/main/resources/modules/system/layers/base/org/jboss/as/jmx/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.jmx">
common/src/main/resources/modules/system/layers/base/org/jboss/as/logging/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.logging">
common/src/main/resources/modules/system/layers/base/org/jboss/as/network/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.network">
common/src/main/resources/modules/system/layers/base/org/jboss/as/patching/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.patching">
common/src/main/resources/modules/system/layers/base/org/jboss/as/platform-mbean/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.platform-mbean">
common/src/main/resources/modules/system/layers/base/org/jboss/as/process-controller/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.process-controller">
common/src/main/resources/modules/system/layers/base/org/jboss/as/protocol/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.protocol">
common/src/main/resources/modules/system/layers/base/org/jboss/as/remoting/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.remoting">
common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.server">
common/src/main/resources/modules/system/layers/base/org/jboss/classfilewriter/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.classfilewriter">
common/src/main/resources/modules/system/layers/base/org/jboss/log4j/logmanager/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.log4j.logmanager">
common/src/main/resources/modules/system/layers/base/org/jboss/logmanager/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.logmanager">
common/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.marshalling">
common/src/main/resources/modules/system/layers/base/org/jboss/marshalling/river/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.marshalling.river">
common/src/main/resources/modules/system/layers/base/org/jboss/msc/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.msc">
common/src/main/resources/modules/system/layers/base/org/jboss/remoting-jmx/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.remoting-jmx">
common/src/main/resources/modules/system/layers/base/org/jboss/remoting/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.remoting">
common/src/main/resources/modules/system/layers/base/org/jboss/threads/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.threads">
common/src/main/resources/modules/system/layers/base/org/jboss/xnio/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.xnio">
common/src/main/resources/modules/system/layers/base/org/jboss/xnio/nio/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.jboss.xnio.nio">
common/src/main/resources/modules/system/layers/base/org/projectodd/vdx/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.projectodd.vdx">
common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.bootable-jar">
common/src/main/resources/modules/system/layers/base/org/wildfly/client/config/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.client.config">
common/src/main/resources/modules/system/layers/base/org/wildfly/common/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.common">
common/src/main/resources/modules/system/layers/base/org/wildfly/discovery/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.discovery">
common/src/main/resources/modules/system/layers/base/org/wildfly/event/logger/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.event.logger">
common/src/main/resources/modules/system/layers/base/org/wildfly/extension/core-management/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.extension.core-management">
common/src/main/resources/modules/system/layers/base/org/wildfly/extension/discovery/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.extension.discovery">
common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.extension.elytron">
common/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.extension.io">
common/src/main/resources/modules/system/layers/base/org/wildfly/extension/request-controller/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.extension.request-controller">
common/src/main/resources/modules/system/layers/base/org/wildfly/extension/security/manager/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.extension.security.manager">
common/src/main/resources/modules/system/layers/base/org/wildfly/openssl/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.openssl">
common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.security.elytron-private">
common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-web/undertow-server/main/module.xml:<module xmlns="urn:jboss:module:1.8" name="org.wildfly.security.elytron-web.undertow-server">
common/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml:<module xmlns="urn:jboss:module:1.6" name="sun.jdk">
common/src/main/resources/modules/system/layers/base/sun/scripting/main/module.xml:<module xmlns="urn:jboss:module:1.6" name="sun.scripting">

**Review by ropalka — APPROVED** [review]
LGTM

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @boris-unckel

**Pull request merged**
