### PR TITLE
[WFCORE-6040] Update MappersTestCase to use assertNull where appropriate

### PR DESCRIPTION
**Pull request by anilabhabaral**
Issue Link: https://issues.redhat.com/browse/WFCORE-6040

### CODE REVIEW

**Comment by yersan** [comment]
Hi @anilabhabaral , you can safely ignore the Integration Jobs failures, they will be gone after getting https://issues.redhat.com/browse/WFLY-17018 merged.

**Comment by anilabhabaral** [comment]
Hi @yersan thank you! Is this PR good to merge ?

**Comment by yersan** [comment]
Hi @anilabhabaral , We have to wait for CI, it looks good, but we have to wait for it. Once CI passes, someone will review it and approve it accordingly. Don't worry about the current failures, I'll restart the Jobs when we are ready for them. Thanks for your contributions.

**Comment by anilabhabaral** [comment]
Thank you @yersan

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
Hi @anilabhabaral, looks good to be merged, thanks!

This is your first contribution to this open source project, we require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. 

Do you agree to these terms?

**Comment by anilabhabaral** [comment]
@yersan Yes Agreed.

**Comment by yersan** [comment]
@anilabhabaral merged, thank you for the contribution!

**Comment by anilabhabaral** [comment]
Thank you @yersan

**Pull request merged**
