### PR TITLE
Make ManagementResourceRegistration#registerCapabilty take RuntimeCap…

### PR DESCRIPTION
**Pull request by ctomc**
…ability

### CODE REVIEW

**Comment by kabir** [comment]
I'll let Brian approve this. For us normal mortals, some Jira references would help explaining what is going on :-)

**Comment by ctomc** [comment]
@kabir of course it was asked for by Brian after some discussion on hipchat.

**Comment by ctomc** [comment]
unrelated, but still retest this please

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
