### PR TITLE
Undertow 1.2.8.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by bstansberry** [comment]
#797 is for master, moving to 1.3.0.Beta1

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I keep testing this, along with 780 and 811, on 1.x-ignore and keep seeing that EJBSignEncryptTestCase failure. So I'm being cautious.

**Comment by stuartwdouglas** [comment]
I will investigate

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
EJBSignEncryptTestCase seems to be failing consistently in other PR's as well. I don't think this is undertow related

**Comment by stuartwdouglas** [comment]
Retest this please

**Pull request merged**
