### PR TITLE
WFCORE-3648 Options --disabled/--enabled/--replace are missing in CLI code completion

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFCORE-3648

The problem is that activators are establishing expected attributes to be present and passing empty String value (`DependOptionActivator.ARGUMENT_NAME`).

Also, cleans up unnecessary modifiers.

### CODE REVIEW

**Comment by rhusar** [comment]
cc @jfdenise

**Comment by jfdenise** [comment]
@rhusar, this is done in purpose, enabled and disabled are not proposed in domain mode.

**Comment by rhusar** [comment]
@jfdenise Please look again, you seem to be confusing the lines with these which are intact:

https://github.com/wildfly/wildfly-core/pull/3141/files#diff-4951a4ca5479737edcea023bef26b67fR147
https://github.com/wildfly/wildfly-core/pull/3141/files#diff-4951a4ca5479737edcea023bef26b67fR176

After the fix, these still do not appear in domain mode as expected.

**Comment by jfdenise** [comment]
I see, so the behavior is expected, in standalone, --enabled and --disabled depend on the Argument (the file path) to be present to be proposed.

**Comment by rhusar** [comment]
So if I understand you correctly, you do not want to present the options until the file path is specified?
I don't see how that makes sense. The file path is required (org.jboss.as.cli.impl.aesh.cmd.deployment.DeployFileCommand#file) so there will always be a file specified for the command to be valid. This there is no reason not to propose those options "dependending on file path to be present". Options are typically proposed right after typing the command, then followed by argument.

**Comment by jfdenise** [comment]
When pressing <TAB> the file path completer will be called first so you will be asked for a file (displaying the lists of file present in the current directory), once you selected a file, the options will be proposed. So you will see --enabled --disabled at the right time.

**Comment by rhusar** [comment]
Unfortunately you are making a wrong assumption that users will always want to type "deployment deploy-file FILE_PATH --disabled" in that exact order. The other way around is perfectly fine "deployment deploy-file --disabled FILE_PATH". The file path completer does not kick in after the typing the first hyphen-minus character is input, e.g. 
```
[standalone@localhost:9990 /] deployment deploy-file --
--headers=  --name=  --runtime-name=  --unmanaged
```
which is correct, but missing all the possible options. This PR fixes that.

**Comment by jfdenise** [comment]
@rhusar , good point! Approved.
JF

**Comment by rhusar** [comment]
@jfdenise Great, thanks. Note that I stumbled upon this when trying to look into https://issues.jboss.org/browse/WFCORE-3649

**Comment by jfdenise** [comment]
@rhusar, I just looked into WFCORE-3649, yes, tha tis caused by the legacy deploy command calling into the new deployment command. The name of the option needs to be passed down, --replace is the new name of --force.

**Pull request merged**
