### PR TITLE
[WFCORE-3433] Register patching child resources in registerChildren

### PR DESCRIPTION
**Pull request by bstansberry**
This also reduces visibility on a bunch of members of this class just as a cleanup.

https://issues.jboss.org/browse/WFCORE-3433

This is the first commit in #2956 but since that one may take some time to review while this is just a minor cleanup, I went ahead and filed a separate PR.

### CODE REVIEW

**Comment by bstansberry** [comment]
@aloubyansky please review

**Comment by jmesnil** [comment]
This PR needs to be rebased.

**Comment by bstansberry** [comment]
@jmesnil rebased

**Comment by jmesnil** [comment]
@bstansberry compilation errors are related to the PR:

> EXCLUDE_AGEDOUT has private access in org.jboss.as.patching.management.PatchResourceDefinition

**Comment by bstansberry** [comment]
sigh :) Sorry Jeff.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by aloubyansky** [comment]
The changes look good to me, thanks.

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
