### PR TITLE
WFLY-5645 - Use script name for file related to Wildfly to allow multiple instances easily

### PR DESCRIPTION
**Pull request by rpelisse**
Note that this issue also related to the [BZ1265740](https://bugzilla.redhat.com/show_bug.cgi?id=1265740)

### CODE REVIEW

**Comment by ctomc** [comment]
:+1:

**Comment by ckyriakidou** [comment]
+1

**Comment by rpelisse** [comment]
Two +1 and no issues with build ? Oh come on this PR needs to be accepted ;) !

**Comment by bstansberry** [comment]
This is fine; it will get merged when we start merging changes for 3.x.

**Pull request merged**
