### PR TITLE
[WFCORE-5839][primary/secondary] Find and replace occurrences used by…

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/WFCORE-5839

### CODE REVIEW

**Review by yersan — CHANGES_REQUESTED** [review]
@moulalis I would say you also have to include here the changes of this file: https://github.com/wildfly/wildfly-core/blob/a3309bd1ce8b267fcef965c69b4ec2412f2e0fda/domain-management/src/main/resources/org/jboss/as/domain/management/_private/LocalDescriptions.properties

@bstansberry allow me to defer the review of this one to you.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @moulalis

**Pull request merged**
