### PR TITLE
[WFCORE-4754] Add version 10 of the WildFly Elytron subsystem schema and model

### PR DESCRIPTION
**Pull request by fjuma**
This is for WildFly Core 12.

https://issues.jboss.org/browse/WFCORE-4754

This will need to be updated once feature development for WildFly Core 11 is finished. However, I am creating this PR now so that engineers already working on new security features for WildFly 20 can make use of this.

### CODE REVIEW

**Comment by darranl** [comment]
I suspect this may be ready to merge (not rebase) master onto this topic branch as we have merged the web services PR which affected the management model.

**Comment by fjuma** [comment]
I have now merged master onto this topic branch.

**Comment by darranl** [comment]
@fjuma now we are passed the feature freeze is it time to merge in master again and make sure any changes are replicated in the bump?

**Comment by jmesnil** [comment]
@fjuma I've reopened WildFly Core master branch for features (for WildFly 20). I've triggered the CI jobs fro this PR.

Assuming they pass, can I merge the PR or is there any outstanding work required for it?

**Comment by fjuma** [comment]
@jmesnil This PR is ready to be merged once CI passes. Thanks!

**Comment by nekdozjam** [comment]
@jmesnil @fjuma can any of you ping me when this gets merged? Thanks.

**Comment by jmesnil** [comment]
@fjuma thanks.
@nekdozjam this is merged

**Pull request merged**
