### PR TITLE
[WFCORE-6307] Management schema version bump.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-6307

### CODE REVIEW

**Comment by bstansberry** [comment]
@darranl Draft?

**Comment by darranl** [comment]
@bstansberry just to make sure we have a PR that builds on it ready so it does not become a redundant bump.

**Comment by darranl** [comment]
I am removing the 21.0.0.Beta1 label as we did not continue with the work that needed the bump in time for Beta1

**Comment by darranl** [comment]
@yersan it can, but not sure if we have anything to use it yet.

**Comment by yersan** [comment]
@darranl ok, got it, we need at least to bump the Kernel API version, that can be done in a separated PR

**Comment by darranl** [comment]
Still active, will rebase

**Pull request closed without merging**
