### PR TITLE
Revert of WFCORE-1487, implies fix of WFCORE-1682

### PR DESCRIPTION
**Pull request by jfdenise**
Nasty regressions have been found in completion and execution of CLI commands. Better to revert this enhancement and design a solution to help users when an argument has no completer nor name.

### CODE REVIEW

**Comment by aloubyansky** [comment]
It's been discussed. Good to merge. Thanks.

**Comment by jamezp** [comment]
@jfdenise @aloubyansky I assume this should also be reverted in Core 2.x as well correct?

**Comment by aloubyansky** [comment]
Yes, wherever it's been merged to. Thanks!

**Comment by jamezp** [comment]
Perfect, thanks! Here's the 2.x revert PR https://github.com/wildfly/wildfly-core/pull/1726.

**Comment by jamezp** [comment]
retest this please

**Pull request merged**
