### PR TITLE
[WFCORE-3432] Correct issues with ManagementResourceRegistrations not reporting as runtime-only

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.jboss.org/browse/WFCORE-3432

### CODE REVIEW

**Comment by jmesnil** [comment]
@bstansberry Compilation errors are related to the PR:

> EXCLUDE_AGEDOUT has private access in org.jboss.as.patching.management.PatchResourceDefinition

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by bstansberry** [comment]
I filed https://issues.jboss.org/browse/WFCORE-3759 for the "Linux (Pull Request)" job failure, which was a hang.

**Comment by bstansberry** [comment]
@jmesnil Fixed.

**Pull request merged**
