### PR TITLE
[WFCORE-3024] - SecurityDomain is lost when setting up remote outbound connections

### PR DESCRIPTION
**Pull request by pedroigor**
### References

* https://issues.jboss.org/browse/WFCORE-3024
* https://issues.jboss.org/browse/JBEAP-11377

### CODE REVIEW

**Comment by bstansberry** [comment]
It looked good to me before I noticed the failing tests!

**Comment by dmlloyd** [comment]
The change seems OK but there are test failures.

**Comment by dmlloyd** [comment]
Probably needs to be coordinated with https://github.com/wildfly/wildfly/pull/10256

**Comment by pedroigor** [comment]
+1. I think that may be the cause.

**Comment by pedroigor** [comment]
FYI, I found the issue. The failing tests are related with scenarios where client configuration in deployment is supposed to be discarded in favor of server configuration. I need to check with QE if the test is really correct or if is considering some wrong behavior fixed by this issue.

**Comment by pedroigor** [comment]
After investigating the failing tests, I've found that my previous changes were not handling properly some scenarios with legacy configuration. The issues were related with using a default authentication context when a connector is not configured explicitly with one.

**Pull request merged**
