### PR TITLE
WFCORE-725 Remove ClassIndex and DeploymentClassIndex

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Requires https://github.com/wildfly/wildfly/pull/7662 to be merged first

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Here's the failure in full:

```

[20:07:46][Step 4/5] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wildfly-ejb3: Compilation failure: Compilation failure:
[20:07:46][Step 4/5] [ERROR] /opt/buildAgent/work/db872761b443af46/full/ejb3/src/main/java/org/jboss/as/ejb3/component/stateless/StatelessComponentDescription.java:[185,37] type org.jboss.as.server.deployment.reflect.ClassReflectionIndex does not take parameters
[20:07:46][Step 4/5] [ERROR] /opt/buildAgent/work/db872761b443af46/full/ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulComponentDescription.java:[278,37] type org.jboss.as.server.deployment.reflect.ClassReflectionIndex does not take parameters
[20:07:46][Step 4/5] [ERROR] /opt/buildAgent/work/db872761b443af46/full/ejb3/src/main/java/org/jboss/as/ejb3/deployment/processors/merging/SessionSynchronizationMergingProcessor.java:[99,39] type org.jboss.as.server.deployment.reflect.ClassReflectionIndex does not take parameters
[20:07:46][Step 4/5] [ERROR] /opt/buildAgent/work/db872761b443af46/full/ejb3/src/main/java/org/jboss/as/ejb3/component/singleton/SingletonComponentDescription.java:[225,37] type org.jboss.as.server.deployment.reflect.ClassReflectionIndex does not take parameters
[20:07:46][Step 4/5] [ERROR] -> [Help 1]
```

**Comment by stuartwdouglas** [comment]
I missed something in my original PR: https://github.com/wildfly/wildfly/pull/7725

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Downstream still has problems:

```

[22:05:27][Step 4/5] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wildfly-pojo: Compilation failure
[22:05:27][Step 4/5] [ERROR] /opt/buildAgent/work/db872761b443af46/full/pojo/src/main/java/org/jboss/as/pojo/service/DefaultBeanInfo.java:[102,76] incompatible types: java.util.Collection<java.lang.reflect.Constructor<?>> cannot be converted to java.util.Collection<java.lang.reflect.Constructor>
```

**Comment by bstansberry** [comment]
retest this please

**Comment by jamezp** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Retest this please

**Pull request merged**
