### PR TITLE
Add option to prevent manual mode tests to automaticly run server

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by jamezp** [comment]
I'm still voting we just get rid of the `@ServerControl` annotation. It's only used in manual mode tests and they all have to override the default value for the annotation. The annotation does nothing if the `manual` attribute is set to `false` which is the default. Having the annotation and a system property just doesn't make much sense to me.

**Comment by ctomc** [comment]
@stuartwdouglas wdyt about this?

**Comment by stuartwdouglas** [comment]
I am fine with getting rid of the annotation. Manual and automatic tests should not be in the same maven module anyway

**Comment by ctomc** [comment]
will rework this to have system property to control in what way servers are started, manual or automatic.

**Pull request closed without merging**
