### PR TITLE
[WFCORE-1642]: Test development

### PR DESCRIPTION
**Pull request by istraka**
Analysis document: https://polarion.engineering.redhat.com/polarion/#/project/EAP7/wiki/RFEs_7_1/EAP7-575
EAP7 issue: https://issues.jboss.org/browse/EAP7-575

### CODE REVIEW

**Comment by bstansberry** [comment]
Can the commit message here refer to WFCORE-1642? EAP7-575 is not a publicly accessible issue.

**Comment by bstansberry** [comment]
@ehsavoie please review

**Comment by istraka** [comment]
@bstansberry fixed. I have also changed title of the PR.

**Comment by bstansberry** [comment]
Thanks, @istraka

**Comment by ehsavoie** [comment]
:+1:

**Pull request merged**
