### PR TITLE
add test for WFCORE-544 inconsistent system property handling

### PR DESCRIPTION
**Pull request by hsvabek**
Test for https://issues.jboss.org/browse/WFCORE-544
https://bugzilla.redhat.com/show_bug.cgi?id=1192467

### CODE REVIEW

**Comment by bstansberry** [comment]
this is ok to test

**Comment by hsvabek** [comment]
retest please

**Comment by hsvabek** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Failed again.

**Comment by hsvabek** [comment]
Our team will create new pull request with simplified test.

**Pull request closed without merging**
