### PR TITLE
[WFCORE-1110] Tests for configuring custom headers

### PR DESCRIPTION
**Pull request by tterem**
Jira: https://issues.redhat.com/browse/WFCORE-1110

### CODE REVIEW

**Comment by marekkopecky** [comment]
@jamezp   ^^^

**Comment by jmesnil** [comment]
This is ok to test.

**Comment by tterem** [comment]
There was a test failure but I believe it wasn't caused by my tests.

**Comment by jmesnil** [comment]
@tterem thanks

**Pull request merged**
