### PR TITLE
Add mixed domain host excludes for WF 10.0 and 10.1

### PR DESCRIPTION
**Pull request by bstansberry**

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I removed the 'hold' label as I see no negative effects in the testsuite.

**Comment by ctomc** [comment]
Why is this needed? mixed-domain tests only check EAP releases not intermittent WildFly ones....

**Comment by luck3y** [comment]
This will be needed for just using core & old slaves, when we figure out how to add elytron to the core feature pack.

**Pull request merged**
