### PR TITLE
[WFCORE-6547] Upgrading JBoss Marshalling to 2.1.3.SP1

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-6547

### CODE REVIEW

**Comment by yersan** [comment]
The integration Jobs needs https://github.com/wildfly/wildfly/pull/17197 before proceeding with this.

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
@ropalka I think this deserves a backport to `22.x`, what do you think?

**Comment by ropalka** [comment]
Yes, I think so @yersan .

**Comment by yersan** [comment]
Thank you @ropalka

**Pull request merged**
