### PR TITLE
[JBEAP-13122] Duplicate record is written in property file when group…

### PR DESCRIPTION
**Pull request by xstefank**
… name set to empty

https://issues.jboss.org/browse/JBEAP-13122

Upstream: https://issues.jboss.org/browse/WFCORE-3282
Upstream PR: https://github.com/wildfly/wildfly-core/pull/3009

### CODE REVIEW

**Comment by darranl** [comment]
This will need an associated upstream PR as well.  The upstream PR should only reference the WFCORE issue in the commit and pull request title.

**Comment by xstefank** [comment]
@darranl Upstream PR: https://github.com/wildfly/wildfly-core/pull/3009 , sorry if it wasn't visible in the PR description

**Comment by bstansberry** [comment]
The upstream 3.x branch is not where JBEAPs are fixed for CPs.

**Comment by xstefank** [comment]
sorry, my misunderstanding of the included version

**Pull request closed without merging**
