### PR TITLE
[WFCORE-6568] - Modify description in elytron subsystem 

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Modify description in elytron of subsystem to its correct sentence.

https://issues.redhat.com/browse/WFCORE-6568

### CODE REVIEW

**Comment by yersan** [comment]
Hello @gabrielpadilh4. Since this issue affects WildFly Core I've just moved it from WildFly. Consequently, the Jira number has changed, would you mind changing the commit message to include the new Jira ([WFCORE-6568](https://issues.redhat.com/browse/WFCORE-6568)) and remove the obsolete one (WFLY-16896)? Thanks!

**Comment by gabrielpadilh4** [comment]
Hello @yersan i changed the commit message. Thank you.

**Review by yersan — APPROVED** [review]
LGTM

**Comment by gabrielpadilh4** [comment]
Hello @yersan i can't see why the job failed at team city, can you please review ?

**Comment by yersan** [comment]
It was an execution timeout, so I kicked it off again, in any case, you can forget about the CI; your changes are harmless and unexpected to affect the testsuite.

**Comment by yersan** [comment]
Thanks @gabrielpadilh4

**Pull request merged**
