### PR TITLE
[WFCORE-1118] Upgrade to WildFly Elytron 1.0.2.Final

### PR DESCRIPTION
**Pull request by darranl**
https://issues.jboss.org/browse/WFCORE-1118
https://issues.jboss.org/browse/ELY-354
https://issues.jboss.org/browse/JBEAP-714

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

failure is unrelated: https://issues.jboss.org/browse/WFCORE-1074

**Comment by n1hility** [comment]
retest this please

**Comment by darranl** [comment]
retest this please

And please use a VM with a JVM installed ;-)

**Comment by n1hility** [comment]
@ctomc ^

**Comment by ctomc** [comment]
Agent was fixed earlier today

**Pull request merged**
