### PR TITLE
[WFCORE-1357] Drop javax.sql.api artifact in anticipation of using th…

### PR DESCRIPTION
**Pull request by dmlloyd**
…e JDK javax.transaction.xa package

### CODE REVIEW

**Comment by dmlloyd** [comment]
It looks like ```org.wildfly.build.util.ModuleParser#parseResources()``` isn't consuming the content of the ```<artifact>``` element, which probably causes all the deps to get messed up.

**Comment by dmlloyd** [comment]
Depends on https://github.com/wildfly/wildfly-core/pull/1414

**Comment by dmlloyd** [comment]
Retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
this actually passed

**Pull request merged**
