### PR TITLE
[WFCORE-5889] Upgrade Apache johnzon to 1.2.17

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFCORE-5889

### CODE REVIEW

**Comment by boris-unckel** [comment]
@ehsavoie Could you review and approve, please? All links are in the Jira.

**Review by ehsavoie — APPROVED** [review]

**Comment by yersan** [comment]
Added hold label since @jamezp's intention is to remove Apache johnzon here: https://github.com/wildfly/wildfly-core/pull/5052

**Comment by yersan** [comment]
Added hold label since @jamezp's intention is to remove Apache johnzon here: https://github.com/wildfly/wildfly-core/pull/5052

**Comment by jamezp** [comment]
I do think we should remove Johnzon. It looks like #5052 is passing now. It required changes that have been merged into full.

**Comment by yersan** [comment]
> Sorry, I only scanned for component upgrade Jiras/PRs before providing this.

Thanks anyway @boris-unckel

**Pull request closed without merging**
