### PR TITLE
[WFCORE-1133] JDK 1.8 on Mac causes javax.script.ScriptEngineFactory:…

### PR DESCRIPTION
**Pull request by jaysensharma**
… Provider apple.applescript.AppleScriptEngineFactory not found

https://issues.jboss.org/browse/WFCORE-1133

### CODE REVIEW

**Comment by jaysensharma** [comment]
retest this please

**Comment by bstansberry** [comment]
@stuartwdouglas @n1hility You guys are probably the best fit to both review this one and schedule the fix.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Thanks!

**Pull request merged**
