### PR TITLE
[WFLY-5498] Upgrade commons-io to 2.10.0

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFCORE-5498

### CODE REVIEW

**Comment by jmesnil** [comment]
The failures look related to the commons.io upgrade (they fail when calling `org.apache.commons.io.FileUtils.forceDelete`)

**Comment by bstansberry** [comment]
@jmesnil Yes, this is why we haven't been upgrading commons-io. I wanted to see if this latest release would have fixed this problem; seems not. But there's a valid need to upgrade in WildFly for production code (https://github.com/wildfly/wildfly/pull/14411) so we'll have to evaluate there whether we care about this behavior change, and either not upgrade anywhere, or just there, or change this test and upgrade here as well. In core it's just a test dep.

**Comment by jmesnil** [comment]
at first glance, it seems commons-io 2.10.0 does not properly handle weird symlinks (that are specific to these tests).

Since we use common-io with the `<scope> test</scope>`, I think we can provide an alternative to correctly delete directories created by the tests and unblock the upgrade in wildfly full.

**Comment by boris-unckel** [comment]
The situation has not change since 2.8.0: It depends on the filesystem: [https://github.com/wildfly/wildfly-core/pull/4400#issuecomment-770276813](https://github.com/wildfly/wildfly-core/pull/4400#issuecomment-770276813) You can check the dir with lsattr

**Comment by gaol** [comment]
> Since we use common-io with the `<scope> test</scope>`, I think we can provide an alternative to correctly delete directories created by the tests and unblock the upgrade in wildfly full.

Agreed, I can take a look on fixing the tests

**Comment by jmesnil** [comment]
this is superseded by #4653

**Pull request closed without merging**
