### PR TITLE
[WFCORE-587] Wildfly does not log stack trace of an exception

### PR DESCRIPTION
**Pull request by TomasHofman**
Issue: https://issues.jboss.org/browse/WFCORE-587

### CODE REVIEW

**Comment by bstansberry** [comment]
This doesn't fix the problem (the "report" method doesn't log anything) and it unnecessarily rearranges imports to not follow the WildFly standard.

**Comment by dmlloyd** [comment]
This fix is completely wrong anyway.  If you want the stack trace to be logged, just add ``@Cause`` to tge exception parameter and drop the corresponding part from the format string.

**Comment by bstansberry** [comment]
I don't want the stack trace in the output to report(...) though. That's an out-of-band message theoretically back to the client, which currently goes nowhere. I don't want to be sending server side stack traces to the client.

There just needs to be a new log method to log this.

**Comment by TomasHofman** [comment]
OK, I will direct it into log instead. Thanks for comments!

**Comment by TomasHofman** [comment]
So I left the original report message without change but also logged it with a stack trace.

**Pull request merged**
