### PR TITLE
[WFCORE-1297] deploy --url command creates invalid deployment

### PR DESCRIPTION
**Pull request by dpospisil**
JIRA: https://issues.jboss.org/browse/WFCORE-1297

### CODE REVIEW

**Comment by aloubyansky** [comment]
This looks good to me. As to your question (from the email) about whether to leave only the last part of the URL, i.e. the file name, let's also @stuartwdouglas for an opinion.

**Comment by dpospisil** [comment]
I think that the argument Martin commented in the JIRA makes sense. We use only last part of the file name so we should do the same with URLs. If @aloubyansky @stuartwdouglas are fine with that I update the PR accordingly.

**Comment by aloubyansky** [comment]
I'm fine with that. Although, that'll be a backward incompatible change.

**Comment by dpospisil** [comment]
OK, I have change it to use it only last part which I believe is better and you are saying you are fine with. Incompatibility (changing the deployment name) seems to be required anyway.

**Pull request merged**
