### PR TITLE
[WFCORE-5875] Migrated the log manager off javax.json.api to the internal module.

### PR DESCRIPTION
**Pull request by jamezp**
Includes the removal of Apache Geronimo JSON and Apache Johnzon. These do not seem to work well because the use the TCCL quite heavily requiring the `internal.javax.json.api.ee8` to be forced to be leaked. Using the `org.glassfish:jakarta.json` implementation makes this easier as it includes both the API and implementation in the artifact. In WildFly we will be migrating to Eclipse Parsson for the implementation so this will not be a conflict.

* https://issues.redhat.com/browse/WFCORE-5875
* https://issues.redhat.com/browse/WFCORE-5876

### CODE REVIEW

**Comment by jamezp** [comment]
This passes for me locally. The failures seem to be an issue with TeamCity that @luck3y is looking at.

**Comment by luck3y** [comment]
@jamezp I still need to update these jobs, should be done later today.

**Review by yersan — APPROVED** [review]

**Pull request merged**
