### PR TITLE
[WFCORE-3705] Cleanup: move to undeprecated modules

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Failures seem related.  I can't reproduce them locally yet though; still working on that.

**Comment by dmlloyd** [comment]
Ah, it only fails on Java 8.  OK, now to fix...

**Comment by dmlloyd** [comment]
All fixed.

**Comment by rsvoboda** [comment]
`<module name="jdk.unsupported"/>` on several places brings some uncomfortable feelings.

http://openjdk.java.net/jeps/260 is not saying how long the module will be available. @dmlloyd are you aware of future plans for It? I hope we would be safe with it for Java 11. After that some drops could happen I guess.

**Comment by dmlloyd** [comment]
The ``jdk.unsupported`` module will be around until the ``Unsafe`` API has been replaced by a new, as-yet undetermined API for serialization.

**Comment by dmlloyd** [comment]
@jmesnil done; I've split the commit.

**Pull request merged**
