### PR TITLE
[WFCORE-5225] Bump the Elytron subsystem and schema versions to 13.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-5225

Just placed on hold whilst we double check if any feature development will be included in this release but as we are past the last feature freeze engineers are getting their topic branches updated for the next round so need a common base.

### CODE REVIEW

**Review by fjuma — APPROVED** [review]

**Comment by jmesnil** [comment]
@darranl I don't think the Keystore failures on Windows are related to the version bump but do you think we could solve these failures before it?

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
@darranl thanks

**Comment by fjuma** [comment]
@darranl @jmesnil At the moment, no RFEs with Elytron subsystem changes have been pre-checked for WildFly 23. Just noticed this PR initially had the hold label but was later removed. We may need to revert this subsystem bump later this week if no RFEs become pre-checked in time.

**Comment by darranl** [comment]
@fjuma I think we are Ok for now as we are planning to have an RFE come in next week that will affect the subsystem.

**Comment by fjuma** [comment]
@darranl Ok, thanks.

**Pull request merged**
