### PR TITLE
[WFCORE-4736] Vault system property security attribute value is revealed on CLI 'reload' command

### PR DESCRIPTION
**Pull request by rmartinc**
Issue: https://issues.redhat.com/browse/WFCORE-4736

Fix for WFCORE-4736.

### CODE REVIEW

**Comment by rmartinc** [comment]
@darranl This was a security issue fixed in JBEAP-17870, now that 7.2.CP6 is out it can be moved to upstream. There is no community issue for this.

**Comment by rmartinc** [comment]
Done!

**Comment by bstansberry** [comment]
this is ok to test

**Comment by jmesnil** [comment]
@rmartinc thanks

**Pull request merged**
