### PR TITLE
[WFCORE-3527] OSGi cleanup

### PR DESCRIPTION
**Pull request by ropalka**

### CODE REVIEW

**Comment by bstansberry** [comment]
@stuartwdouglas wdyt about this one?  Ripping out some undeprecated public API in Attachments and DeploymentUtil is a tiny red flag, but in reality I figure no one is using this stuff.  If it wouldn't work anymore anyway (possible if it's never called) then there isn't even a tiny red flag.

**Comment by ropalka** [comment]
@bstansberry @stuartwdouglas I just sent PR to wildfly-camel to address binary compatibility problem

**Comment by bstansberry** [comment]
In that case I'm going to revert this.

**Comment by bstansberry** [comment]
@ropalka Since it's 3 commits it's too much work for me to revert and I guess since the branch is deleted the normal button on this page to revert is gone. Please send a revert PR that eliminates the breakage.

**Comment by ropalka** [comment]
Here is it @bstansberry https://github.com/wildfly/wildfly-core/pull/3060

**Pull request merged**
