### PR TITLE
[WFCORE-4841] Fix the capabilities for the logging subsystem. 

### PR DESCRIPTION
**Pull request by jamezp**
[WFCORE-4841] Fix the capabilities for the logging subsystem. Removed the previously unneeded recorder for filters. Moved the tests to the manual mode test suite as a result of WFCORE-4846.
    
 https://issues.redhat.com/browse/WFCORE-4841

The first commit adds the ability to run tests like the `RunsWith(Parameterized.class)`. This can definitely be removed if we don't want this. I can just change the tests.

The second commit adds a `ModuleBuilder` for creating test modules. It's somewhat similar to the `TestModule`, however it didn't quite work right for my use case and a refactor seemed a bit much. Again this can be removed if we don't want it.

### CODE REVIEW

**Comment by jamezp** [comment]
The error seems legitimate and I'll have to dig in to find where in the configuration it seems to be wrong.

**Comment by jamezp** [comment]
This requires https://github.com/wildfly/wildfly/pull/12991 to be merged first.

**Comment by jamezp** [comment]
retest this please

**Comment by jmesnil** [comment]
@jamezp thanks

**Pull request merged**
