### PR TITLE
[WFCORE-758] Use OpenJDK javax.sql with RowSet API and implementation

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by bstansberry** [comment]
This fails on the 1.x-ignore integration job:

http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=57095&tab=buildResultsDiv&buildTypeId=WF_WildFlyCore1xMasterIgnoreIntegration

```
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] Tests run: 16, Failures: 0, Errors: 16, Skipped: 0, Time elapsed: 0.518 sec <<< FAILURE! - in org.jboss.as.test.smoke.mgmt.datasource.DataSourceOperationsUnitTestCase
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] testMarshallUnmarshallXaDs(org.jboss.as.test.smoke.mgmt.datasource.DataSourceOperationsUnitTestCase)  Time elapsed: 0.02 sec  <<< ERROR!
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] org.jboss.as.test.integration.management.util.MgmtOperationException: Management operation failed: "WFLYCTL0158: Operation handler failed: java.lang.UnsupportedClassVersionError: javax/sql/DataSource : Unsupported major.minor version 52.0"
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] 	at org.jboss.as.test.integration.management.ManagementOperations.executeOperation(ManagementOperations.java:67)
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] 	at org.jboss.as.test.integration.management.ManagementOperations.executeOperation(ManagementOperations.java:37)
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] 	at org.jboss.as.test.integration.management.base.AbstractMgmtTestBase.executeOperation(AbstractMgmtTestBase.java:80)
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] 	at org.jboss.as.test.integration.management.base.AbstractMgmtTestBase.executeOperation(AbstractMgmtTestBase.java:92)
[02:45:58][org.wildfly:wildfly-ts-integ-smoke] 	at org.jboss.as.test.smoke.mgmt.datasource.DataSourceOperationsUnitTestCase.testMarshallUnmarshallXaDs(DataSourceOperationsUnitTestCase.java:364)
```

That job uses JDK 7; the Core Full Integration job run by the pull player uses JDK 8.

**Comment by dmlloyd** [comment]
Ah.  Well, that sucks.  I'll look into whether I can easily pull the 7.x code in for this branch.

**Comment by dmlloyd** [comment]
OK should be ready to go pending OK test.

**Comment by bstansberry** [comment]
http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=57509&tab=buildResultsDiv&buildTypeId=WF_WildFlyCore1xMasterIgnoreIntegration is a custom run of the 1.x-ignore integration job using this branch instead of 1.x. Just started.

**Comment by bstansberry** [comment]
Worked ok!

**Comment by dmlloyd** [comment]
Huzzah!

**Pull request merged**
