### PR TITLE
[WFCORE-5276]: Upgrade jgit to 5.10.0.202012080955-r

### PR DESCRIPTION
**Pull request by ehsavoie**
* Upgrading jgit to the new 5.10.0.202012080955-r version

Jira: https://issues.redhat.com/browse/WFCORE-5276

### CODE REVIEW

**Comment by jmesnil** [comment]
@ehsavoie WildFly full is not building with that component upgrade. Could you please have a look?

**Comment by ehsavoie** [comment]
@jmesnil it seems to be related to the lack of disk space that we hit yesterday

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
@ehsavoie I looked at the [Release Notes](https://projects.eclipse.org/projects/technology.jgit/releases/5.10.0/) but did not see how it is related to the removal of Bouncycastle dependencies from the manualmode tests. Could you please clarify?

**Comment by ehsavoie** [comment]
@jmesnil this was doable since 5.9 when they removed hard dependency on implementations for defaults

**Comment by jmesnil** [comment]
@ehsavoie thanks

**Pull request merged**
