### PR TITLE
[WFCORE-6268] Remove use of deprecated ModelTestControllerVersion enums

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFCORE-6268

### CODE REVIEW

**Review by yersan — APPROVED** [review]

**Comment by bstansberry** [comment]
@yersan I put a 'hold' on this as it looks like I missed a use of an enum value in the preparatory work I did for this in full WF. So that would need to be cleaned up first.

**Review by yersan — APPROVED** [review]
The failed org.jboss.as.logging.RootSubsystemOperationsTestCase does not use ModelTestControllerVersion, failure is unrelated

**Comment by bstansberry** [comment]
Thanks @yersan

**Pull request merged**
