### PR TITLE
[master] WFCORE-1568 AttributeDefinition should defer handling of undefined values to CapabilityReferenceRecorder

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFCORE-1568

N.B. This commit will cause the core+full integration tests to fail until https://github.com/wildfly/wildfly/pull/8914 is merged.

### CODE REVIEW

**Comment by bstansberry** [comment]
Please update the CapabilityReferenceRecorder javadoc to specify the param can be null and that it is permissible to do nothing in that case.

I should have specified that kind of thing when I wrote the API, although in this case it seems not doing so is a benefit!

@darranl will this break any elytron implementations?

**Comment by darranl** [comment]
I don't think it should break anything for us - any places where we must resolve a capability the attribute will not support undefined anyway.

**Comment by pferraro** [comment]
@bstansberry Will do.  Just to say, the only external impact of this change are custom CapabilityReferenceRecorder implementations (hence the failure in the wildfly integration run), which is handled in https://github.com/wildfly/wildfly/pull/8914

**Comment by pferraro** [comment]
Requisite downstream have been merged.

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
