### PR TITLE
[WFCORE-3522] Deployment module content comes before dependencies if isLocalLast is false

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Discussion:

> [8:57 AM] David Lloyd: the problem that arises is that even if "isLocalLast" is false, "dependencies" and "userDependencies" still come before local classes
[8:57 AM] David Lloyd: the reason for doing this is presumably to prevent user JARs from overwriting dependency JARs (classic parent-first fallacy)
[8:59 AM] David Lloyd: I think that if "isLocalLast" is false then we should put the createLocalDependencySpec() *first* before everything else
[9:00 AM] David Lloyd: the potential problem is user deployments that will break if they had included a wrong dependency
[9:01 AM] David Lloyd: but I'm tempted to take the Linus Torvalds approach: just fix it, and if anyone really wants to fix the wrong dependency problem, they will be motivated to do it then :)
[9:01 AM] David Lloyd: TBH we've needed a better solution to that for years now

**Comment by ropalka** [comment]
Looks good to me.

**Comment by dmlloyd** [comment]
It looks like there are numerous tests which use shrinkwrap and which duplicate classes all over the place.

**Comment by dmlloyd** [comment]
Looks like this solution is too simplistic and doesn't account for compatibility with existing cases.

**Pull request closed without merging**
