### PR TITLE
[WFCORE-5900] Add version 16 of the WildFly Elytron model and schema

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFCORE-5900

### CODE REVIEW

**Review by darranl — APPROVED** [review]

**Comment by fjuma** [comment]
@yersan The bump will be needed for [WFCORE-5859](https://issues.redhat.com/browse/WFCORE-5859) and [WFCORE-5740](https://issues.redhat.com/browse/WFCORE-5740).

**Comment by fjuma** [comment]
Just FYI, this PR is still active. We are just waiting on some Elytron RFEs to be pre-checked before merging this.

**Comment by fjuma** [comment]
Just FYI, this PR is now ready to be merged. WFCORE-5859 has been pre-checked by QE and we decided today that we will include the corresponding Elytron changes in Elytron releases tomorrow.

**Comment by yersan** [comment]
Thanks for confirming @fjuma

**Pull request merged**
