### PR TITLE
 [WFCORE-3684] Upgrade to JBoss Modules 1.8.0.Final

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
https://issues.jboss.org/browse/WFCORE-3684
https://issues.jboss.org/browse/WFCORE-3705
https://github.com/wildfly/wildfly-proposals/pull/39

**Comment by dmlloyd** [comment]
AFAIK failures are caused by https://issues.jboss.org/browse/WFLY-10134 - I will add a workaround commit for now.

**Comment by dmlloyd** [comment]
Requires https://github.com/wildfly/wildfly/pull/11104

**Comment by stuartwdouglas** [comment]
Superseded by https://github.com/wildfly/wildfly-core/pull/3201

**Pull request closed without merging**
