### PR TITLE
[WFCORE-6178] Upgrading JBoss MSC to 1.5.0.Beta5

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-6178

### CODE REVIEW

**Review by yersan — APPROVED** [review]
This version holds only clean up stuff, so giving approval from my side.

**Comment by ropalka** [comment]
@bstansberry @yersan any possibility this PR could be merged? I received a message about 90 days inactivity and warning it will be automatically closed :(

**Comment by bstansberry** [comment]
@ropalka I did a retest given the age of the last run. If you see it passes and we haven't merged it, please ping us in zulip chat "Pull Requests" stream.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
