### PR TITLE
[WFCORE-6305] Upgrade to Jandex 3.1.1

### PR DESCRIPTION
**Pull request by yersan**
Jira issue: https://issues.redhat.com/browse/WFCORE-6305

### CODE REVIEW

**Comment by scottmarlow** [comment]
CC @franz1981 @beikov @Ladicek

Will Weld 5.1.1.Final + Hibernate ORM 6.2.5.Final work well with this upgrade to Jandex 3.1.1 which I requested?  

Note that https://github.com/hibernate/hibernate-orm/pull/6402 is still pending which would reduce memory allocation especially with this upgrade.

**Comment by Ladicek** [comment]
I'd recommend using 3.1.2 which has some fixed for newer JDKs: https://smallrye.io/blog/jandex-3-1-2/

That said, I'm not aware of any breaking changes between 3.0 and 3.1, so things should just work.

**Comment by scottmarlow** [comment]
The [test failure](https://github.com/wildfly/wildfly-core/pull/5565#issuecomment-1607623701) appears to be caused by a setup failure creating table WebTxEmFlight:
```
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: GeneralError; SQL statement:
create table WebTxEmFlight (comp_id bigint, flight_id bigint generated by default as identity, flight_name varchar(50) not null, primary key (flight_id)) [50000-214]
  at com.h2database.h2@2.1.214//org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
  at com.h2database.h2@2.1.214//org.h2.message.DbException.addSQL(DbException.java:177)
  at com.h2database.h2@2.1.214//org.h2.command.Command.executeUpdate(Command.java:268)
  at com.h2database.h2@2.1.214//org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
  at com.h2database.h2@2.1.214//org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
  at org.jboss.ironjacamar.jdbcadapters@3.0.2.Final//org.jboss.jca.adapters.jdbc.WrappedStatement.execute(WrappedStatement.java:198)
  at org.hibernate@6.2.5.Final//org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:78)
  ... 29 more
Caused by: java.sql.SQLException: GeneralError
  at com.h2database.h2@2.1.214//org.h2.message.DbException.convert(DbException.java:400)
  at com.h2database.h2@2.1.214//org.h2.command.Command.executeUpdate(Command.java:264)
  ... 33 more
Caused by: java.lang.AssertionError
  at com.h2database.h2@2.1.214//org.h2.engine.Database.addMeta(Database.java:731)
  at com.h2database.h2@2.1.214//org.h2.engine.Database.addSchemaObject(Database.java:909)
  at com.h2database.h2@2.1.214//org.h2.table.Column.initializeSequence(Column.java:461)
  at com.h2database.h2@2.1.214//org.h2.command.ddl.CommandWithColumns.generateSequences(CommandWithColumns.java:103)
  at com.h2database.h2@2.1.214//org.h2.command.ddl.CreateTable.update(CreateTable.java:113)
  at com.h2database.h2@2.1.214//org.h2.command.CommandContainer.update(CommandContainer.java:169)
  at com.h2database.h2@2.1.214//org.h2.command.Command.executeUpdate(Command.java:252)
```

**Comment by bstansberry** [comment]
@scottmarlow I'm going to assume that failure means https://github.com/wildfly/wildfly/pull/16846 did not resolve the longstanding intermittent failure problem with that test. It passed with this PR on a subsequent run.

**Comment by bstansberry** [comment]
Thanks @yersan, @scottmarlow and @Ladicek. I'll send up a separate PR to go to 3.1.2.

**Comment by bstansberry** [comment]
The separate PR: #5568

**Pull request merged**
