### PR TITLE
[WFCORE-2368] Set default value of filter-name in Elytron ldap-realm …

### PR DESCRIPTION
**Pull request by danilAREFY**
…in management model
https://issues.jboss.org/projects/WFCORE/issues/WFCORE-2368

### CODE REVIEW

**Comment by bstansberry** [comment]
this is ok to test

**Comment by bstansberry** [comment]
@darranl please approve

**Comment by kabir** [comment]
@danilAREFY Are you looking into these failures?

**Comment by yersan** [comment]
@bstansberry , @kabir 

Since @danilAREFY seems is not working on this issue, in my opinion, can be safely closed. It should be replaced by https://github.com/wildfly/wildfly-core/pull/2642. The issue here is: the default value is dependent on another attribute in the realm. These attributes are not good candidates to get a constant default values using set-default, so we have added the default in the attribute description.

**Comment by bstansberry** [comment]
Closing per the comment about about #2642.

**Pull request closed without merging**
