### PR TITLE
WFCORE-3282 Duplicate record is written in property file when group name set to empty

### PR DESCRIPTION
**Pull request by msfm**
Upstream JIRA: https://issues.jboss.org/browse/WFCORE-3282
EAP 7.1.0 JIRA: https://issues.jboss.org/browse/JBEAP-13122
EAP 7.0.z JIRA: https://issues.jboss.org/browse/JBEAP-13099

### CODE REVIEW

**Comment by bstansberry** [comment]
Can you add something to PropertiesFileLoaderTestCase please? Thanks.

**Comment by darranl** [comment]
Actually I think PropertiesPatternMatchingTestCase would be the better one to modify but maybe split the testAllEntries into two - one to test password entries and the other to test group entries.

Also some manual test would be good to the time to load large files after a move from possessive quantifiers to greedy quantifiers - performance was a big consideration during the development of that pattern.

**Comment by xstefank** [comment]
surpased by #3009

**Comment by msfm** [comment]
@bstansberry @darranl Thanks for your comment. And I'm sorry that I did not have much time to improve this PR.

As @xstefank sent the new PR surpassing this, I'm closing this. Thanks, Martin!

**Pull request closed without merging**
