### PR TITLE
WFCORE-487 WFCORE-576 Upgrade jboss-remoting to 4.0.8

### PR DESCRIPTION
**Pull request by ctomc**
fixes WFCORE-487 Instability in RespawnHttpTestCase

### CODE REVIEW

**Comment by dmlloyd** [comment]
No surprise, doesn't really fix the issue.  There are a couple minor fixes in this release that are useful though.

**Comment by ctomc** [comment]
new agents don't have swap anymore and this results in failures above ^^
> Mar 19 12:42:45 build01-el6 kernel: Out of memory: Kill process 14158 (java) score 301 or sacrifice child
> Mar 19 12:42:45 build01-el6 kernel: Killed process 14158, UID 500, (java) total-vm:1440500kB, anon-rss:1180148kB, file-rss:4kB

**Comment by ctomc** [comment]
noting to do with wrong fix for remoting

**Comment by ctomc** [comment]
@dmlloyd with bit more RAM in new agents it passed as it should ^^

**Comment by ctomc** [comment]
retest this please just to make sure

**Pull request merged**
