### PR TITLE
[WFCORE-3814] Upgrade to Galleon and plugins 1.0.0.CR1

### PR DESCRIPTION
**Pull request by aloubyansky**
https://issues.jboss.org/browse/WFCORE-3814

### CODE REVIEW

**Comment by psakar** [comment]
@bstansberry  @aloubyansky both issues (A hang when using maven proxy B failure because of artifact not found without proxy) are present even after applying this patch

**Comment by aloubyansky** [comment]
@psakar i'll verify again today.

**Comment by psakar** [comment]
@aloubyansky hint - If I remove scope test for artifact which is not found (eg. https://github.com/wildfly/wildfly-core/blob/5.0.0.Alpha7/logging/pom.xml#L195), it is found

**Comment by aloubyansky** [comment]
retest this please

**Comment by bstansberry** [comment]
I'm not sure from the discussion above whether the proxy issue is corrected or not, but in any case this passes and the non-component-upgrade part is fine, so I'll merge it. If there's further change needed that can come in the next upgrade.

**Comment by bstansberry** [comment]
The GAL or WFGP projects in JIRA can be used for issues in Galleon or the WildFly plugins to it.

**Pull request merged**
