### PR TITLE
[WFCORE-4032] Add CLI request logging option

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.jboss.org/browse/WFCORE-4032
https://issues.jboss.org/browse/JBEAP-4904

### CODE REVIEW

**Comment by kabir** [comment]
@xstefank Something bad is happening, adding the fixme label

**Comment by xstefank** [comment]
@kabir yes, my bad. Should be ok now

**Comment by bstansberry** [comment]
This needs a new WFCORE JIRA. WFCORE-1583 was resolved long ago and JBEAP-4904 is not relevant to upstream.

**Comment by xstefank** [comment]
@bstansberry JBEAP-4904 has been reopened for CD/7.2, where WFCORE-1583 is its precise upstream (I don't remember how why it got resolved). New WFCORE will be duplicate.

**Pull request closed without merging**
