### PR TITLE
WFCORE-5899 [primary/secondary] Problematic Language usage deprecation and replacement of Java docs/variable names

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFCORE-5899

### CODE REVIEW

**Comment by parsharma** [comment]
Note: host-secondary-rbac-properties.xml and host-secondary-rbac.xml files are not updated.

**Comment by parsharma** [comment]
Integration failure will be resolved here: https://github.com/wildfly/wildfly/pull/16065

**Comment by parsharma** [comment]
@yersan pr is ready for review.
Thanks

**Comment by yersan** [comment]
Hi @parsharma 

> Note: host-secondary-rbac-properties.xml and host-secondary-rbac.xml files are not updated.

I've checked this test suite and ended up with the following suggestions: https://github.com/parsharma/wildfly-core/pull/1

Could you review them and append them to this set if you agree?

**Comment by parsharma** [comment]
Hello Yeray,
I have checked locally and the result is :
[ERROR] Errors: 
[ERROR]   FullRbacProviderPropertiesRoleMappingTestSuite.beforeClass:88->start:74 Runtime
[ERROR]   FullRbacProviderRunAsTestSuite.beforeClass:91->start:76 Runtime java.lang.Runt...
[ERROR]   FullRbacProviderTestSuite.beforeClass:113->start:99 Runtime java.lang.RuntimeE...
[ERROR]   SimpleRbacProviderTestSuite.beforeClass:88->start:74 Runtime java.lang.Runtime...
Failures: 
[ERROR]   ConfigurationChangesTestCase.testConfigurationChangesOnSecondary:140-

**Review by yersan — APPROVED** [review]
LGTM, RBAC tests will be fixed with WFCORE-6060

**Pull request merged**
