### PR TITLE
[bz-1196343] LDAP authentication/authorization fails due to making unneeded role lookup requests

### PR DESCRIPTION
**Pull request by dehort**
upstream: Wildfly: https://issues.jboss.org/browse/WFCORE-1202
wildfly/wildfly-core#1306
downstream: EAP 7: https://issues.jboss.org/browse/JBEAP-2320
way-downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1196343
https://github.com/jbossas/jboss-eap/pull/2654

### CODE REVIEW

**Comment by dehort** [comment]
Retest

**Comment by bstansberry** [comment]
@darranl please approve. If you agree, please ack https://issues.jboss.org/browse/JBEAP-2320 as well just to keep the paperwork straight. (The BZ is already acked, which is sufficient to merge this if the change itself is ok.)

**Comment by darranl** [comment]
I think I would prefer a config change in core and just use the system property for compatibility with those migrating from older versions - having said that the PR for the next major schema version is currently held up waiting for WildFly 11.

Also I think we need a bit more detail in the Jira issue.

Other than that - looks good.

**Comment by darranl** [comment]
I think both Jira issues need additional information adding.

Also I think the title should be more accurate, the lookup call is only unneeded if the role can be extracted from the DN.

**Comment by bstansberry** [comment]
+1 re: there needing to be a proper config item in the management schema. @dehort or @darranl please file a WFCORE for that. It's correct though that this PR doesn't involve that as it an forward port of a fix to EAP 6.4.

@dehort please improve the WFCORE-1022 content.

**Comment by darranl** [comment]
Once merged I will follow up on https://issues.jboss.org/browse/WFCORE-1228

**Pull request merged**
