### PR TITLE
[WFCORE-4148] In GC logging for Java8- put back quotes to .sh script

### PR DESCRIPTION
**Pull request by rstancel**
Jira: https://issues.jboss.org/browse/WFCORE-4148

Following this PR: https://github.com/wildfly/wildfly-core/pull/3496

### CODE REVIEW

**Comment by rstancel** [comment]
@jamezp Can you please review this? Thanks

**Comment by marekkopecky** [comment]
@rstancel, @jamezp: This LGTM

**Comment by rstancel** [comment]
@jamezp Rebased.

**Comment by marekkopecky** [comment]
JDK11 issue is currently not covered ...

**Comment by jamezp** [comment]
@marekkopecky Which JDK 11 issue? There's been so many I'm getting them confused :)

**Comment by rstancel** [comment]
@jamezp @marekkopecky Issue should be fixed (missing quotes in JDK 11 part). It is validated in Fedora on directory "wildfly(jboss)". Server has started and then I have shut it down without any issues

**Comment by marekkopecky** [comment]
I agree with @rstancel -> "abc(def)" JDK 11 issue is fixed by this PR. Thank you.

**Pull request merged**
