### PR TITLE
WFCORE-3510 Build tools 1.2.6.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
retest this please

**Comment by dmlloyd** [comment]
Is that the right JIRA #?  It references something about boot context.

**Comment by dmlloyd** [comment]
But it's not clear what was fixed here from the JIRA # at any rate...

**Comment by bstansberry** [comment]
@dmlloyd https://github.com/wildfly/wildfly-build-tools/compare/1.2.5.Final...1.2.6.Final

**Comment by stuartwdouglas** [comment]
The main one is the support for hard coded resources, as it allows us to create feature packs with different versions of the same jar for EE8.

**Pull request merged**
