### PR TITLE
WFCORE-3570 Undertow 2.0.0.Beta1

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by kabir** [comment]
@stuartwdouglas seems to be a compilation failure somewhere

**Comment by stuartwdouglas** [comment]
https://github.com/wildfly/wildfly/pull/10821 should resolve the upstream compilation issues

**Comment by stuartwdouglas** [comment]
retest this please

**Comment by jmesnil** [comment]
WildFly integration tests looks related to the PR: 

> java.lang.NoClassDefFoundError: javax/servlet/http/MappingMatch

@stuartwdouglas Should it have been solved by https://github.com/wildfly/wildfly/pull/10821 or is it a different issue (related to EE8)?

**Comment by kabir** [comment]
@jmesnil I guess it needs @stuartwdouglas https://github.com/wildfly/wildfly/pull/10827

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
@jmesnil @stuartwdouglas I started a few runs of this at https://ci.wildfly.org/project.html?projectId=WildFlyCore_PullRequest&branch_WildFlyCore_PullRequest=pull%2F3075

**Comment by stuartwdouglas** [comment]
Retest this plase

**Pull request merged**
