### PR TITLE
[WFCORE-5759] Upgrade bouncycastle from 1.69 to 1.70

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFCORE-5759

Please find release notes and diff link in the Jira.

### CODE REVIEW

**Comment by yersan** [comment]
Hello @boris-unckel , thanks for the PR. This is a duplicate of https://issues.redhat.com/browse/WFCORE-5735.

Just for your info, BC is also used by RestEasy and WebServices so we need approval from their component leads before upgrading it in wildfly-core.

Consequently, added a hold label. We need to wait for @jimma approval (@jamezp already confirmed this upgrade works for RestEasy).

I'm going to close WFCORE-5735 so we can use the one created by you to track the upgrade, thanks!

**Comment by boris-unckel** [comment]
@yersan Apologies. I should have checked that :-(

**Comment by yersan** [comment]
Sure, no problem @boris-unckel , it's ok, we will track it with this one.

**Comment by boris-unckel** [comment]
@yersan @fjuma The error mentioned above is related. Bouncycastle 1.70 introduces a incompatible change:
https://github.com/bcgit/bc-java/blob/r1rv70/core/src/main/java/org/bouncycastle/asn1/x509/SubjectPublicKeyInfo.java#L133 (see git history)

Found in `testsuite/integration/elytron/target/test.log`

```
13:53:47,226 ERROR [org.jboss.as.arquillian.container.ServerSetupObserver] (main) Setup failed during setup. Offending class 'org.wildfly.test.integration.elytron.certs.ocsp.OcspTestBase$OcspServerSetup@2de50ee4': java.lang.NoSuchMethodError: org.bouncycastle.asn1.x509.SubjectPublicKeyInfo.getPublicKeyData()Lorg/bouncycastle/asn1/DERBitString;
        at org.xipki.ocsp.server.impl.ResponderSigner.<init>(ResponderSigner.java:109)
        at org.xipki.ocsp.server.impl.OcspServer.initSigner(OcspServer.java:1022)
        at org.xipki.ocsp.server.impl.OcspServer.init0(OcspServer.java:408)
        at org.xipki.ocsp.server.impl.OcspServer.init(OcspServer.java:278)
        at org.wildfly.test.integration.elytron.certs.ocsp.TestingOcspServer.start(TestingOcspServer.java:121)
        at org.wildfly.test.integration.elytron.certs.ocsp.OcspTestBase.startOcspServer(OcspTestBase.java:362)
        at org.wildfly.test.integration.elytron.certs.ocsp.OcspTestBase$OcspServerSetup.setup(OcspTestBase.java:444)
        at org.wildfly.test.security.common.AbstractElytronSetupTask.setup(AbstractElytronSetupTask.java:56)
        at org.jboss.as.arquillian.container.ServerSetupObserver$ServerSetupTaskHolder.setup(ServerSetupObserver.java:185)
        at org.jboss.as.arquillian.container.ServerSetupObserver.handleBeforeDeployment(ServerSetupObserver.java:108)
```
The related test API https://github.com/wildfly/wildfly/blob/main/testsuite/integration/elytron/pom.xml#L58 is
https://mvnrepository.com/artifact/org.xipki.pki/ocsp-server which has an (major) update for this https://github.com/xipki/xipki/blob/v5.3.14/pom.xml#L36 which seems not available in public maven. How do we have to deal with this?

**Comment by yersan** [comment]
Thanks for the investigation and the related Jira @boris-unckel

It's a test dependency, so upgrading it sounds like the path to follow to unlock the BC upgrade, it looks like we have to migrate the tests cases as well to use the new version. @fjuma do you have any other suggestions? Soon or later this is going to bite us.

**Comment by boris-unckel** [comment]
@yersan @fjuma I have looked at xpiki a bit further: It's not only the new maven coordinate, it's really a major change: java packages changed, there are new necessary dependencies (API, util, server...). Unfortunately the servlet is not packaged in a jar anymore, it's a WAR file now. I have tried to make a copy of the old xpiki classes run in the WildFly java package namespace, but I had top stop due to lack of knowledge related to security  error messages. I'm going to provide it as branch, hopefully this evening. Maybe it's the completely wrong idea to make the testcase work, hopefully it helps to find a better way.

**Comment by boris-unckel** [comment]
@yersan @fjuma The draft is here https://github.com/boris-unckel/wildfly/tree/WFLY-15867_xpiki_draft I have commented on some changes. 

My build was with `mvn clean install -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -Dts.noSmoke -Dts.elytron -Dtest=org/wildfly/test/integration/elytron/certs/ocsp/*TestCase.java >../2022-01-11_1632_wfly.txt`

The result is in `testsuite/integration/elytron/target/test.log`

```
16:39:03,016 ERROR [org.xipki.ocsp.server.OcspServerImpl] (main) could not start OCSP responder: org.xipki.util.InvalidConfException: could not find Factory to create Signer of type JKS
	at org.xipki.ocsp.server.OcspServerUtil.initSigner(OcspServerUtil.java:104)
	at org.xipki.ocsp.server.OcspServerImpl.init0(OcspServerImpl.java:430)
	at org.xipki.ocsp.server.OcspServerImpl.init(OcspServerImpl.java:241)
	at org.xipki.ocsp.server.OcspServerImpl.init(OcspServerImpl.java:227)
	at org.wildfly.test.integration.elytron.certs.ocsp.TestingOcspServer.start(TestingOcspServer.java:129)
	at org.wildfly.test.integration.elytron.certs.ocsp.OcspTestBase.startOcspServer(OcspTestBase.java:362)
	at org.wildfly.test.integration.elytron.certs.ocsp.OcspTestBase$OcspServerSetup.setup(OcspTestBase.java:444)
	at org.wildfly.test.security.common.AbstractElytronSetupTask.setup(AbstractElytronSetupTask.java:56)
	at org.jboss.as.arquillian.container.ServerSetupObserver$ServerSetupTaskHolder.setup(ServerSetupObserver.java:185)
```
The configuration has switched from XML to JSON, you can find it here `testsuite/integration/elytron/src/test/resources/org/wildfly/test/integration/elytron/certs/ocsp/ocsp-responder.json`

**Comment by fjuma** [comment]
Thanks very much for looking into this, @boris-unckel!

It sounds like we need do need to update our tests.

@jstourac Do you have any thoughts on what approach to take? Do you know of any alternatives to the XiPKI based OCSP server that is currently being used for testing? Or do you think we should try to update the tests so that they work with the latest version of `org.xipki:ocsp-server`?

**Comment by yersan** [comment]
Hi @jstourac , would you mind sharing your feedback about this? It is blocking a BC upgrade, thanks!

**Comment by jstourac** [comment]
@fjuma @yersan Hi, I've completely missed your comments here.

Well, TBH, I'm not aware of any other alternative than XiPKI at the moment that is used in any of our testsuites. Would be great to update these tests to work with the latest XiPKI though.

**Comment by boris-unckel** [comment]
@yersan @fjuma Looking at the priorities: Would it be good to `@Ignore` the test for now, with a corresponding WFLY Jira? My personal opinion is that the update of a security component has a high worth, and a single test (which breaks due to dependencies) a lower priority.

**Comment by yersan** [comment]
Hi @boris-unckel , I am unable to measure the relevance of these tests and whether they should be ignored, so I defer it to @fjuma.

**Comment by fjuma** [comment]
@boris-unckel Instead of ignoring the test, would it be possible to temporarily update the test pom so that it depends on BC 1.69 until WFLY-15867 has been addressed?

**Comment by boris-unckel** [comment]
@fjuma It works, but it affects other tests as well. I have tested twice, first test was to check the tests breaks with 1.70, second one with the following change:
```
diff --git a/testsuite/integration/elytron/pom.xml b/testsuite/integration/elytron/pom.xml
index f26154d5bc..c9f7e705c3 100644
--- a/testsuite/integration/elytron/pom.xml
+++ b/testsuite/integration/elytron/pom.xml
@@ -52,6 +52,7 @@
         <jbossas.project.dir>${jbossas.ts.dir}/..</jbossas.project.dir>
         <wildfly.dir>${basedir}/target/${wildfly.instance.name}</wildfly.dir>
         <security.properties>${project.basedir}/src/test/resources/reenabled_tlsv1.properties</security.properties>
+        <version.org.bouncycastle>1.69</version.org.bouncycastle>
         <version.org.hsqldb.hsqldb>2.5.0</version.org.hsqldb.hsqldb>
         <version.org.mock-server.mockserver>5.6.1</version.org.mock-server.mockserver>
         <version.org.mock-server.mockserver-netty>5.6.1</version.org.mock-server.mockserver-netty>
@@ -235,24 +236,28 @@
         <dependency>
             <groupId>org.bouncycastle</groupId>
             <artifactId>bcpkix-jdk15on</artifactId>
+            <version>${version.org.bouncycastle}</version>
             <scope>test</scope>
         </dependency>
 
         <dependency>
             <groupId>org.bouncycastle</groupId>
             <artifactId>bcmail-jdk15on</artifactId>
+            <version>${version.org.bouncycastle}</version>
             <scope>test</scope>
         </dependency>
 
         <dependency>
             <groupId>org.bouncycastle</groupId>
             <artifactId>bcprov-jdk15on</artifactId>
+            <version>${version.org.bouncycastle}</version>
             <scope>test</scope>
         </dependency>
 
         <dependency>
             <groupId>org.bouncycastle</groupId>
             <artifactId>bcutil-jdk15on</artifactId>
+            <version>${version.org.bouncycastle}</version>
             <scope>test</scope>
         </dependency>
```

**Comment by fjuma** [comment]
Thanks @boris-unckel! I think that's fine. I think it would be good to add a comment in the pom.xml to indicate why we're using a different version. I think it would also be good to create a WFLY issue to track updating the test dependency to the newer version. The new issue could then depend on https://issues.redhat.com/browse/WFLY-15867.

**Comment by boris-unckel** [comment]
@fjuma Please find the 1.69 pinning here https://github.com/wildfly/wildfly/pull/15327 including documentation and linked Jiras.

**Comment by boris-unckel** [comment]
@yersan @fjuma WFLY-16155 has been merged. Could one of you trigger a full retest here, please?

**Comment by yersan** [comment]
retest this please

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
@boris-unckel , thank you for the contribution and all the handling around this.

**Pull request merged**
