### PR TITLE
[WFCORE-5079] Remove temporary "secure-managament" alias.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFCORE-5079

This pull request follows up on https://github.com/wildfly/wildfly-core/pull/4295 to remove the temporary "secure-management" alias.

This PR can only be merged after https://github.com/wildfly/wildfly/pull/13468 as WildFly has a dependency on the "secure-management" layer.  An immediate tag of core is not required after merging this one.

### CODE REVIEW

**Comment by bstansberry** [comment]
@jmesnil fyi.

Note that it's best to look at the commits as only the last one is relevant. The other 3 are already in master via #4295

**Comment by yersan** [comment]
@darranl Do you think we can finally merge this one? there is no `secure-management` alias on 7.3.x. It would be a detail that will allow both branches matching on this regards. I'm not sure what were your plans around this.

**Comment by darranl** [comment]
@yersan Just removed the hold label - the PR to WildFly is now merged so just kicked off a test run to see if this is clean now.

**Comment by darranl** [comment]
@yersan if I can get a clean CI run I will bundle this up with other changes coming to core to get it merged.

**Pull request merged**
