### PR TITLE
[WFCORE-5782] Reset 'java.security.manager' default value back to "allow" by default in WildFly shell scripts

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-5782

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Thanks @ropalka!

**Comment by fjuma** [comment]
@jamezp It would be good if you could take a look at this one as well.

Note that as Jeff pointed out, we should merge this and https://github.com/wildfly/wildfly-core/pull/4934 at the same time.

**Review by jamezp — CHANGES_REQUESTED** [review]
This looks good, but the launcher would need changes too for Arquillian and others to work properly.

**Comment by ropalka** [comment]
Right @jamezp , launcher changes are in separate PR here: https://github.com/wildfly/wildfly-core/pull/4934

**Review by jamezp — APPROVED** [review]

**Comment by jmesnil** [comment]
@ropalka thanks

**Pull request merged**
