### PR TITLE
[WFCORE-3965] Cover possible error when host controllers can not conn…

### PR DESCRIPTION
**Pull request by JiriOndrusek**
…ect to domain after creating a rollout plan and restarting the master host controller - fix (of possible errors) in test

Issue: https://issues.jboss.org/browse/WFCORE-3965

This PR contains only fix for error in test. Missing clean of environment and proper wait after execution.

### CODE REVIEW

**Comment by kabir** [comment]
@JiriOndrusek I tested this along with PRs 3463 and 6460 yesterday and  saw problems in ResponseStreamTestCase:
https://ci.wildfly.org/viewType.html?buildTypeId=WildFlyCore_MasterIgnoreLinux
https://ci.wildfly.org/viewType.html?buildTypeId=WildFlyCore_MasterIgnorWindows

Today I did a bunch of runs of each PR individually, and the only place it crops up is in your PR
https://ci.wildfly.org/viewLog.html?buildId=118253&tab=buildResultsDiv&buildTypeId=WildFlyCore_PullRequestWindows

So I think it is safe to say it is something in this PR causing it. Also, when checking the history of the failing test the only place that happened earlier was in PR #3393 which I believe is related. I am just about to join a meeting, but will check the jobs afterwards (since they haven't all completed yet) just to double check.

**Comment by JiriOndrusek** [comment]
@kabir I'll look into it.

**Comment by kabir** [comment]
@JiriOndrusek I double checked and my last comment still seems valid. I've added the hold label to avoid merging this by accident

**Comment by JiriOndrusek** [comment]
Closing. Current change is not needed. Everything is already merged in https://github.com/wildfly/wildfly-core/pull/3393

**Pull request closed without merging**
