### PR TITLE
[WFCORE-1709] Added tests for special character resource values

### PR DESCRIPTION
**Pull request by mschvarc**
JIRA: https://issues.jboss.org/browse/WFCORE-1709

Description: Added tests for special characters in resource values for interactive and non-interactive CLI modes

### CODE REVIEW

**Comment by mschvarc** [comment]
Retest this please

**Comment by mschvarc** [comment]
@bstansberry I've fixed the failing test issues

**Comment by bstansberry** [comment]
:)

@jfdenise please approve

**Comment by jfdenise** [comment]
Approved. Thank-you for adding this test.
JF

**Pull request merged**
