### PR TITLE
WFCORE-564 Fix PersistentResourceXMLDescription parser

### PR DESCRIPTION
**Pull request by ctomc**
- it now properly supports mixing attribute groups & wrappers
- add support for multiple resources inside wrapper element
- add option to override also marshaller insde parser definition

also add tests to make sure this works properly

### CODE REVIEW

**Comment by ctomc** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

Problems on master-ignore:

http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=37837&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreMasterIgnoreIntegration

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
@bstansberry you are right, something was wrong, replacement PR is #543

**Pull request closed without merging**
