### PR TITLE
[WFCORE-6277] adds wildflyee.api module dependency to java.se

### PR DESCRIPTION
**Pull request by emmartins**
Issue: https://issues.redhat.com/browse/WFCORE-6277

### CODE REVIEW

**Comment by yersan** [comment]
Added Hold label, since this bug is still under discussion

**Review by yersan — COMMENTED** [review]
@ropalka  what's your feeling about this?

I'm not fully getting the root cause yet, accordingly to the changes in https://github.com/wildfly/wildfly-core/pull/5384, the `java.se` module should be available to all the deployments since it is added as a dependency to the Deployment module via `ServerDependenciesProcessor`.

**Comment by jamezp** [comment]
Is there a discussion about this somewhere? There is no JIRA description so it's not clear if this is causing issues somewhere.

**Comment by yersan** [comment]
We can follow up the discussion in [Zulip](https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/WFCORE-6277)

**Comment by ropalka** [comment]
I removed javax.api but in this particular case it is obvious module is also used outside from WildFly runtime so java.se explicit dependency is needed.

**Comment by yersan** [comment]
Thanks for adding your review @ropalka

**Comment by yersan** [comment]
And @emmartins for fix it :)

**Pull request merged**
