### PR TITLE
[WFCORE-2116 2.x] Update xnio to 3.4.3.

### PR DESCRIPTION
**Pull request by langfr**
Upstream https://github.com/wildfly/wildfly-core/pull/2036

### CODE REVIEW

**Comment by bstansberry** [comment]
@dmlloyd is this ok in a community micro release (2.2.1.Final)?

There are no EAP implications. However WildFly Swarm will pick up 2.2.1.

**Comment by bstansberry** [comment]
https://github.com/xnio/xnio/compare/3.4.0.Final...3.4.3.Final

**Comment by dmlloyd** [comment]
Yeah this should be OK.

**Comment by bstansberry** [comment]
Paperwork note: Since this is now a bump to 3.4.3, the JIRA for this is really https://issues.jboss.org/browse/WFCORE-2361 as WFCORE-2116 was for an upgrade to 3.4.2. So I can't reuse 2116 and just add another Fix Version.

**Pull request merged**
