### PR TITLE
[EAP7-575]: Test development

### PR DESCRIPTION
**Pull request by istraka**
Analysis document: https://polarion.engineering.redhat.com/polarion/#/project/EAP7/wiki/RFEs_7_1/EAP7-575
EAP7 issue: https://issues.jboss.org/browse/EAP7-575

### CODE REVIEW

**Comment by ctomc** [comment]
this is ok to test

**Comment by istraka** [comment]
Failed tests have nothing to do with MR. Please retest.

**Comment by kabir** [comment]
Once merged, please move EAP7-575 to backport todo

**Comment by bstansberry** [comment]
In the future let's use WFCORE commit messages for this stuff. EAP7 is not a publicly accessible JIRA so community users have no way to know what it's about.

**Pull request merged**
