### PR TITLE
[WFCORE-6246] Upgrade snakeyaml from 1.33 to 2.0

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/WFCORE-6246 Upgrade snakeyaml from 1.33 to 2.0

cc @ehsavoie @jamezp

### CODE REVIEW

**Comment by soul2zimate** [comment]
SnakeYaml 2.0 contains `Backwards-incompatible` changes , see https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes.

`microprofile` integration tests uses snakeyaml 1.33 via

```
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.4:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.33:compile
```

It seems that we need to wait and upgrade [jackson-dataformats-text](https://github.com/FasterXML/jackson-dataformats-text) 2.15 in WFLY to incorporate  https://github.com/FasterXML/jackson-dataformats-text/pull/390

**Comment by bstansberry** [comment]
@jamezp @pferraro FYI.

**Comment by soul2zimate** [comment]
superseded by https://github.com/wildfly/wildfly-core/pull/5397

**Review by yersan — APPROVED** [review]

**Pull request merged**
