### PR TITLE
Deprecate threading subsystem & security module

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by dmlloyd** [comment]
That's a lot of failures.

**Comment by ctomc** [comment]
@dmlloyd yeah, they are fixed by https://github.com/wildfly/wildfly/pull/7171

**Comment by ctomc** [comment]
retest this please

**Comment by bstansberry** [comment]
The PR failures on core look related to this.

**Comment by scottmarlow** [comment]
@jamezp mentioned that he was able to run the TCK locally after removing the threading subsystem from his standalone.xml.  Did this bz 1190981 change make it into EAP 6.4 yet?

**Comment by ctomc** [comment]
@scottmarlow threads subsystem was deprecated in EAP already.
In upstream it there is additional change that prevents threads subsystem to be used for anything else but managing legacy model (for mixed domain mode scenarios) similar as we have with web and jaxr subsystems.
Upstream code & configurations should not use threads subsystem anymore.
So proper fix for TCK is to remove threads subsystem from all its configs

**Pull request merged**
