### PR TITLE
[WFCORE-766] Move cli extension tests from manual mode into standalone

### PR DESCRIPTION
**Pull request by pkremens**
https://issues.jboss.org/browse/WFCORE-766

Tests for WFCORE-582 are currently located in manual mode module, but could be moved into standalone module to save ts execution time.

### CODE REVIEW

**Comment by jamezp** [comment]
retest this please

**Comment by jamezp** [comment]
There seems to be an issue with a changed test on Windows.

**Comment by pkremens** [comment]
It's a problem with 
```java
testModule.remove();
```
on Windows, as the file lock on testModule is released only on server shutdown. First test fails to delete testModule and second fails due to this. I'll change the name of testModule for second test so there are no collision.

**Comment by pkremens** [comment]
retest this please

**Comment by pkremens** [comment]
EjbRemoteSuspendTestCase fail doesn't seem to be related

**Comment by bstansberry** [comment]
Thanks!

**Comment by pkremens** [comment]
You're welcome.

**Pull request merged**
