### PR TITLE
[1.x] [WFCORE-649] Add logging 1.5 schema. Add new transformer tests.

### PR DESCRIPTION
**Pull request by jamezp**
The first commit just removes some tests that aren't needed as they're covered by the LoggingSubsystemTestCase.

The second commit adds the logging 1.5 schema. I added the missing transformer tests and fixed transformers that were done incorrectly.

### CODE REVIEW

**Comment by jamezp** [comment]
Something seems wrong with the CI. This shouldn't cause any issues in full though.

**Comment by jamezp** [comment]
retest this please

**Comment by jamezp** [comment]
This is passing locally for me. I'm not sure why it's having a difficult time passing on the CI.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
The CI job was misconfigured. It was still testing the 1.x branch against full master, not full 9.x.

**Comment by jamezp** [comment]
retest this please

**Pull request merged**
