### PR TITLE
[WFCORE-2925] Heap settings separation in standalone and domain conf scripts

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFCORE-2925

### CODE REVIEW

**Comment by darranl** [comment]
@lvydra have you had any discussions with anyone about taking on this issue, and around the naming of the variable to use?

**Comment by lvydra** [comment]
Hi @darranl , I have discussed taking on this issue, but not the naming. I'm open to suggestions/discussion.

**Comment by darranl** [comment]
Thanks, I was asking because Brian says he only gave the names 20s thought but each of the variables does either have size in it's description or name so I think we are good.

Everyone has now had over a month to come up with alternatives.

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
@bstansberry I have added an approval of this one as the suggested changes have been implemented and the name feels correct - but do you think we need some documentation updates as well?

**Comment by bstansberry** [comment]
@luck3y @jfdenise Any concerns about this? This idea (which I forgot I had!) predates us doing cloud stuff, bootable jar etc. 

Partly I'm asking as an FYI in case we need to adjust anything elsewhere

**Comment by luck3y** [comment]
This looks fine to me, we'd just have to set JBOSS_JAVA_SIZING to some not empty value in images to meet the other requirement (I don't have the ticket # handy) for not specifying any default values for max metaspace. So +1 from me.

**Comment by bstansberry** [comment]
@darranl I don't see any docs of JAVA_OPTS, so it seems we can live without. ;)

@luck3y We should get rid of the max metaspace in wf core as well. :)

**Comment by bstansberry** [comment]
Thanks @lvydra !

**Pull request merged**
