### PR TITLE
[WFCORE-114] : Get RuntimeVaultReader into WildFly Core

### PR DESCRIPTION
**Pull request by ehsavoie**
Moving RuntimeVaultReader from WildFly to WildFly-Core

Jira: https://issues.jboss.org/browse/WFCORE-114

### CODE REVIEW

**Comment by ctomc** [comment]
Does wildfly-core still boot with this in?
As by design we don't include picketbox as part of wildfly-core distro but only wildfly-full ships PB modules.

**Comment by ctomc** [comment]
as discussed with @ehsavoie this works fine without PB, it is safe to merge

**Comment by bstansberry** [comment]
@ehsavoie I don't see how it can work fine. If you configure a vault, it won't work as the classes are not present.

There are tests in core-model-test of the vault config, but they don't involve the runtime stuff, just Stage.MODEL.

**Comment by ehsavoie** [comment]
To be reworked

**Pull request closed without merging**
