### PR TITLE
Various component updates

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Retest this please

**Comment by darranl** [comment]
This one looks like it will conflict with my PR so I am going to merge into my PR - as long as this one is not rebased they can both still go in in any order.

**Comment by dmlloyd** [comment]
So in case it wasn't obvious, this is going to have to be part of a coordinated release....

**Comment by darranl** [comment]
This one should still be on hold I think, I have merged it for a second time now with my PR so it up to date with the latest component upgrades.

**Comment by kabir** [comment]
Included by https://github.com/wildfly/wildfly-core/pull/2380

**Pull request closed without merging**
