### PR TITLE
WFLY-13828 remote+tls is not supported by EJBClient and remote-outbou…

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/WFLY-13828
Other related PR for the same issue: [#475](https://github.com/wildfly/jboss-ejb-client/pull/475)

### CODE REVIEW

**Comment by jmesnil** [comment]
@ropalka could you please review?

In particular would that need a release of jboss-ejb-client with https://github.com/wildfly/jboss-ejb-client/pull/475/ merged?

**Review by ropalka — CHANGES_REQUESTED** [review]
I would say also the following files should be updated accordingly @RanabirChakraborty :
 * cli/src/main/java/org/jboss/as/cli/ControllerAddressResolver.java
 * protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionConfiguration.java

**Comment by ropalka** [comment]
> @ropalka could you please review?
> 
> In particular would that need a release of jboss-ejb-client with [wildfly/jboss-ejb-client#475](https://github.com/wildfly/jboss-ejb-client/pull/475) merged?
I would say this is another feature available via future jboss-ejb-client upgrade @jmesnil .

**Comment by jmesnil** [comment]
@ropalka thanks, I've requalified WFLY-13828 as a Feature Request that will have to follow our regular process for new features.

**Comment by RanabirChakraborty** [comment]
Thank you @ropalka , @jmesnil for your feedback. I'll do the changes accordingly :)

**Comment by bstansberry** [comment]
This will require a bump in the mgmt api version in RemotingExtension and an update to RemotingTransformers a la what's in L111. 

This is a pre-existing problem but the ConnectorCommon.SASL_PROTOCOL attribute def at a glance looks like it should be limited to values in the Protocol enum. That should be investigated (carefully -- the fact its in a ''common" class hints it's use is not simple/obvious) and if it's wrong, fixed as part of this work. That would likely involve some further changes to  RemotingTransformers.

**Comment by darranl** [comment]
@RanabirChakraborty / @ropalka Do we have a plan yet as to how this will be proceeding?  At the moment it is flagged as an RFE which is not ready for merge but it appears the current outstanding steps are with the engineers to kick off the process.

**Comment by RanabirChakraborty** [comment]
@darranl I'm not working on this issue right now. @ropalka has assigned Tomasz Adamski for the issue. 
I'm closing this PR. Sorry for the inconvenience.

**Pull request closed without merging**
