### PR TITLE
[WFCORE-3923] Provide a profile to run enforcer rule for downstream p…

### PR DESCRIPTION
**Pull request by gaol**
…rojects - wildfly-core

Added a profile enforce-product to check redhat dependencies

Jira: https://issues.jboss.org/browse/WFCORE-3923

### CODE REVIEW

**Comment by gaol** [comment]
retest this please

**Comment by gaol** [comment]
@jmesnil Could you please re-run the failed CI jobs and to see if it is OK to merge?
BTW, the similar PR for WildFly https://github.com/wildfly/wildfly/pull/11342 has been merged.

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
@gaol Could the `enforce-product` profile be declared in the root `pom.xml` instead of duplicating it in the `core-feature-pack`  and `core-galleon-pack` modules?

**Comment by gaol** [comment]
@jmesnil it is intended to be only included in `core-feature-pack` and `core-galleon-pack`, so that we can only run enforcer rule for these 2 distributed packs in EAP CP streams.

In downstream, all artifacts in these 2 distributed packs are required built from prod team(*-redhat-X). But we still have other community version dependencies, like some test scope dependencies, build tools related dependencies etc. so that we cannot have the profile in the root `pom.xml` which will enforce all modules.

**Pull request merged**
