### PR TITLE
WFCORE-1139 Undertow 1.3.6.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by pferraro** [comment]
The wildfly full integration test failure is due to https://issues.jboss.org/browse/WFLY-5711
Fix is here: https://github.com/wildfly/wildfly/pull/8417

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
