### PR TITLE
WFCORE-3164 Wildfly OpenSSL 1.0.0.Final

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by jamezp** [comment]
retest this please

**Comment by bstansberry** [comment]
@stuartwdouglas is the test failure relevant?

**Comment by bstansberry** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
@bstansberry the earlier test failures were not relevant, there were no material changes between the versions being updated (just the license files)

**Comment by stuartwdouglas** [comment]
retest this please

**Pull request merged**
