### PR TITLE
[WFCORE-3971] Referral mode should be an enumeration

### PR DESCRIPTION
**Pull request by marschall**
https://issues.jboss.org/browse/WFCORE-3971

### CODE REVIEW

**Comment by marschall** [comment]
@jmesnil did I break all those tests? I can't login to the CI server?

**Comment by jamezp** [comment]
There should be a "Log in as guest" link that will allow you to see it. But yes it breaks the build. It looks like previously some configurations use `THROW` which isn't allowed with the new constraints to lowercase only.

**Comment by marschall** [comment]
There was an additional issue that model serialization would generate ALL-CAPS values.

**Comment by jamezp** [comment]
@marschall In that case we might not be able to do this or we're going to have to allow for both upper/lower case. Otherwise we break compatibility.

**Comment by darranl** [comment]
Yeah updating the schema is Ok as that is a new schema.

We can update the code now to always write using lowercase, that will be fine as the write always uses the latest schema.

But we must continue to support older configuration which may use upper or lower case.

**Comment by jamezp** [comment]
+1 to what @darranl says. It should just be the parser that needs to be updated.

**Comment by marschall** [comment]
@darranl I'm not that familiar with the model and the parsers, how do I change it so that lower case values are written?
Also I don't understand why both `setAllowedValues` and `.setValidator(EnumValidator)` are called.

Currently a `.toUpperCase()` is already performed so it looks as if the values are already case insensitive
https://github.com/wildfly/wildfly-core/blob/master/elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java#L194

**Comment by kabir** [comment]
@marschall I am just jumping in real quick without really remembering how this works, or having looked much at the failure. But in case it helps take a look at https://github.com/wildfly/wildfly/blob/master/ejb3/src/main/java/org/jboss/as/ejb3/subsystem/StrictMaxPoolResourceDefinition.java#L75 which accepts lower case values https://github.com/wildfly/wildfly/blob/master/ejb3/src/main/resources/subsystem-templates/ejb3.xml#L16. The magic seems to be in the DeriveSize enum

**Comment by bstansberry** [comment]
I think changing ReferralMode.toString() to return getValue() will solve this with no need to change the management code.

**Comment by jmesnil** [comment]
closing this PR as it is superseded by #3523

**Pull request closed without merging**
