### PR TITLE
[WFCORE-6312] Add version 18 of the WildFly Elytron model and schema

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFCORE-6312

Creating this as a draft PR for now since we have at least one RFE being worked on right now that needs this. This can be merged once we have an RFE that has been pre-checked.

### CODE REVIEW

**Comment by yersan** [comment]
CC @ehsavoie since he can help with the yaml failures

**Comment by fjuma** [comment]
@ehsavoie Would you be able to help with the yaml failures? I haven't been able to look closely yet but I'm not sure where it's getting the `urn:wildfly:elytron:17.0` value from since it looks like I've updated that to `urn:wildfly:elytron:18.0` in most places. Thanks!

**Comment by yersan** [comment]
@fjuma It looks like these XML files are the bad guys:

https://github.com/wildfly/wildfly-core/blob/main/testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml#L90
https://github.com/wildfly/wildfly-core/blob/main/testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml#L87

**Comment by ehsavoie** [comment]
@fjuma PR sent on your branch https://github.com/fjuma/wildfly-core/pull/4

**Comment by fjuma** [comment]
Thanks very much @yersan and @ehsavoie! I've just merged @ehsavoie's PR against my branch.

**Review by yersan — APPROVED** [review]

**Comment by darranl** [comment]
Please don't make any further changes to this PR - I am going to combine it with a couple of other PRs so we can get them merged together.

Thank you for this implementation.

**Pull request merged**
