### PR TITLE
[WFCORE-5185] Update ProviderDefinition to use optimised service loading API

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.redhat.com/browse/WFCORE-5185

### CODE REVIEW

**Comment by darranl** [comment]
@ivassile this looks like we have a merge conflict but other than that looks good to go.

**Comment by ivassile** [comment]
@darranl Resolved merge conflict.

**Comment by darranl** [comment]
Ok we will give testing another go at the end of the week once WildFly 23 is out - then this is hopefully good to go.

**Comment by darranl** [comment]
Sorry @ivassile looks like we still have a merge conflict.

**Comment by ivassile** [comment]
@darranl rebased again

**Pull request merged**
