### PR TITLE
[WFCORE-4894] Upgrade jackson databind to 2.10.3 ...

### PR DESCRIPTION
**Pull request by panossot**
[WFCORE-4894] : https://issues.redhat.com/browse/WFCORE-4894

### CODE REVIEW

**Comment by jmesnil** [comment]
@panossot Could you please create a WFCORE component upgrade for this and reference it from the commit message?

**Comment by jmesnil** [comment]
@panossot Could you please rebase and create a WFCORE component upgrade for this and reference it from the commit message?

**Comment by panossot** [comment]
Sure. Just a moment....

**Comment by panossot** [comment]
It should be done ...

**Comment by jmesnil** [comment]
@panossot thanks

**Pull request merged**
