### PR TITLE
[WFCORE-1135] Enable custom SSL configuration for the connection from the app server to it's host controller.

### PR DESCRIPTION
**Pull request by darranl**
Also includes [WFCORE-1283] to add a new version of the management model / schema.

### CODE REVIEW

**Comment by darranl** [comment]
The WildFly side of this PR can be found here https://github.com/wildfly/wildfly/pull/8578

**Comment by darranl** [comment]
So far test failures look to be expected until both PRs are merged in parallel.

**Comment by darranl** [comment]
Before this is merged I have one more commit to add.

**Comment by darranl** [comment]
Retest this please

**Comment by darranl** [comment]
This last failure looks like TeamCity is using an stale copy of the branch - the line calling assertEquals is now line 184 in the test and not 170.

**Comment by bstansberry** [comment]
Added 3.x per yesterday's discussion.

**Pull request merged**
