### PR TITLE
[WFLY-5332]: Allow configure max-threads and core-threads independently. Allow idle thread reusage.

### PR DESCRIPTION
**Pull request by panossot**
[WFLY-5332] : https://issues.jboss.org/browse/WFLY-5332

The PR tests will fail till https://github.com/jbossas/jboss-threads/pull/16 is included.

### CODE REVIEW

**Comment by ctomc** [comment]
parser change is wrong. You need to update 2.0 parser not the legacy one.
There are no parser / model tests for new attribute.
this is just subsystem wise.
@dmlloyd wdyt about the concept? I know you are not fan such thread pools.

**Comment by panossot** [comment]
You are right Tomaz. It seems upstream needs some mere work.

**Comment by dmlloyd** [comment]
First, our thread pools already always reuse idle threads; that certainly isn't a problem.  So I think the pool name is misleading.

However, in general I am highly, highly skeptical of the safety of a new thread pool implementation.  In addition, there is a large amount of locking going on in this pool implementation.  I'm not inclined to approve it as is unless it can be shown to have equal or better performance to the existing pools.

**Comment by panossot** [comment]
Hello David, it should be compared with which thread pool? (JBossThreadPoolExecutor, which was the default, was not reusing idle threads)

**Comment by dmlloyd** [comment]
Are you saying that it was creating a new thread for every task?

**Comment by panossot** [comment]
Till core threads, yes. And since for the default pool we use corethreads=maxthreads, till max threads it creates a new thread for every new task.

**Comment by dmlloyd** [comment]
Oh, yes of course.  The pool must prefill; that's what core threads are.  Max threads are non-prefilled threads, which can be reused in preference to creating new threads.

That said, no existing thread pool has implemented core/max threads in an efficient *and* safe manner.

**Comment by panossot** [comment]
I will try to create some test to prove its efficiency/safety.

**Comment by dmlloyd** [comment]
For a thread pool, tests can prove efficiency but not safety.  To prove safety, because it is concurrent code, you need nothing less than a complete state diagram.

**Comment by panossot** [comment]
Ok. I will try to create a state diagram as well.

**Comment by bstansberry** [comment]
Please submit a design proposal to wildfly-dev. Jason intends to start requiring that for new features, and for this one it sounds particularly useful. We can then review pull requests in comparison to an agreed upon design.

**Pull request closed without merging**
