### PR TITLE
Upgrade to http-core 4.4.5 and http-client 4.5.4

### PR DESCRIPTION
**Pull request by rpelisse**
Upstream Issue: https://issues.jboss.org/browse/WFCORE-3473
Issue: https://issues.jboss.org/browse/JBEAP-13801

### CODE REVIEW

**Comment by bstansberry** [comment]
@asoldano Please approve. I review of module.xml contents tells me cxf and resteasy are the production code consumers of these libs.

**Comment by bstansberry** [comment]
Requires https://github.com/wildfly/wildfly/pull/10723 before it can be merged.

**Comment by langfr** [comment]
httpclient is using httpcore 4.4.7. Shouldn't this be the httpcore version here also?
And httpcore 4.4.8 is already out.

**Comment by rpelisse** [comment]
@langfr I honestly pondered about that. I did have to change some minor things to be able to update http-core 4.4.5 and http-client 4.5.4, so there might more work if you upgrade to even more recent version. I'm not set against upgrading to latest version if other people +1 this.

**Comment by asoldano** [comment]
@rpelisse , you should create a RESTEASY jira for performing the upgrade in it first. I've quickly tried the upgrade locally and got a regression in the resteasy testsuite.

**Comment by rpelisse** [comment]
@langfr exactly why I did not update to the latest ;) 

@asoldano gotcha, I'm working on making the issues (for both upstream and the maintenance branch of Resteasy)

**Comment by bstansberry** [comment]
I put a 'hold' label on this to save the mergers looking at this as it sounds like there are external issues to sort. @rpelisse or @asoldano please ping me in chat or mail when this looks ok.

The downstream-update-required issue is cleared as that PR has been merged.

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
OK, so this time around the following builds went fine:

- **Full Integration Windows**,
- **Linux JDK9 (Pull Request) - merge** and 
- **Windows (Pull Request)** - merge

I'm pretty sure the two first ones (**Full integration - Linux** and **Linux (Pull Request) - merge**) did passed in earlier build. So I'm going to one more rebuild and see if I can get those two to work.

**Comment by rpelisse** [comment]
retest this please

**Comment by kabir** [comment]
Adding the fixme label as I messed up trying to resolve the conflicts in the GH editor

**Comment by rpelisse** [comment]
@kabir I'm not sure what is the hold up here? Do you want me to tweak this PR again somehow?

**Comment by jmesnil** [comment]
@asoldano do you see any issue with merging this PR now (for WildFly 15)?

**Comment by asoldano** [comment]
@jmesnil fine with me, in the mean time resteasy moved to those versions.

**Pull request merged**
