### PR TITLE
[WFCORE-1742] Add hooks to certain kinds of contexts to the HTTP mana…

### PR DESCRIPTION
**Pull request by bstansberry**
…gement interface

https://issues.jboss.org/browse/WFCORE-1742
https://issues.jboss.org/browse/EAP7-614

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by pedroigor** [comment]
@bstansberry, your changes look sufficient to expose that custom context for HAL in order to expose configuration from Keycloak subsystem.

If you are OK, we can merge it in upstream and then with Elytron's remoting5_integration branch.

**Comment by pedroigor** [comment]
@bstansberry, your changes look sufficient to expose that custom context for HAL in order to expose configuration from Keycloak subsystem.

Once merged, I think we can create a separated branch based on Elytron's remoting5_integration branch containing all changes from this PR. That way I can actually test and give something to HAL as well.

**Comment by bstansberry** [comment]
@pedroigor this will be in the core Alpha11 release today.

**Pull request merged**
