### PR TITLE
[WFCORE-1199] CLI Lists in non-interactive mode are erroneously split…

### PR DESCRIPTION
**Pull request by ryanemerson**
… into multiple commands

JIRA: https://issues.jboss.org/browse/WFCORE-1199

### CODE REVIEW

**Comment by jamezp** [comment]
@aloubyansky Could you please give your thoughts on this?

**Comment by bstansberry** [comment]
@aloubyansky if this is ok, please hit the Devel Approve button (aka dev_ack) on the JBEAP as well.

**Comment by aloubyansky** [comment]
Sorry for the delay.
While I am more or less fine with the syntax of grouping the list (the parser actually supports it) I don't like the fact that every argument will have to check whether the value is enclosed or not.

This kind of check could possibly be built into ArgumentWithValue.getValue(...), so it automatically covers all the values. A subclass, e.g. ArgumentWithListValue, would probably be even better.

There is actually a workaround, you can simply escape the comma. It's not as convenient as wrapping the whole list but it's there, just in case.

**Comment by ryanemerson** [comment]
@aloubyansky thanks for the feedback and sorry for the slow reply (PTO).  I will rework this to use a subclass ASAP.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

@aloubyansky is this ok now? (I'm assuming the test failures are unrelated; we are seeing failures in those suites elsewhere.)

**Comment by aloubyansky** [comment]
Yes, looks good, thanks!

**Pull request merged**
