### PR TITLE
[WFCORE-7056] Upgrade SSHD from 2.13.2 to 2.14.0

### PR DESCRIPTION
**Pull request by yersan**
Jira issue: https://issues.redhat.com/browse/WFCORE-7056

### CODE REVIEW

**Comment by yersan** [comment]
@ehsavoie / @fjuma This dependency is used in jGit and Elytron, since it is not a minor, could you approve it from your side?

**Comment by yersan** [comment]
@fjuma / @ehsavoie friendly reminder, do you have any issues with this dependency upgrade?

**Review by fjuma — APPROVED** [review]
Thanks @yersan!

**Review by ehsavoie — APPROVED** [review]

**Comment by yersan** [comment]
Thanks @fjuma @ehsavoie

**Pull request merged**
