### PR TITLE
https://issues.jboss.org/browse/WFCORE-869 an option to turn off secu…

### PR DESCRIPTION
**Pull request by aloubyansky**
…rity prompts in the CLI running in non-interactive mode

Thanks,
Alexey

### CODE REVIEW

**Comment by aloubyansky** [comment]
@darranl this is what we talked about, i.e. --no-security-prompts. Please, let me know if you have any comments. Thanks!

**Comment by darranl** [comment]
Looks good but I think you also need to update help.txt with the new argument.

**Comment by aloubyansky** [comment]
Thanks! Updated help.txt.

**Comment by bstansberry** [comment]
retest this please

@aloubyansky IIRC I put the "Hold" label on this because @Gonthim wanted to discuss aspects of it. Is that discussion done? If so I'll remove it.

**Comment by aloubyansky** [comment]
@Gonthim came up with a set of issues/features to be addressed in the non-interactive mode and wanted to look into how this could fit into his effort. Joe, does it all come together? Do you need more time? Thanks!

**Comment by Gonthim** [comment]
Another few days please. I finally got my larger submission that can include this working today, so I need another 2 or 3 to finish it out.

**Comment by bstansberry** [comment]
@Gonthim any news?

**Comment by bstansberry** [comment]
Closing in favor of #1048. Please ping me in HipChat if something still needs to happen here.

**Pull request closed without merging**
