### PR TITLE
[WFCORE-5708] Add a new "org.wildfly.security.http.sfbasic" module.

### PR DESCRIPTION
**Pull request by darranl**
Added the hold label as this will require an update of WildFly Elytron but I need an upstream PR.

https://issues.redhat.com/browse/WFCORE-5708

### CODE REVIEW

**Comment by fjuma** [comment]
Looks good, an update will also be needed in `core-feature-pack-common-licenses.xml`.

**Review by fjuma — APPROVED** [review]
Marking as approved, just needs an update in core-feature-pack-common-licenses.xml.

**Comment by gaol** [comment]
Maybe we need to add `org.wildfly.security.http.sfbasic` to `NOT_USED` in [LayersTestCase of WildFly testsuite](https://github.com/wildfly/wildfly/blob/main/testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java#L71) as well to pass `Galleon Full Integration - Linux` ?

The same for #4879

**Comment by gaol** [comment]
I opened a PR https://github.com/wildfly/wildfly/pull/14970 to address the changes in wildfly

**Pull request merged**
