### PR TITLE
WFCORE-1629: Fixed potential NPE

### PR DESCRIPTION
**Pull request by gastaldi**
modulePath is null when executed inside WildFly Swarm, therefore causing a NPE in this method

### CODE REVIEW

**Comment by gastaldi** [comment]
This patch just performs a null check in modulePath before attempting to discover the console versions

**Comment by bstansberry** [comment]
this is ok to test

**Comment by gastaldi** [comment]
Can we make this fix available in the next WildFly 10 release?

**Comment by bstansberry** [comment]
@gastaldi see #1646

**Comment by gastaldi** [comment]
You are awesome, thank you!

**Pull request merged**
