### PR TITLE
Use a custom thread factory for the ServerService's executors

### PR DESCRIPTION
**Pull request by bstansberry**
Fixes a problem with the ACC for executor threads

### CODE REVIEW

**Comment by ctomc** [comment]
retest this please

**Comment by dmlloyd** [comment]
Brian, would you rather just have a component update PR for jboss-threads with the SM check fix in it?

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@dmlloyd a component upgrade is fine

**Comment by dmlloyd** [comment]
Hopefully obviated by #870 ...

**Comment by bstansberry** [comment]
#870 eliminates the need.

**Pull request closed without merging**
