### PR TITLE
[WFCORE-5566] Use com.sun.net.ssl.internal.ssl.Provider.isFIPS() method for FIPS detection if it exists

### PR DESCRIPTION
**Pull request by Skyllarr**
https://issues.redhat.com/browse/WFCORE-5566

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Thanks @Skyllarr!

**Comment by fjuma** [comment]
@OndrejKotek Did you want to take a look at this one?

**Comment by OndrejKotek** [comment]
@fjuma I have had a look and performed several tests and it seems to work as expected, thanks.

**Comment by jmesnil** [comment]
@Skyllarr thanks

**Pull request merged**
