### PR TITLE
WFCORE-3261 Unignore NotificationSupportImplTestCase.doManyNotificati…

### PR DESCRIPTION
**Pull request by jmartisk**
…onOrderingWithExecutor

https://issues.jboss.org/browse/WFCORE-3261

### CODE REVIEW

**Comment by bstansberry** [comment]
@jmesnil Do you want this unignored? Does running it add value to the testsuite proportionate to the time spent? If not we should just comment out the @Test since it seems we're on a drive to eliminate use of @Ignore. I looks a bit like experimental/debugging type stuff.

**Comment by jmartisk** [comment]
I reduced the number of iterations to make this run within 2 seconds. But if we decide that this test doesn't add enough value, I'm not opposed to removing it instead.

**Comment by jmesnil** [comment]
@jmartisk let's remove it then. It adds no value to the unit test we already have. thanks!

**Comment by jmartisk** [comment]
I updated the PR, the test is now removed.

**Pull request merged**
