### PR TITLE
WFCORE-1043: Show error message when accessing http management consol…

### PR DESCRIPTION
**Pull request by rarguello**
…e of a slave host controller

### CODE REVIEW

**Comment by bstansberry** [comment]
@luck3y can you verify this patch has the effect it says? The patch looks fine to me.

**Comment by bstansberry** [comment]
@rarguello -- we need to ask a one-time housekeeping question; we forgot to do this with the system-d patch:

We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by luck3y** [comment]
@bstansberry yep, taking a look.

**Comment by luck3y** [comment]
Looks fine to me, I get the following message accessing the slave:

Welcome to WildFly

Your WildFly Application Server is running.

You may not access the admin console on this node, all access must come via the master host controller.

**Comment by rarguello** [comment]
I agree with the terms of the MIT License for these contributions.
However, doesn't the HttpManagementAddHandler.java header says it is licensed under the LGPL license?

**Comment by bstansberry** [comment]
Thanks, Ricardo.

Yes the header references LGPL We ask this question of contributors because in the past, contributor agreements applicable to WildFly have generally limited outbound licensing of contributions under LGPL (or  GPL) only. We would now like to have the flexibility to consider other outbound open source licensing options for components of WildFly that may be incompatible with or less restrictive than LGPL  licensing.

An example of such a change would be changing the licensing to use the Apache Software License.

**Pull request merged**
