### PR TITLE
WFCORE-1829 Allow server to start in suspended mode

### PR DESCRIPTION
**Pull request by stuartwdouglas**
https://issues.jboss.org/browse/WFCORE-1829

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please!

**Comment by rhatlapa** [comment]
I've taken a look at the changes and tried it out. I can see there are `:reload` operations containing now `suspend` option. Still I am missing this option for CLI `reload` operation, I believe the suspend option should be available for the CLI `reload` operation.

**Comment by rhatlapa** [comment]
@stuartwdouglas When taking a look, I've noticed this behavior: When having server started with `--suspend` and then call `:reload(suspend=false)`. The server stays suspended after reload instead of being then fully started.

**Comment by stuartwdouglas** [comment]
I have pushed some changes so that if a server was started suspended it will not always be suspended on reload

**Comment by kabir** [comment]
Included by https://github.com/wildfly/wildfly-core/pull/1984

**Pull request merged**
