### PR TITLE
[WFCORE-2588] Deprecating optional dependencies in DDs and manifests

### PR DESCRIPTION
**Pull request by ropalka**
…nifests

### CODE REVIEW

**Comment by bstansberry** [comment]
This one better have a JBEAP and acks. I know that customers use this so removing it and deciding to log warnings about that requires higher visibility than just a PR review.

**Comment by ropalka** [comment]
I created JBEAP-9962. Do I need to reference it in git commit message?

**Comment by dmlloyd** [comment]
I don't think we ever all agreed to deprecate optional deployment module dependencies.  I still believe it is possible to change the mechanism of the dependency to simply query for the module at the correct point in time, and if it's missing, skip the dependency.

**Comment by ropalka** [comment]
Ah right! Now I remember saying you @dmlloyd this should be worked around in DU chain somehow.
Thanks for reminding it. I'm closing this PR and associated JIRAs.

**Comment by bstansberry** [comment]
@ropalka You don't need to reference JBEAP JIRAs in WildFly Core commit messages (including wildfly-core-eap). Nor in upstream WildFly. It's nice to do (but AFAIK not required) in the EAP 7.x branch as there the JBEAP is the true tracker for the change to that code base.

**Pull request closed without merging**
