### PR TITLE
[WFCORE-6103] Add org.aesh dependency for Elytron Tool

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/WFCORE-6103

### CODE REVIEW

**Comment by petrberan** [comment]
Changes in this PR should be merged to WFCORE once the Elytron contains changes from [ELY-2082](https://issues.redhat.com/browse/ELY-2082)

**Comment by bstansberry** [comment]
@fjuma If this is ok conceptually, can you put a hold label on this and make sure whoever does the upgrade PR merges this branch in the their upgrade PR branch? Thanks.

**Comment by fjuma** [comment]
Thanks @bstansberry, will do. I've added the hold label.

**Comment by fjuma** [comment]
This PR is still active.

**Comment by petrberan** [comment]
This PR is still active

**Comment by petrberan** [comment]
This PR is still active

**Comment by bstansberry** [comment]
@petrberan Please coordinate with @fjuma to get this commit included with the PR that does the upgrade that brings in https://issues.redhat.com/browse/ELY-2082. Thanks.

**Comment by darranl** [comment]
I have reopened to check CI again.

I think we are ready to merge the PR to WildFly Elytron and IMO we don't need to wait for that before we merge the module update.  Considering "What is the worst that could happen?" we end up with a module with a redundant dependency but if CI passes nothing more.

**Review by darranl — APPROVED** [review]

**Pull request merged**
