### PR TITLE
Drop transforemrs testing of pre EAP 6.2, drop old transformers code

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by bstansberry** [comment]
Looks good other than needing a rebase!

**Comment by bstansberry** [comment]
Argh!  The legacy-test revert introduced the need for another rebase!

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by ctomc** [comment]
retest this please

**Pull request merged**
