### PR TITLE
[WFCORE-3127] standalone.bat script does not parse JAVA_OPTS containi…

### PR DESCRIPTION
**Pull request by rstancel**
…ng '|' symbol properly

Jira: https://issues.jboss.org/browse/WFCORE-3127

7.1 Jira: https://issues.jboss.org/browse/JBEAP-12448

### CODE REVIEW

**Comment by marekkopecky** [comment]
JBEAP jira for 7.1 is missing

**Comment by rstancel** [comment]
@marekkopecky 7.1 Jira added

**Comment by marekkopecky** [comment]
I don't recommend to merge this jira, more details in jira:
https://issues.jboss.org/browse/JBEAP-12448?focusedCommentId=13442594&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13442594

**Comment by marekkopecky** [comment]
More details: I did some pre-check and this fix causes regression in this case:

1. add set "JAVA_OPTS=%JAVA_OPTS% -Daaa=bbb" to standalone.conf.bat file
2. standalone.bat
3.  jboss-cli.bat -c
    * /system-property=custom:add(value=${aaa:default})
    * /system-property=custom:read-attribute(name=value, resolve-expressions=true)
    * "bbb" is expected, but "default" is returned

**Comment by rstancel** [comment]
@marekkopecky can you please retest now?

**Comment by jmesnil** [comment]
@rstancel @marekkopecky  As this pull request has been held up for a long time, I am closing it to get the pull request queue under control again. Since this is very old now, it will be a very long time until this one will be addressed. Also, I don't have much time to spend on this to evaluate on a case by case basis.

If this is something important to you or the project please feel free to recreate the pull request. That way it will come on top of the pile again, and be looked at again sooner.

If it is a new feature, please follow the new process for features. Ping @wildfly/mergers-core  if you are unsure what this means, and we can help. Please do that before opening the pull request though.

Sorry for any inconvenience!

**Pull request closed without merging**
