### PR TITLE
[WFCORE-4150] Add support for automatically adding and updating credentials in a credential store

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.jboss.org/browse/WFCORE-4150
https://issues.jboss.org/browse/EAP7-676

Analysis document: https://github.com/wildfly/wildfly-proposals/pull/215
WildFly PR with corresponding subsystem changes and documentation: https://github.com/wildfly/wildfly/pull/12538

WildFly PR that updates all existing usages of wildfly-credential-reference_1_0.xsd to the new wildfly-credential-reference_1_1.xsd version to allow the WildFly testsuite to pass with this Core PR (as requested in the comments):
wildfly/wildfly#12601

Depends on #4018

### CODE REVIEW

**Comment by bstansberry** [comment]
Ugh.

```
java.lang.RuntimeException: Default configs are not in line with most recent schemas wildfly-credential-reference_1_0.xsd has been superseded by wildfly-credential-reference_1_1.xsd
	at org.wildfly.dist.subsystem.xml.AbstractValidationUnitTest.discoverXsd(AbstractValidationUnitTest.java:258)
	at org.wildfly.dist.subsystem.xml.AbstractValidationUnitTest$2.resolveResource(AbstractValidationUnitTest.java:208)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1081)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:657)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.resolveSchema(XSDHandler.java:2056)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.constructTrees(XSDHandler.java:1012)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:623)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:613)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:572)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:538)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
	at org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase.parseXml(StandardConfigsXMLValidationUnitTestCase.java:170)
	at org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase.testDomain(StandardConfigsXMLValidationUnitTestCase.java:92)
```

That's going to be a bit of a pain to work around. 

@fjuma can you work up a commit for full that will fix every place wildfly-credential-reference_1_0.xsd is used? That commit will need to be part of the PR used to upgrade core to whatever release brings in wildfly-credential-reference_1_1.xsd.

In the meantime I'll see if I can do some black magic to allow core tests on full to pass when this change is in place.

Hopefully we won't change this schema often. :)

@jamezp fyi

**Comment by bstansberry** [comment]
retest this please

@jamezp fyi if this works, you can see the black magic by looking at

https://ci.wildfly.org/admin/settingsDiffView.html?id=project:WildFlyCore_PullRequest&versionBefore=156&versionAfter=157&actionId=118303

**Comment by jamezp** [comment]
Okay I think that makes sense.

**Comment by bstansberry** [comment]
My black magic worked. Hopefully I haven't damned my immortal soul.

**Comment by fjuma** [comment]
I've created the following PR that updates all existing usages of wildfly-credential-reference_1_0.xsd to the new wildfly-credential-reference_1_1.xsd version to allow the WildFly testsuite to pass with this Core PR:

https://github.com/wildfly/wildfly/pull/12601

**Comment by fjuma** [comment]
I've now updated this to ensure that if an operation that includes a ```credential-reference``` parameter fails for any reason, then the credential store update will get rolled back.

**Comment by tterem** [comment]
Hi @fjuma,

I think your tests are sufficient and I don't plan to add more, however I propose some changes to existing tests: https://github.com/tterem/wildfly-core/commit/b5ee7b011e410579694325048753da820b6922f3

Changes:
* One empty and one non-empty credential store is enough, there is no need for two empty credential stores (as far as I could tell)
* added few assertions
* made checking number of aliases in credential stores using actual numbers instead of a variable - 1 and 2 instead of `numAliases` and `numAliases + 1`. I think it's better to test for exact numbers when we can (we know the initial value is going to be 1).

What do you think about these changes?

**Comment by fjuma** [comment]
@tterem Thanks for the changes, they look good. I have included your commit in this PR.

**Comment by tterem** [comment]
@fjuma thanks, but what about the failing tests? can you fix it?

**Comment by fjuma** [comment]
@tterem The failures in `org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase` do not occur with the changes from the corresponding WildFly PR wildfly/wildfly#12538 (this was mentioned in the comments above but is hard to spot due to the failed runs). As requested previously by Brian, I also have a WildFly PR that updates all existing usages of wildfly-credential-reference_1_0.xsd to the new wildfly-credential-reference_1_1.xsd version to allow the WildFly testsuite to pass with just this Core PR: wildfly/wildfly#12601.

**Comment by tterem** [comment]
@fjuma Thanks for clarification. You were right, I somehow overlooked those comments.

**Comment by fjuma** [comment]
@tterem I've updated this to include the fix for [WFWIP-295](https://issues.redhat.com/browse/WFWIP-295), i.e., only lower case characters and digits are now used when randomly generating an alias:

https://github.com/wildfly/wildfly-core/pull/3925/commits/af4cbf0cec367c5166d3e1eec9a600031de7d3e8#diff-955e48598ef9f41cbfef3231e19871dbR128

**Comment by fjuma** [comment]
I have ported these changes to version 10 of the Elytron subsystem schema and model.

**Comment by fjuma** [comment]
I've rebased this PR. It now also includes the [management bump PR](https://github.com/wildfly/wildfly-core/pull/4124).

**Comment by jmesnil** [comment]
@fjuma I've fixed the CI setup so that it would know about the up-to-be-released wildly-credential-reference_1_1.xsd and all tests pass.

I've deleted a bunch of CI comments that were polluting the conversation too :)

**Comment by fjuma** [comment]
Thanks @jmesnil!

**Comment by jmesnil** [comment]
@fjuma thanks

**Pull request merged**
