### PR TITLE
[WFCORE-3966] JwtValidator jku and kid header parameters

### PR DESCRIPTION
**Pull request by nekdozjam**
https://issues.jboss.org/browse/WFCORE-3966
https://issues.jboss.org/browse/EAP7-1068

Requires ELY-1551
https://issues.jboss.org/browse/ELY-1551

### CODE REVIEW

**Comment by kabir** [comment]
@nekdozjam I believe you are a Red Hat employee?

This is ok to test

**Comment by nekdozjam** [comment]
@kabir Yes

**Comment by jmesnil** [comment]
code is not compiling

**Comment by darranl** [comment]
This one depends on the Elytron change being merged but the PR is needed as we need it to be pre-checked before we can start the merge and tag,

**Comment by jmesnil** [comment]
retest this please

**Comment by darranl** [comment]
This one still depends on an Elytron tag but this is a general issue in the process we need to find a solution for somehow.

To reach a point we can confidently merge a chain of changes we need to get the changes out there and ready for review, I can't start merging and tagging in Elytron until that review is mostly complete as is required by the process.

Where we have a chain of PRs there is a real risk that review of the later PR could affect the API of the earlier PR.

**Comment by jmesnil** [comment]
closing it as it is superseded by #3561

**Pull request closed without merging**
