### PR TITLE
[WFCORE-885] [BZ1063649] Fixing audit log creation with world readabl…

### PR DESCRIPTION
**Pull request by istudens**
…e file permissions.

Peter's commit from https://github.com/jbossas/jboss-eap/pull/1320 restructured for the current WFCORE.

https://issues.jboss.org/browse/WFCORE-885
https://issues.jboss.org/browse/JBEAP-721

### CODE REVIEW

**Comment by bstansberry** [comment]
@darranl Please approve.

**Comment by darranl** [comment]
Looks fine as in porting the original approach to fix this - however as we are now in Java 8 as minimum we should have additional APIs available to us to control permissions.

**Comment by istudens** [comment]
@darranl  You mean PosixFilePermissions, right? I will rework the PR.

**Comment by darranl** [comment]
At this point this PR should be fine as we have used this approach for a while now.  The file permission approach is something however we should switch to subsequently in all cases where we control file permissions.

**Comment by istudens** [comment]
I can easily update the PR to something like the following snippet if you like:
https://gist.github.com/istudens/32884c81249d001c59b3

**Comment by ehsavoie** [comment]
I'm not sure PosixFilePermissions are available to set on all OS (Windows and Solaris might be failing).

**Comment by ehsavoie** [comment]
@istudens I'm afraid this will not work on Windows :( so you will have to go to ACL there or back to the current solution.

**Comment by istudens** [comment]
Ok, so let's keep this PR as is and then we can prepare a JDK8-like general solution and update the entire codebase with it later.

**Pull request merged**
