### PR TITLE
[WFCORE-2415] credential-reference must have defined combinations of constraints

### PR DESCRIPTION
**Pull request by ivassile**
wildfly-core: https://issues.jboss.org/browse/WFCORE-2415

### CODE REVIEW

**Comment by darranl** [comment]
Please submit this directly to ladybird instead, we still potentially have multiple engineers working on Elytron related resources.

**Comment by ivassile** [comment]
@darranl Do we have to submit all WFCORE fixes also to ladybird? Please note that this fix is not for Elytron Subsystem. 
Created PR for ladybird: https://github.com/wildfly-security-incubator/wildfly-core/pull/71

**Comment by darranl** [comment]
For the moment if Elytron related please stick to the incubator.  We are starting to plan to transition from using the incubator over the next few weeks but for now it is the central synchronisation point.

**Comment by bstansberry** [comment]
Closing per the above discussion.

**Pull request closed without merging**
