### PR TITLE
WFCORE-715 Xalan Linkage error : TransformerConfigurationException fo…

### PR DESCRIPTION
**Pull request by ctomc**
…r domain setup

### CODE REVIEW

**Comment by bstansberry** [comment]
ClusteredMessagingTestCase will be ignored as soon as my PR doing so compiles.

**Comment by bstansberry** [comment]
@n1hility I'll leave this one to both in terms of whether it's the correct fix, and whether you want it in WF 10. I added a 3.x label so we can mark stuff we don't want in 10.

**Comment by ctomc** [comment]
It would make sense to get this into EAP7, no mater what the core / WF version is.
currently we have behavior where same application that is using XSLT works in standalone mode but fails in domain, that to me is a blocking bug. The jira has reproducer for this exact scenario.

**Comment by n1hility** [comment]
This isn't the correct fix. Jaxpmodule being removed everywhere is the cause.

**Comment by n1hility** [comment]
I'll fix everything up

**Comment by ctomc** [comment]
@n1hility that would mean that also standalone entry point it wrong as it imports xalan atm.

**Comment by n1hility** [comment]
Actually this specific change was fine since jaxpmodule redirection falls back to the boot module, and the server module is the boot module for domain mode. It is just missing the other default implementations though, which I have added in another PR.

**Pull request closed without merging**
