### PR TITLE
[WFCORE-1450] Use a copy constructor instead of a subclass

### PR DESCRIPTION
**Pull request by bstansberry**
Also includes a commit converting some classes to nested classes of the main class in the file.

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by ctomc** [comment]
@bstansberry while you are at it, I think we should @deprecate this class all together.
It is mostly used by tests and WS subsystem, which can be easily converted to PersistentRD
wdyt?

**Comment by bstansberry** [comment]
I kind of like the class though. :) I'll think about it.

**Comment by bstansberry** [comment]
This is used in 4 subsystems in full, so I'm not going to deprecate it here.

**Pull request merged**
