### PR TITLE
[WFCORE-2745] Upgrade WildFly Elytron to 1.1.0.Beta40 and backport latest integration changes.

### PR DESCRIPTION
**Pull request by darranl**
This PR will depend on the following PR being merged to WildFly first: -
  https://github.com/wildfly/wildfly/pull/10000

~However a coordinated core tag and merge should not be required.~
Kabir: 

> The full tests will fail 
> * on the -Delytron runs (not done on core PRs) without https://github.com/wildfly/wildfly/pull/10023 (https://github.com/jbossas/jboss-eap7/pull/1793)
> * on the normal runs without https://github.com/wildfly/wildfly/pull/10028 (https://github.com/jbossas/jboss-eap7/pull/1799)
> 
> Experimental runs for the latter case: https://ci.wildfly.org/viewLog.html?buildId=57869&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments / https://ci.wildfly.org/viewLog.html?buildId=57867&buildTypeId=WF_WildFlyCoreIntegrationExperimentsWindows&tab=buildResultsDiv

This PR resolves the following issues: -
  https://issues.jboss.org/browse/WFCORE-2415
  https://issues.jboss.org/browse/WFCORE-2500
  https://issues.jboss.org/browse/WFCORE-2715
  https://issues.jboss.org/browse/WFCORE-2547
  https://issues.jboss.org/browse/WFCORE-2745
  https://issues.jboss.org/browse/WFCORE-2753

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I did that 'retest' prematurely, so it will still fail. I pushed this to master-ignore and will test it that way.

**Comment by bstansberry** [comment]
retest this please

The master-ignore run showed failures:

https://ci.wildfly.org/viewLog.html?buildId=57045&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreMasterIgnoreIntegration

**Comment by darranl** [comment]
Retest this please

**Pull request merged**
