### PR TITLE
WFCORE-5871 Invalid operator error launching the server in dash

### PR DESCRIPTION
**Pull request by rosiecki**
https://issues.redhat.com/browse/WFCORE-5871

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
Hi @rosiecki , thanks, notice you don't need to create a new PR, you can just change the commit message by using git on your topic branch.

I'm going to close the other.

**Review by yersan — APPROVED** [review]

**Comment by jmesnil** [comment]
@rosiecki thanks

**Pull request merged**
