### PR TITLE
Update service.bat

### PR DESCRIPTION
**Pull request by simonovdenis**
Script is missing few features, which **Wildfly**/**Commons Daemon** provide:

1. it is not possible to pass properties file to **Wildfly** instance
2. it is not possible to pass environment variables to **Wildfly** instance(more concretely - **JBOSS_MODULEPATH** to specify one or more external module directories)

### CODE REVIEW

**Comment by jamezp** [comment]
this is ok to test

**Comment by jamezp** [comment]
JIRA https://issues.jboss.org/browse/WFCORE-4377

**Comment by bstansberry** [comment]
Thanks!

**Comment by bstansberry** [comment]
@simonovdenis 

The WildFly project would like to change its license from the GNU Lesser General Public License version 2.1 to the Apache Software License 2.0. We feel that ASL 2.0 is a better option for the project and our user community, as we find a project's use of LGPL can be a barrier to adoption in some parts of the software community, while we see no such barriers from use of ASL.

Do you agree to a relicensing of your contributions to the WildFly, WildFly Core or JBoss AS 7 projects from LGPL 2.1 to ASL 2.0?

I'm happy to answer any questions you may have about this, and I hope you are doing well. Thank you for your contributions to WildFly and open source!

Best regards,
Brian Stansberry
WildFly Project Lead

**Pull request merged**
