### PR TITLE
[WFCORE-1729] Bugfix for CliAliasTestCase.testAliasPersistence

### PR DESCRIPTION
**Pull request by mschvarc**
JIRA: https://issues.jboss.org/browse/WFCORE-1729

### CODE REVIEW

**Comment by bstansberry** [comment]
@jfdenise please review

**Comment by jfdenise** [comment]
I am fine with the test fix. I have logged https://issues.jboss.org/browse/WFCORE-1853
in order to track the root cause (the Ctrl-C not being properly handled).

**Comment by mschvarc** [comment]
@jfdenise  
Since the failing test revealed a bug, would you like me to add a new (@Ignored for now) test for ctrlC exit alias saving?

**Comment by jfdenise** [comment]
Good suggestion!
Thanks.

**Comment by mschvarc** [comment]
Retest this please

**Pull request merged**
