### PR TITLE
[WFCORE-3361] GSSCredential obtaining fail caching for fast fallback

### PR DESCRIPTION
**Pull request by honza889**
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1013

https://issues.jboss.org/browse/WFCORE-3361
https://issues.jboss.org/browse/JBEAP-11055

### CODE REVIEW

**Comment by bstansberry** [comment]
I'm dropping the "rebase this" label since making requested changes is going to mean the rebase anyway.

**Comment by honza889** [comment]
@darranl which transformer do you mean in comment above?

**Comment by darranl** [comment]
As you have added a new attribute to version 2 of the management model of this subsystem a transformer is also going to need to be added to reject this attribute if this is used on a later domain controller managing earlier domain controllers as the earlier ones will not understand the attribute.

**Comment by kabir** [comment]
@honza889 https://docs.jboss.org/author/display/WFLY/Domain+Mode+Subsystem+Transformers

**Comment by honza889** [comment]
Should be ok now.

**Pull request merged**
