### PR TITLE
[WFCORE-5321] Upgrading xalan to 2.7.1.jbossorg-5

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFCORE-5321

### CODE REVIEW

**Comment by ropalka** [comment]
The Windows failures are unrelated to this change.

**Comment by bstansberry** [comment]
@fjuma FYI we're still seeing the Keystore... failures on Windows.

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
@ropalka thanks

**Comment by fjuma** [comment]
@bstansberry I'll take another look at the Keystore... failures on Windows.

**Pull request merged**
