### PR TITLE
WFCORE-6328 Add AbstractSubsystemTest subclass for use with tests parameterized via SubsystemSchema

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFCORE-6328

Reduces boilerplate code for subsystem parsing tests that enumerate their namespace versions via SubsystemSchema.

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
@pferraro A quick look at the existing potential tests to refactorize it seems AbstractUndertowSubsystemTestCase could be a good candidate to include in this PR, but I'm not 100% sure without playing with the code.

Could you double-check if it is feasible? otherwise LGTM

**Comment by pferraro** [comment]
@yersan What did you mean by "candidate to include in this PR"?  There are about a dozen subsystems in full (including Undertow) that leverage enumerated schemas and will eventually be migrated to use this subclass - but they are all waiting for this PR to be merged and a subsequent core upgrade.

**Comment by yersan** [comment]
Upss, sorry @pferraro , when I was quickly reviewing the PR I search for possible candidates for both projects (WildFly Full / WildFly Core). I saw a lot of candidates on WildFly Full but I made a mistake highlighting  `AbstractUndertowSubsystemTestCase` here, I thought that test was in WildFly Core but in reality, it is in WildFly Full.

I guess the undertow word made me automatically think that it was part of WIldFly Core.

**Review by yersan — APPROVED** [review]

**Comment by yersan** [comment]
Thanks @pferraro

**Pull request merged**
