### PR TITLE
Undertow 1.3.0.Beta1

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by darranl** [comment]
@luck3y Are jobs going crazy again?

**Comment by luck3y** [comment]
@darranl Not that I know of, did this run > 1 again?

**Comment by darranl** [comment]
@luck3y I think it only ran once but it should not have run at all as this PR is five years old.

**Comment by luck3y** [comment]
The most likely case for this then is GH returning the PR as modified for some reason. Which may have just been an API change or something. I'll see if I can find out why it triggered as updated.

**Pull request merged**
