### PR TITLE
WFCORE-1349 Upgrate JBoss Marshalling to >= 1.4.11.Final

### PR DESCRIPTION
**Pull request by oscerd**
Hi all,

This PR is related to:
https://issues.jboss.org/browse/WFCORE-1349

Thanks,
Andrea

### CODE REVIEW

**Comment by rhusar** [comment]
Already included in https://github.com/wildfly/wildfly-core/pull/1608.

**Comment by oscerd** [comment]
Sorry.

**Comment by dmlloyd** [comment]
No worries - nobody is expected to know what is in every pull request! :)

**Comment by rhusar** [comment]
Don't worry, thanks.

**Comment by oscerd** [comment]
I'll try with something else :-)

**Pull request closed without merging**
