### PR TITLE
[WFCORE-6357] Remove deprecated AttributeDefinition API

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFCORE-6357

Requires https://github.com/wildfly/wildfly/pull/16864 first.

### CODE REVIEW

**Review by pferraro — CHANGES_REQUESTED** [review]
Can the readers/writers in this PR get the same treatment as those in https://github.com/wildfly/wildfly/pull/16864 ?

**Comment by darranl** [comment]
CI running after the merge to WildFly

**Comment by bstansberry** [comment]
@pferraro I added a commit.

**Review by yersan — APPROVED** [review]

**Review by pferraro — APPROVED** [review]

**Pull request merged**
