### PR TITLE
[WFCORE-4788] Upgrade httpclient 4.5.10

### PR DESCRIPTION
**Pull request by jmesnil**
* Also upgrade httpcomponents:httpcore to 4.4.12

JIRA: https://issues.redhat.com/browse/WFCORE-4788

### CODE REVIEW

**Comment by bstansberry** [comment]
@jimma @ronsigal Any concerns from the CXF/RESTEasy point of view?

**Comment by ronsigal** [comment]
I'll take a look. Thanks, Brian.

**Comment by jimma** [comment]
Httpclient 4.5.10  and httpcore 4.4.12 upgrade is OK for CXF/JBossWS. @bstansberry

**Comment by ronsigal** [comment]
Hey Brian,

I see that RESTEasy 3.x has already upgraded to httpclient 4.5.10

-Ron

**Comment by jmesnil** [comment]
@ronsigal The failure in the integration test is related to the upgrade (e.g. https://ci.wildfly.org/viewLog.html?buildId=180159&buildTypeId=WildFlyCore_PullRequest_WildFlyCoreFullIntegration#testNameId4963075477194842595)

The failure in PreservePathTestCase was somehow anticipated as [the comment](https://github.com/wildfly/wildfly/blob/512b7867fb1941ed70a91f708f6f8817431ffa38/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/servlet/preservepath/PreservePathTestCase.java#L143-L144) implies. The future is now :)

Can this test be updated to pass whether there is an additional `/` in the URL?

**Comment by ronsigal** [comment]
@jmesnil, did you mean to direct the question to me? It's not a RESTEasy test. I don't mind looking at it, but probably there's someone better suited ...

**Comment by jmesnil** [comment]
@ronsigal never mind, I thought that you were involved in that test but that's not the case. I'll take of it, thanks

**Comment by bstansberry** [comment]
@jmesnil I approved this even though it needs a rebase and you're sorting the test issue, as the basic change is fine. Feel free to merge when you're ready.

**Comment by bstansberry** [comment]
@jmesnil https://github.com/wildfly/wildfly/pull/12888 is merged

**Pull request merged**
