### PR TITLE
[WFCORE-4214] VaultPasswordsInCLITestCase fails with Elytron profile

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/WFCORE-4214

### CODE REVIEW

**Comment by petrberan** [comment]
As discussed with Darran Lofthouse, this test case should not run with -Delytron profile as it is vault related. However, running this test with -Delytron profile causes failures in tests following this one in manualmode module, so a check of whether Elytron is used.

In case of Elytron use, this test case is skipped, allowing following tests to be run properly and not to fail.

**Review by darranl — APPROVED** [review]

**Comment by jmesnil** [comment]
@petrberan thanks

**Pull request merged**
