### PR TITLE
[WFCORE-5092] Added passing NOPAUSE=Y from service.bat to jboss-cli.bat

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFCORE-5092

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
Hello @lvydra , just for your info, EAP has its own service.bat script, could you evaluate if do we need to backport this upstream change so it is included in the next EAP release based on this WildFly release?

In addition to that, I got confused with the commit and PR descriptions, they suggest there is something added from service.bat to  jboss-cli.bat, how is  jboss-cli.bat involved here?

**Comment by lvydra** [comment]
Hi @yersan , sorry for the confusion, I should have made it more clear in the description. The parameter which is added in service.bat, is later passed to jboss-cli.bat, where its absence (behaviorally by "Press any key ..." prompt) has been initially noted.

**Comment by yersan** [comment]
> sorry for the confusion, I should have made it more clear in the description. The parameter which is added in service.bat, is later passed to jboss-cli.bat, where its absence has been initially noted (behaviorally by "Press any key ..." prompt) .

Hi @lvydra , no worries, thanks for clearing it up. If you finally need to backport these changes, please file a PR on https://github.com/jbossas/wildfly-to-product

**Comment by lvydra** [comment]
The change itself is not the cause of reporters problem, that one was identified and resolved through communication on issue. Intention of change is only to make starting and stopping params consistent and get rid of warning which has been source of some confusion. So I'm not sure if backporting to EAP is necessary.

**Review by jamezp — APPROVED** [review]

**Comment by jmesnil** [comment]
@lvydra thanks

**Pull request merged**
