### PR TITLE
[WFCORE-4911] Remove org.apache.xml-resolver (it has been moved to WildFly)

### PR DESCRIPTION
**Pull request by parsharma**
JIRA: https://issues.redhat.com/browse/WFCORE-4911

WildFly counterpart: https://github.com/wildfly/wildfly/pull/13173

### CODE REVIEW

**Comment by jmesnil** [comment]
This is ok to test.

**Comment by bstansberry** [comment]
@parsharma Kabir went ahead and filed https://issues.redhat.com/browse/WFCORE-4911 so can you add WFCORE-4911 to the commit message and change the PR title to use that? Thanks.

**Comment by darranl** [comment]
Do we have a link to the corresponding WildFly PR to cross reference?

**Comment by kabir** [comment]
@darranl  I added https://github.com/wildfly/wildfly/pull/13173 in the description

@parsharma it helps reviewers to include as much information (as links) as possible :)

@jmesnil Since the upstream one has been merged, I think we can remove the hold label?

**Comment by darranl** [comment]
If that is the case I will include this in the batch I am preparing ready for one more round of CI

**Pull request merged**
