### PR TITLE
Evaluate to the current year in code templates.

### PR DESCRIPTION
**Pull request by soul2zimate**
it's 2018 now.

### CODE REVIEW

**Comment by bstansberry** [comment]
What I've read on this subject from Red Hat legal is that if we even have dates like these in our headers we should not be changing them like this.

**Comment by darranl** [comment]
This is the template used by Eclipse for new classes added using Eclipse - not a template to retrospectively edit other years.

**Comment by soul2zimate** [comment]
Should I update to fixed value 2018 instead of property value?

**Comment by darranl** [comment]
@soul2zimate I think your current proposed change is correct.

**Comment by bstansberry** [comment]
Thanks, Darran!

**Pull request merged**
